package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	DisconnectReasonUnknown int32 = iota
	DisconnectReasonCantConnectNoInternet
	DisconnectReasonNoPermissions
	DisconnectReasonUnrecoverableError
	DisconnectReasonThirdPartyBlocked
	DisconnectReasonThirdPartyNoInternet
	DisconnectReasonThirdPartyBadIP
	DisconnectReasonThirdPartyNoServerOrServerLocked
	DisconnectReasonVersionMismatch
	DisconnectReasonSkinIssue
	DisconnectReasonInviteSessionNotFound
	DisconnectReasonEduLevelSettingsMissing
	DisconnectReasonLocalServerNotFound
	DisconnectReasonLegacyDisconnect
	DisconnectReasonUserLeaveGameAttempted
	DisconnectReasonPlatformLockedSkinsError
	DisconnectReasonRealmsWorldUnassigned
	DisconnectReasonRealmsServerCantConnect
	DisconnectReasonRealmsServerHidden
	DisconnectReasonRealmsServerDisabledBeta
	DisconnectReasonRealmsServerDisabled
	DisconnectReasonCrossPlatformDisabled
	DisconnectReasonCantConnect
	DisconnectReasonSessionNotFound
	_
	DisconnectReasonServerFull
	DisconnectReasonInvalidPlatformSkin
	DisconnectReasonEditionVersionMismatch
	DisconnectReasonEditionMismatch
	DisconnectReasonLevelNewerThanExeVersion
	DisconnectReasonNoFailOccurred
	DisconnectReasonBannedSkin
	DisconnectReasonTimeout
	DisconnectReasonServerNotFound
	DisconnectReasonOutdatedServer
	DisconnectReasonOutdatedClient
	_
	DisconnectReasonMultiplayerDisabled
	DisconnectReasonNoWiFi
	_
	DisconnectReasonNoReason
	DisconnectReasonDisconnected
	DisconnectReasonInvalidPlayer
	DisconnectReasonLoggedInOtherLocation
	DisconnectReasonServerIdConflict
	DisconnectReasonNotAllowed
	DisconnectReasonNotAuthenticated
	DisconnectReasonInvalidTenant
	DisconnectReasonUnknownPacket
	DisconnectReasonUnexpectedPacket
	DisconnectReasonInvalidCommandRequestPacket
	DisconnectReasonHostSuspended
	DisconnectReasonLoginPacketNoRequest
	DisconnectReasonLoginPacketNoCert
	DisconnectReasonMissingClient
	DisconnectReasonKicked
	DisconnectReasonKickedForExploit
	DisconnectReasonKickedForIdle
	DisconnectReasonResourcePackProblem
	DisconnectReasonIncompatiblePack
	DisconnectReasonOutOfStorage
	DisconnectReasonInvalidLevel
	_
	DisconnectReasonBlockMismatch
	DisconnectReasonInvalidHeights
	DisconnectReasonInvalidWidths
	_
	_
	DisconnectReasonShutdown
	_
	DisconnectReasonLoadingStateTimeout
	DisconnectReasonResourcePackLoadingFailed
	DisconnectReasonSearchingForSessionLoadingScreenFailed
	DisconnectReasonNetherNetProtocolVersion
	DisconnectReasonSubsystemStatusError
	DisconnectReasonEmptyAuthFromDiscovery
	DisconnectReasonEmptyUrlFromDiscovery
	DisconnectReasonExpiredAuthFromDiscovery
	DisconnectReasonUnknownSignalServiceSignInFailure
	DisconnectReasonXBLJoinLobbyFailure
	DisconnectReasonUnspecifiedClientInstanceDisconnection
	DisconnectReasonNetherNetSessionNotFound
	DisconnectReasonNetherNetCreatePeerConnection
	DisconnectReasonNetherNetICE
	DisconnectReasonNetherNetConnectRequest
	DisconnectReasonNetherNetConnectResponse
	DisconnectReasonNetherNetNegotiationTimeout
	DisconnectReasonNetherNetInactivityTimeout
	DisconnectReasonStaleConnectionBeingReplaced
	_
	DisconnectReasonBadPacket
	DisconnectReasonNetherNetFailedToCreateOffer
	DisconnectReasonNetherNetFailedToCreateAnswer
	DisconnectReasonNetherNetFailedToSetLocalDescription
	DisconnectReasonNetherNetFailedToSetRemoteDescription
	DisconnectReasonNetherNetNegotiationTimeoutWaitingForResponse
	DisconnectReasonNetherNetNegotiationTimeoutWaitingForAccept
	DisconnectReasonNetherNetIncomingConnectionIgnored
	DisconnectReasonNetherNetSignalingParsingFailure
	DisconnectReasonNetherNetSignalingUnknownError
	DisconnectReasonNetherNetSignalingUnicastDeliveryFailed
	DisconnectReasonNetherNetSignalingBroadcastDeliveryFailed
	DisconnectReasonNetherNetSignalingGenericDeliveryFailed
	DisconnectReasonEditorMismatchEditorWorld
	DisconnectReasonEditorMismatchVanillaWorld
	DisconnectReasonWorldTransferNotPrimaryClient
	DisconnectReasonRequestServerShutdown
	DisconnectReasonClientGameSetupCancelled
	DisconnectReasonClientGameSetupFailed
	_
	DisconnectReasonNetherNetSignalingSigninFailed
	DisconnectReasonSessionAccessDenied
	DisconnectReasonServiceSigninIssue
	DisconnectReasonNetherNetNoSignalingChannel
	DisconnectReasonNetherNetNotLoggedIn
	DisconnectReasonNetherNetClientSignalingError
	DisconnectReasonSubClientLoginDisabled
	DisconnectReasonDeepLinkTryingToOpenDemoWorldWhileSignedIn
	DisconnectReasonAsyncJoinTaskDenied
	DisconnectReasonRealmsTimelineRequired
	DisconnectReasonGuestWithoutHost
	DisconnectReasonFailedToJoinExperience
	DisconnectReasonNetherNetDataChannelClosed
	DisconnectReasonDiscoveryEnvironmentMismatch
	DisconnectReasonHostWithoutKeys
)

// Disconnect may be sent by the server to disconnect the client using an optional message to send as the
// disconnect screen.
type Disconnect struct {
	// Reason is the reason for the disconnection. This affects the error code displayed on the Ore UI
	// disconnection screen and is one of the constants above.
	Reason int32
	// HideDisconnectionScreen specifies if the disconnection screen should be hidden when the client is
	// disconnected, meaning it will be sent directly to the main menu.
	HideDisconnectionScreen bool
	// Message is an optional message to show when disconnected. This message is only written if the
	// HideDisconnectionScreen field is set to true.
	Message string
	// FilteredMessage is a filtered version of Message with all the profanity removed. The client will use
	// this over Message if this field is not empty and they have the "Filter Profanity" setting enabled.
	FilteredMessage string
}

// ID ...
func (*Disconnect) ID() uint32 {
	return IDDisconnect
}

func (pk *Disconnect) Marshal(io protocol.IO) {
	io.Varint32(&pk.Reason)
	io.Bool(&pk.HideDisconnectionScreen)
	if !pk.HideDisconnectionScreen {
		io.String(&pk.Message)
		io.String(&pk.FilteredMessage)
	}
}
