package p2p

import (
	"encoding/json"
	"maps"
	"slices"

	"github.com/df-mc/go-xsapi/v2/mpsd"
	"github.com/google/uuid"
)

// World represents a player-hosted world that can be joined.
// It typically mirrors the custom properties of the multiplayer
// session published by the host.
type World struct {
	// Joinability reports how the World is exposed to other players.
	// Unlike [BroadcastSetting], it does not cover every option available
	// in the Multiplayer settings screen.
	Joinability string
	// HostName is the host's display name.
	// It is typically the gamertag of the host.
	// It is displayed below [World.HostName] in the world card.
	HostName string `json:"hostName"`
	// OwnerID is the XUID for the host of the World.
	OwnerID string `json:"ownerId"`
	// RakNetGUID is the GUID assigned to the RakNet listener of the host.
	// It is only populated when the host is playing on an experience server that
	// listens on RakNet. Otherwise, it remains empty because most sessions
	// no longer use RakNet.
	RakNetGUID string `json:"rakNetGUID"`
	// Version is the game version used by the host.
	Version string `json:"version"`
	// LevelID is the ID of the level loaded in the World.
	LevelID string `json:"levelId"`
	// WorldName is the display name of the World.
	// It is displayed above the [World.HostName] in world card.
	WorldName string `json:"worldName"`
	// WorldType is the default game mode configured for the World.
	WorldType string `json:"worldType"`
	// Protocol is the protocol version used by the host.
	// If it differs from the joining player's client version, the
	// player is shown an error when attempting to join before sending
	// any packets to the host.
	Protocol int `json:"protocol"`
	// MemberCount is the current number of players connected to the World.
	MemberCount int
	// MaxMemberCount is the maximum number of players that can be
	// connected to the World. It may change during the session if the
	// host runs the /setmaxplayers command.
	MaxMemberCount int
	// BroadcastSetting is the broadcast visibility setting chosen by the host.
	// It remains unchanged for the lifetime of the session.
	// It is one of the constants defined below.
	BroadcastSetting BroadcastSetting
	// LANGame indicates whether the World is available to players on the
	// same local network as the host's.
	LANGame bool `json:"LanGame"`
	// EditorWorld indicates whether the World is in Editor Mode.
	EditorWorld bool `json:"isEditorWorld"`
	// Hardcore indicates whether the World is in Hardcore Mode.
	Hardcore bool `json:"isHardcore"`
	// TransportLayer indicates the transport layer used to connect to
	// the host. It is typically one of the constants defined below.
	TransportLayer int
	// OnlineCrossPlatformGame indicates whether the World is available
	// through cross-platform play.
	OnlineCrossPlatformGame bool
	// CrossPlayDisabled indicates whether the World is restricted to
	// players on the same platform.
	CrossPlayDisabled bool
	// TitleID identifies the title used to host the World.
	// It is typically zero for most sessions.
	TitleID int `json:"TitleId"`
	// SupportedConnections lists the connection methods that may be used
	// to connect to the host.
	SupportedConnections []Connection

	// Nonces maps each joining player's XUID to the nonce generated by the host
	// for that player. The host publishes this map after the player joins the
	// Xbox Live multiplayer session. See [login.ClientData.Nonce] for details on
	// how the nonce is used during connection establishment.
	Nonces map[string]string `json:"nonces"`

	// ExperienceID is the ID of the gathering experience that the host
	// is currently playing. When a player joins a gathering experience
	// (also called an online experience), it publishes a multiplayer
	// session to Xbox Live to advertise its presence.
	// It is only populated when the host is playing a gathering experience.
	ExperienceID uuid.UUID `json:"ExperienceId,omitzero"`
	// ExperienceWorldID is the ID of the world the host is currently
	// playing within the gathering experience.
	// It is only populated when the host is playing a gathering experience.
	ExperienceWorldID uuid.UUID `json:"ExperienceWorldId,omitzero"`
	// FriendID is the host's PlayFab ID.
	// It is only populated when the host is playing a gathering experience.
	FriendID string `json:"FriendId,omitempty"`

	// handleID is the identifier of the activity associated with the World.
	handleID uuid.UUID
	// client is the API Client bound to this World.
	// It is only present when the World is part of the results returned by [Client.Worlds].
	client *Client
}

// clone clones the World so that can be returned to user without worrying about
// race conditions.
func (w World) clone() World {
	w2 := w
	w2.Nonces = maps.Clone(w.Nonces)
	w2.SupportedConnections = slices.Clone(w.SupportedConnections)
	return w2
}

// HandleID returns the identifier for the Xbox Live multiplayer session handle associated with the World.
func (w World) HandleID() uuid.UUID {
	return w.handleID
}

// Connection represents a way to connect to a World.
type Connection struct {
	// Type identifies the connection subtype.
	// Together with the parent [World.TransportLayer], it describes how
	// the player should connect to the World.
	Type int `json:"ConnectionType"`
	// HostIPAddress is the IP address of the RakNet listener.
	// It is typically empty for most sessions because RakNet is no longer supported.
	HostIPAddress string `json:"HostIpAddress"`
	// HostPort is the port of the RakNet listener.
	// It is typically empty for most sessions because RakNet is no longer supported.
	HostPort uint16
	// NetherNetID is the network ID of the NetherNet network for the host.
	NetherNetID json.Number `json:"NetherNetId"`
	// PlayerMessagingID is the player messaging ID of the host.
	// When joining a World, clients use it together with [NetherNetID]
	// as the destination for signaling messages needed to establish the
	// WebRTC connection to the host.
	// It is only populated when Type is [ConnectionTypeSignalingOverJSONRPC].
	PlayerMessagingID uuid.UUID `json:"PmsgId,omitzero"`
}

// Valid reports whether c is a complete NetherNet signaling connection
// supported by this package. Unsupported, LAN-only, or future connection types
// may still be decoded from MPSD data, but they are ignored when selecting a
// connection to dial.
func (c Connection) Valid() bool {
	switch c.Type {
	case ConnectionTypeSignalingOverJSONRPC:
		return c.PlayerMessagingID != uuid.Nil && c.NetherNetID != ""
	case ConnectionTypeSignalingOverWebSocket:
		return c.NetherNetID != ""
	default:
		return false
	}
}

// Connection returns the first supported NetherNet signaling connection
// advertised by w. Non-NetherNet worlds are rejected because this package
// currently implements only NetherNet peer-to-peer joins. Unsupported connection
// entries are ignored so a future or auxiliary entry does not make an otherwise
// joinable world unusable.
func (w World) Connection() (Connection, bool) {
	if w.TransportLayer != TransportLayerNetherNet {
		return Connection{}, false
	}
	for _, c := range w.SupportedConnections {
		if c.Valid() {
			return c, true
		}
	}
	return Connection{}, false
}

// Address returns a string that can be used as the address when dialing a new Conn.
func (c Connection) Address() string {
	switch c.Type {
	case ConnectionTypeSignalingOverWebSocket:
		return c.NetherNetID.String()
	case ConnectionTypeSignalingOverJSONRPC:
		return c.PlayerMessagingID.String()
	default:
		panic("unreachable")
	}
}

const (
	// TransportLayerRakNet indicates that the World is using RakNet as the transport layer.
	// It is not seen anymore for regular worlds since RakNet is no longer supported by the clients.
	TransportLayerRakNet = iota << 1
	// TransportLayerNetherNet indicates that the World is using NetherNet as the transport layer.
	TransportLayerNetherNet
)

const (
	// ConnectionTypeSignalingOverJSONRPC indicates that a JSON-RPC over
	// WebSocket connection is used for the WebRTC signaling needed to
	// establish a NetherNet connection.
	// This is the connection type used by most sessions.
	ConnectionTypeSignalingOverJSONRPC = 7
	// ConnectionTypeSignalingOverWebSocket indicates that a WebSocket
	// connection carrying plain JSON messages is used for the WebRTC
	// signaling needed to establish a NetherNet connection.
	// It is only used by the host when the 'mc-host-json-rpc' parameter
	// is set to 'false' in [github.com/sandertv/gophertunnel/minecraft/service.Token.Configuration].
	ConnectionTypeSignalingOverWebSocket = 3
	// ConnectionTypeSignalingOverLAN indicates that LAN is used for the
	// WebRTC signaling needed to establish a NetherNet connection.
	// It is only valid in
	// [github.com/df-mc/go-nethernet/discovery.ServerData.ConnectionType].
	ConnectionTypeSignalingOverLAN = 4
)

const (
	// JoinabilityInviteOnly indicates that the World is only visible to players
	// invited by the participants of the World.
	JoinabilityInviteOnly = "invite_only"
	// JoinabilityFriends indicates that the World is visible to friends of the host.
	JoinabilityFriends = "joinable_by_friends"
)

const (
	// BroadcastSettingInviteOnly indicates that only players invited by
	// a participant in the World may join.
	BroadcastSettingInviteOnly BroadcastSetting = iota + 1
	// BroadcastSettingFriendsOnly indicates that the host's friends may
	// join the World.
	BroadcastSettingFriendsOnly
	// BroadcastSettingFriendsOfFriends indicates that friends of the
	// host's friends may join the World.
	BroadcastSettingFriendsOfFriends
)

// BroadcastSetting represents the access policy configured by the host
// for the World.
type BroadcastSetting int

// JoinRestriction returns the
// [github.com/df-mc/go-xsapi/v2/mpsd.PublishConfig.JoinRestriction]
// value for the BroadcastSetting.
func (s BroadcastSetting) JoinRestriction() string {
	switch s {
	case BroadcastSettingInviteOnly:
		return mpsd.SessionRestrictionLocal
	case BroadcastSettingFriendsOnly, BroadcastSettingFriendsOfFriends:
		return mpsd.SessionRestrictionFollowed
	default:
		panic("unreachable")
	}
}

// ReadRestriction returns the
// [github.com/df-mc/go-xsapi/v2/mpsd.PublishConfig.ReadRestriction]
// value for the BroadcastSetting.
func (s BroadcastSetting) ReadRestriction() string {
	switch s {
	case BroadcastSettingInviteOnly, BroadcastSettingFriendsOnly, BroadcastSettingFriendsOfFriends:
		return mpsd.SessionRestrictionFollowed
	default:
		panic("unreachable")
	}
}

// Valid reports whether s is a valid BroadcastSetting value.
func (s BroadcastSetting) Valid() bool {
	switch s {
	case BroadcastSettingInviteOnly, BroadcastSettingFriendsOnly, BroadcastSettingFriendsOfFriends:
		return true
	default:
		return false
	}
}
