// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          35 (0x23)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ActorPickRequest Player clicks on an actor in the world, eg a chicken.
type ActorPickRequest struct {
	// ActorID Target Actor ID
	ActorID int64
	// MaxSlots number of empty hotbar slots (to decide whether to overwrite a slot or add it to an empty one)
	MaxSlots uint8
	// WithData whether we want to store the NBT data along with the item
	WithData bool
}

// ID ...
func (*ActorPickRequest) ID() uint32 {
	return IDActorPickRequest
}

func (pk *ActorPickRequest) Marshal(io protocol.IO) {
	io.Int64(&pk.ActorID)
	io.Uint8(&pk.MaxSlots)
	io.Bool(&pk.WithData)
}
