// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          27 (0x1B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ActorEventNONE = iota
	ActorEventJUMP
	ActorEventHURT
	ActorEventDEATH
	ActorEventStartAttacking
	ActorEventStopAttacking
	ActorEventTamingFailed
	ActorEventTamingSucceeded
	ActorEventShakeWetness
	ActorEventEatGrass
	ActorEventFishhookBubble
	ActorEventFishhookFishpos
	ActorEventFishhookHooktime
	ActorEventFishhookTease
	ActorEventSquidFleeing
	ActorEventZombieConverting
	ActorEventPlayAmbient
	ActorEventSpawnAlive
	ActorEventStartOfferFlower
	ActorEventStopOfferFlower
	ActorEventLoveHearts
	ActorEventVillagerAngry
	ActorEventVillagerHappy
	ActorEventWitchHatMagic
	ActorEventFireworksExplode
	ActorEventInLoveHearts
	ActorEventSilverfishMergeAnim
	ActorEventGuardianAttackSound
	ActorEventDrinkPotion
	ActorEventThrowPotion
	ActorEventPrimeTntcart
	ActorEventPrimeCreeper
	ActorEventAirSupply
	ActorEventDeprecatedAddPlayerLevels
	ActorEventGuardianMiningFatigue
	ActorEventAgentSwingArm
	ActorEventDragonStartDeathAnim
	ActorEventGroundDust
	ActorEventSHAKE
	ActorEventFEED
	ActorEventBabyAge
	ActorEventInstantDeath
	ActorEventNotifyTrade
	ActorEventLeashDestroyed
	ActorEventCaravanUpdated
	ActorEventTalismanActivate
	ActorEventDeprecatedUpdateStructureFeature
	ActorEventPlayerSpawnedMob
	ActorEventPUKE
	ActorEventUpdateStackSize
	ActorEventStartSwimming
	ActorEventBalloonPop
	ActorEventTreasureHunt
	ActorEventSummonAgent
	ActorEventFinishedChargingItem
	ActorEventActorGrowUp
	ActorEventVibrationDetected
	ActorEventDrinkMilk
	ActorEventShakeWetnessStop
	ActorEventKineticDamageDealt
)

// ActorEvent All kinds of actor state changes (see Actor::handleEntityEvent).
type ActorEvent struct {
	EntityRuntimeID uint64
	EventType uint8
	Data int32
}

// ID ...
func (*ActorEvent) ID() uint32 {
	return IDActorEvent
}

func (pk *ActorEvent) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	io.Uint8(&pk.EventType)
	io.Varint32(&pk.Data)
}
