// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          166 (0xA6)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AddVolumeEntity Sends a volume entity's definition and components from server to client.
type AddVolumeEntity struct {
	EntityNetworkID uint32
	Components map[string]any
	JSONIdentifier string
	InstanceName string
	MinBounds protocol.BlockPos
	MaxBounds protocol.BlockPos
	DimensionType int32
	// EngineVersion Semantic version string
	EngineVersion string
}

// ID ...
func (*AddVolumeEntity) ID() uint32 {
	return IDAddVolumeEntity
}

func (pk *AddVolumeEntity) Marshal(io protocol.IO) {
	io.Varuint32(&pk.EntityNetworkID)
	io.NBT(&pk.Components, nbt.NetworkLittleEndian)
	io.String(&pk.JSONIdentifier)
	io.String(&pk.InstanceName)
	io.UBlockPos(&pk.MinBounds)
	io.UBlockPos(&pk.MaxBounds)
	io.Varint32(&pk.DimensionType)
	io.String(&pk.EngineVersion)
}
