// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          166 (0xA6)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AddVolumeEntity Sends a volume entity's definition and components from server to client.
type AddVolumeEntity struct {
	EntityNetworkID uint32
	Components any
	JSONIdentifier string
	InstanceName string
	MinBounds protocol.BlockPos
	MaxBounds protocol.BlockPos
	DimensionType int32
	// EngineVersion Semantic version string
	EngineVersion string
}

// ID ...
func (*AddVolumeEntity) ID() uint32 {
	return IDAddVolumeEntity
}

func (pk *AddVolumeEntity) Marshal(io protocol.IO) {
	io.Varuint32(&pk.EntityNetworkID)
	// TODO: Components - unresolved reference: #/definitions/3172631924
	io.String(&pk.JSONIdentifier)
	io.String(&pk.InstanceName)
	io.BlockPos(&pk.MinBounds)
	io.BlockPos(&pk.MaxBounds)
	io.Varint32(&pk.DimensionType)
	io.String(&pk.EngineVersion)
}
