// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          22 (0x16)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AddPainting Sends the information for a new painting actor from server to client.
type AddPainting struct {
	EntityUniqueID int64
	EntityRuntimeID uint64
	Position mgl32.Vec3
	Direction int32
	Title string
}

// ID ...
func (*AddPainting) ID() uint32 {
	return IDAddPainting
}

func (pk *AddPainting) Marshal(io protocol.IO) {
	io.Varint64(&pk.EntityUniqueID)
	io.Varuint64(&pk.EntityRuntimeID)
	io.Vec3(&pk.Position)
	io.Varint32(&pk.Direction)
	io.String(&pk.Title)
}
