// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          89 (0x59)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AddBehaviorTree Add Behavior Tree
type AddBehaviorTree struct {
	BehaviorTreeStructure string
}

// ID ...
func (*AddBehaviorTree) ID() uint32 {
	return IDAddBehaviorTree
}

// Marshal ...
func (pk *AddBehaviorTree) Marshal(io protocol.IO) {
	io.String(&pk.BehaviorTreeStructure)
}
