// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          89 (0x59)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AddBehaviorTree Add Behavior Tree
type AddBehaviorTree struct {
	BehaviorTreeStructure string
}

// ID ...
func (*AddBehaviorTree) ID() uint32 {
	return IDAddBehaviorTree
}

func (pk *AddBehaviorTree) Marshal(io protocol.IO) {
	io.String(&pk.BehaviorTreeStructure)
}
