// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          304 (0x130)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	AgentAnimationArmSwing = iota
	AgentAnimationShrug
)

// AgentAnimation Broadcasted to other players when an Agent performs an animation so it gets properly replicated.
type AgentAnimation struct {
	AgentAnimation uint8
	RuntimeID uint64
}

// ID ...
func (*AgentAnimation) ID() uint32 {
	return IDAgentAnimation
}

// Marshal ...
func (pk *AgentAnimation) Marshal(io protocol.IO) {
	io.Uint8(&pk.AgentAnimation)
	io.Varuint64(&pk.RuntimeID)
}
