// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          181 (0xB5)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	AgentActionTypeAttack = iota
	AgentActionTypeCollect
	AgentActionTypeDestroy
	AgentActionTypeDetectRedstone
	AgentActionTypeDetectObstacle
	AgentActionTypeDrop
	AgentActionTypeDropAll
	AgentActionTypeInspect
	AgentActionTypeInspectData
	AgentActionTypeInspectItemCount
	AgentActionTypeInspectItemDetail
	AgentActionTypeInspectItemSpace
	AgentActionTypeInteract
	AgentActionTypeMove
	AgentActionTypePlaceBlock
	AgentActionTypeTill
	AgentActionTypeTransferItemTo
	AgentActionTypeTurn
)

// AgentActionEvent packet containing data of Agent Action Type
type AgentActionEvent struct {
	RequestID string
	Action int32
	Response []byte
}

// ID ...
func (*AgentActionEvent) ID() uint32 {
	return IDAgentActionEvent
}

func (pk *AgentActionEvent) Marshal(io protocol.IO) {
	io.String(&pk.RequestID)
	io.Int32(&pk.Action)
	io.ByteSlice(&pk.Response)
}
