// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          158 (0x9E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AnimateEntity The AnimateEntityPacket is used to trigger a one - off animation on the client it is sent to.
type AnimateEntity struct {
	MAnimation string
	MNextState string
	MStopExpression string
	MStopExpressionVersion int32
	MController string
	MBlendOutTime float32
	MRuntimeIds []uint64
}

// ID ...
func (*AnimateEntity) ID() uint32 {
	return IDAnimateEntity
}

func (pk *AnimateEntity) Marshal(io protocol.IO) {
	io.String(&pk.MAnimation)
	io.String(&pk.MNextState)
	io.String(&pk.MStopExpression)
	io.Int32(&pk.MStopExpressionVersion)
	io.String(&pk.MController)
	io.Float32(&pk.MBlendOutTime)
	protocol.FuncSlice(io, &pk.MRuntimeIds, io.Varuint64)
}
