// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          44 (0x2C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	AnimatePacketPayloadActionNoAction = iota
	AnimatePacketPayloadActionSwing
	AnimatePacketPayloadActionWakeUp
	AnimatePacketPayloadActionCriticalHit
	AnimatePacketPayloadActionMagicCriticalHit
)

const (
	ActorSwingSourceNone = iota
	ActorSwingSourceBuild
	ActorSwingSourceMine
	ActorSwingSourceInteract
	ActorSwingSourceAttack
	ActorSwingSourceUseItem
	ActorSwingSourceThrowItem
	ActorSwingSourceDropItem
	ActorSwingSourceEvent
)

// Animate Animate Actor
type Animate struct {
	Action uint8
	TargetActorRuntimeID uint64
	Data float32
	SwingSource protocol.Optional[uint8]
}

// ID ...
func (*Animate) ID() uint32 {
	return IDAnimate
}

func (pk *Animate) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varuint64(&pk.TargetActorRuntimeID)
	io.Float32(&pk.Data)
	protocol.OptionalFunc(io, &pk.SwingSource, io.Uint8)
}
