// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          141 (0x8D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AnvilDamage Requests an anvil to be damaged.
type AnvilDamage struct {
	DamageAmount uint8
	BlockPosition protocol.BlockPos
}

// ID ...
func (*AnvilDamage) ID() uint32 {
	return IDAnvilDamage
}

// Marshal ...
func (pk *AnvilDamage) Marshal(io protocol.IO) {
	io.Uint8(&pk.DamageAmount)
	io.BlockPos(&pk.BlockPosition)
}
