// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          141 (0x8D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AnvilDamage Requests an anvil to be damaged.
type AnvilDamage struct {
	DamageAmount uint8
	BlockPosition protocol.BlockPos
}

// ID ...
func (*AnvilDamage) ID() uint32 {
	return IDAnvilDamage
}

func (pk *AnvilDamage) Marshal(io protocol.IO) {
	io.Uint8(&pk.DamageAmount)
	io.UBlockPos(&pk.BlockPosition)
}
