// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          95 (0x5F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AutomationClientConnect Initiates websocket connection
type AutomationClientConnect struct {
	WebSocketData string
}

// ID ...
func (*AutomationClientConnect) ID() uint32 {
	return IDAutomationClientConnect
}

func (pk *AutomationClientConnect) Marshal(io protocol.IO) {
	io.String(&pk.WebSocketData)
}
