// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          95 (0x5F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AutomationClientConnect Initiates websocket connection
type AutomationClientConnect struct {
	WebSocketData string
}

// ID ...
func (*AutomationClientConnect) ID() uint32 {
	return IDAutomationClientConnect
}

// Marshal ...
func (pk *AutomationClientConnect) Marshal(io protocol.IO) {
	io.String(&pk.WebSocketData)
}
