// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          119 (0x77)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AvailableActorIdentifiers Sends the whole list of actor identifiers at game start from the server.
type AvailableActorIdentifiers struct {
	// IdentifierList CompoundTag containing a list of ActorInfo: rid (RuntimeId - Int), id (string), bid (BaseId - string), hasspawnegg (bool), summonable (bool)
	IdentifierList any
}

// ID ...
func (*AvailableActorIdentifiers) ID() uint32 {
	return IDAvailableActorIdentifiers
}

func (pk *AvailableActorIdentifiers) Marshal(io protocol.IO) {
	// TODO: IdentifierList - unresolved reference: #/definitions/3172631924
}
