// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          119 (0x77)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AvailableActorIdentifiers Sends the whole list of actor identifiers at game start from the server.
type AvailableActorIdentifiers struct {
	// IdentifierList CompoundTag containing a list of ActorInfo: rid (RuntimeId - Int), id (string), bid (BaseId - string), hasspawnegg (bool), summonable (bool)
	IdentifierList map[string]any
}

// ID ...
func (*AvailableActorIdentifiers) ID() uint32 {
	return IDAvailableActorIdentifiers
}

func (pk *AvailableActorIdentifiers) Marshal(io protocol.IO) {
	io.NBT(&pk.IdentifierList, nbt.NetworkLittleEndian)
}
