// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          309 (0x135)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AwardAchievement Contains the ID of the achievement to award
type AwardAchievement struct {
	AchievementID int32
}

// ID ...
func (*AwardAchievement) ID() uint32 {
	return IDAwardAchievement
}

func (pk *AwardAchievement) Marshal(io protocol.IO) {
	io.Int32(&pk.AchievementID)
}
