// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          309 (0x135)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AwardAchievement Contains the ID of the achievement to award
type AwardAchievement struct {
	AchievementID int32
}

// ID ...
func (*AwardAchievement) ID() uint32 {
	return IDAwardAchievement
}

func (pk *AwardAchievement) Marshal(io protocol.IO) {
	io.Int32(&pk.AchievementID)
}
