// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          122 (0x7A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BiomeStringList is a nested struct used in the packet.
type BiomeStringList struct {
	// Strings List of strings referenced wherever a string index is used under BiomeDefinitionData
	Strings []string
}

func (x *BiomeStringList) Marshal(r protocol.IO) {
	protocol.FuncSlice(r, &x.Strings, r.String)
}

// BiomeDefinitionList On world start, send clients the info for all available biomes.
type BiomeDefinitionList struct {
	MapOfBiomeNamesToData any
	StringList BiomeStringList
}

// ID ...
func (*BiomeDefinitionList) ID() uint32 {
	return IDBiomeDefinitionList
}

func (pk *BiomeDefinitionList) Marshal(io protocol.IO) {
	// TODO: MapOfBiomeNamesToData - type mapping not found for any
	protocol.Single(io, &pk.StringList)
}
