// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          26 (0x1A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BlockEvent Whenever a block event happens it is sent from the server to sync client and server, with arbitrarily encoded information in b0 and b1.
type BlockEvent struct {
	BlockPosition protocol.BlockPos
	EventType int32
	EventValue int32
}

// ID ...
func (*BlockEvent) ID() uint32 {
	return IDBlockEvent
}

// Marshal ...
func (pk *BlockEvent) Marshal(io protocol.IO) {
	io.BlockPos(&pk.BlockPosition)
	io.Varint32(&pk.EventType)
	io.Varint32(&pk.EventValue)
}
