// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          34 (0x22)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BlockPickRequest Player picks up a block in the world; client to server.
type BlockPickRequest struct {
	Position protocol.BlockPos
	WithData bool
	MaxSlots uint8
}

// ID ...
func (*BlockPickRequest) ID() uint32 {
	return IDBlockPickRequest
}

func (pk *BlockPickRequest) Marshal(io protocol.IO) {
	io.BlockPos(&pk.Position)
	io.Bool(&pk.WithData)
	io.Uint8(&pk.MaxSlots)
}
