// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          26 (0x1A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BlockEvent Whenever a block event happens it is sent from the server to sync client and server, with arbitrarily encoded information in b0 and b1.
type BlockEvent struct {
	BlockPosition protocol.BlockPos
	EventType int32
	EventValue int32
}

// ID ...
func (*BlockEvent) ID() uint32 {
	return IDBlockEvent
}

func (pk *BlockEvent) Marshal(io protocol.IO) {
	io.UBlockPos(&pk.BlockPosition)
	io.Varint32(&pk.EventType)
	io.Varint32(&pk.EventValue)
}
