// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          56 (0x38)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BlockActorData Sends the entire user data compound tag and the block position to the client.
type BlockActorData struct {
	BlockPosition protocol.BlockPos
	ActorDataTags any
}

// ID ...
func (*BlockActorData) ID() uint32 {
	return IDBlockActorData
}

func (pk *BlockActorData) Marshal(io protocol.IO) {
	io.BlockPos(&pk.BlockPosition)
	// TODO: ActorDataTags - unresolved reference: #/definitions/3172631924
}
