// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          56 (0x38)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BlockActorData Sends the entire user data compound tag and the block position to the client.
type BlockActorData struct {
	BlockPosition protocol.BlockPos
	ActorDataTags map[string]any
}

// ID ...
func (*BlockActorData) ID() uint32 {
	return IDBlockActorData
}

func (pk *BlockActorData) Marshal(io protocol.IO) {
	io.UBlockPos(&pk.BlockPosition)
	io.NBT(&pk.ActorDataTags, nbt.NetworkLittleEndian)
}
