// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          97 (0x61)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// BookEditActionReplacePage is a nested struct used in the packet.
type BookEditActionReplacePage struct {
	PageIndex int32
	PageText string
	PhotoName string
}

func (x *BookEditActionReplacePage) Marshal(r protocol.IO) {
	r.Varint32(&x.PageIndex)
	r.String(&x.PageText)
	r.String(&x.PhotoName)
}

// BookEditActionAddPage is a nested struct used in the packet.
type BookEditActionAddPage struct {
	PageIndex int32
	PageText string
	PhotoName string
}

func (x *BookEditActionAddPage) Marshal(r protocol.IO) {
	r.Varint32(&x.PageIndex)
	r.String(&x.PageText)
	r.String(&x.PhotoName)
}

// BookEditActionDeletePage is a nested struct used in the packet.
type BookEditActionDeletePage struct {
	PageIndex int32
}

func (x *BookEditActionDeletePage) Marshal(r protocol.IO) {
	r.Varint32(&x.PageIndex)
}

// BookEditActionSwapPages is a nested struct used in the packet.
type BookEditActionSwapPages struct {
	PageIndex int32
	SwapWithIndex int32
}

func (x *BookEditActionSwapPages) Marshal(r protocol.IO) {
	r.Varint32(&x.PageIndex)
	r.Varint32(&x.SwapWithIndex)
}

// BookEditActionFinalize is a nested struct used in the packet.
type BookEditActionFinalize struct {
	Title string
	Author string
	XUID string
}

func (x *BookEditActionFinalize) Marshal(r protocol.IO) {
	r.String(&x.Title)
	r.String(&x.Author)
	r.String(&x.XUID)
}

// BookEdit Sends the updated state of the Book and Quill item from client to server during use.
type BookEdit struct {
	BookSlot int32
	// Operation Payload variant holding data specific to the type of Book Edit Operation.
	Operation any
}

// ID ...
func (*BookEdit) ID() uint32 {
	return IDBookEdit
}

// Marshal ...
func (pk *BookEdit) Marshal(io protocol.IO) {
	io.Varint32(&pk.BookSlot)
	// TODO: Operation - oneOf variants generated but control field unknown
	// Variants: BookEditActionReplacePage(0), BookEditActionAddPage(1), BookEditActionDeletePage(2), BookEditActionSwapPages(3), BookEditActionFinalize(4)
}
