// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          74 (0x4A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	BossEventUpdateTypeAdd = iota
	BossEventUpdateTypePlayerAdded
	BossEventUpdateTypeRemove
	BossEventUpdateTypePlayerRemoved
	BossEventUpdateTypeUpdatePercent
	BossEventUpdateTypeUpdateName
	BossEventUpdateTypeUpdateProperties
	BossEventUpdateTypeUpdateStyle
	BossEventUpdateTypeQuery
)

const (
	BossBarOverlayPROGRESS = iota
	BossBarOverlayNotched6
	BossBarOverlayNotched10
	BossBarOverlayNotched12
	BossBarOverlayNotched20
)

const (
	BossBarColorPINK = iota
	BossBarColorBLUE
	BossBarColorRED
	BossBarColorGREEN
	BossBarColorYELLOW
	BossBarColorPURPLE
	BossBarColorRebeccaPurple
	BossBarColorWHITE
)

// BossEvent Sent when a boss gets updated
type BossEvent struct {
	// EntityUniqueID actor id for the boss
	EntityUniqueID int64
	PlayerID int64
	// EventType type of boss event
	EventType uint8
	// Name Name of the boss to add
	Name string
	// FilteredName Filtered name of the boss to add
	FilteredName string
	// HealthPercent Health value of the boss
	HealthPercent float32
	// Color color for the boss bar, listed in an enumeration
	Color uint8
	// Overlay overlay for the boss bar, listed in an enumeration
	Overlay uint8
}

// ID ...
func (*BossEvent) ID() uint32 {
	return IDBossEvent
}

func (pk *BossEvent) Marshal(io protocol.IO) {
	io.Varint64(&pk.EntityUniqueID)
	io.Varint64(&pk.PlayerID)
	io.Uint8(&pk.EventType)
	io.String(&pk.Name)
	io.String(&pk.FilteredName)
	io.Float32(&pk.HealthPercent)
	io.Uint8(&pk.Color)
	io.Uint8(&pk.Overlay)
}
