// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          159 (0x9F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	CameraShakeActionAdd = iota
	CameraShakeActionStop
)

const (
	CameraShakeTypePositional = iota
	CameraShakeTypeRotational
)

// CameraShake Used to control trigger camera shake movements on the client's player camera
type CameraShake struct {
	// Intensity Camera shake intensity
	Intensity float32
	// Seconds Camera shake duration in seconds
	Seconds float32
	// ShakeType The type of calculation used for determining camera shake
	ShakeType uint8
	// ShakeAction The action to perform to camera shake
	ShakeAction uint8
}

// ID ...
func (*CameraShake) ID() uint32 {
	return IDCameraShake
}

func (pk *CameraShake) Marshal(io protocol.IO) {
	io.Float32(&pk.Intensity)
	io.Float32(&pk.Seconds)
	io.Uint8(&pk.ShakeType)
	io.Uint8(&pk.ShakeAction)
}
