// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          320 (0x140)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	CameraAimAssistPresetsPacketOperationSet = iota
	CameraAimAssistPresetsPacketOperationAddToExisting
)

// CameraAimAssistPresetExclusionDefinition is a nested struct used in the packet.
type CameraAimAssistPresetExclusionDefinition struct {
	// Blocks Optional. List of block identifiers to exclude from aim assist targeting.
	Blocks []string
	// Entities Optional. List of entity identifiers to exclude from aim assist targeting.
	Entities []string
	// BlockTags Optional. List of block tags to exclude from aim assist targeting.
	BlockTags []string
}

func (x *CameraAimAssistPresetExclusionDefinition) Marshal(r protocol.IO) {
	protocol.FuncSlice(r, &x.Blocks, r.String)
	protocol.FuncSlice(r, &x.Entities, r.String)
	protocol.FuncSlice(r, &x.BlockTags, r.String)
}

// ItemSettingsEntry is a nested struct used in the packet.
type ItemSettingsEntry struct {
	Key string
	Value string
}

func (x *ItemSettingsEntry) Marshal(r protocol.IO) {
	r.String(&x.Key)
	r.String(&x.Value)
}

// CameraAimAssistPresetDefinition is a nested struct used in the packet.
type CameraAimAssistPresetDefinition struct {
	// Identifier Namespaced identifier for Camera Aim-Assist preset. Namespace and name must be separated by a ':'.
	Identifier string
	// ExclusionSettings Optional. List of block/entity identifiers to exclude from aim assist targeting.
	ExclusionSettings CameraAimAssistPresetExclusionDefinition
	// LiquidTargetingList Optional. List of item identifiers that will target liquid blocks with aim-assist when being held.
	LiquidTargetingList []string
	// ItemSettings Optional. Map of Item identifiers to Aim-Assist Category names found in the specified 'categories'.
	ItemSettings []ItemSettingsEntry
	// DefaultItemSettings Optional. Default Aim-Assist Category used for Items not found in 'item_settings'.
	DefaultItemSettings string
	// HandSettings Optional. Aim-assist Category used for an empty hand.
	HandSettings string
}

func (x *CameraAimAssistPresetDefinition) Marshal(r protocol.IO) {
	r.String(&x.Identifier)
	protocol.Single(r, &x.ExclusionSettings)
	protocol.FuncSlice(r, &x.LiquidTargetingList, r.String)
	protocol.Slice(r, &x.ItemSettings)
	r.String(&x.DefaultItemSettings)
	r.String(&x.HandSettings)
}

// EntitiesEntry is a nested struct used in the packet.
type EntitiesEntry struct {
	Key string
	Value int32
}

func (x *EntitiesEntry) Marshal(r protocol.IO) {
	r.String(&x.Key)
	r.Int32(&x.Value)
}

// BlocksEntry is a nested struct used in the packet.
type BlocksEntry struct {
	Key string
	Value int32
}

func (x *BlocksEntry) Marshal(r protocol.IO) {
	r.String(&x.Key)
	r.Int32(&x.Value)
}

// CameraAimAssistCategoryPriorities is a nested struct used in the packet.
type CameraAimAssistCategoryPriorities struct {
	// Entities Optional. Map of Entity identifiers to Aim-Assist targeting priority. Larger numbers have greater priority.
	Entities []EntitiesEntry
	// Blocks Optional. Map of Block identifiers to Aim-Assist targeting priority. Larger numbers have greater priority.
	Blocks []BlocksEntry
	// BlockTags Optional. Map of Block tags to Aim-Assist targeting priority. Larger numbers have greater priority.
	BlockTags any
	// EntityDefault Optional. Default Aim-Assist targeting priority used for Entities not found in 'entities'.
	EntityDefault int32
	// BlockDefault Optional. Default Aim-Assist targeting priority used for Blocks not found in 'blocks'.
	BlockDefault int32
}

func (x *CameraAimAssistCategoryPriorities) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.Entities)
	protocol.Slice(r, &x.Blocks)
	// TODO: BlockTags - unknown additionalProperties structure
	r.Int32(&x.EntityDefault)
	r.Int32(&x.BlockDefault)
}

// CameraAimAssistCategoryDefinition is a nested struct used in the packet.
type CameraAimAssistCategoryDefinition struct {
	// Name Name of the Aim-Assist Category used during lookup.
	Name string
	// Priorities The set of priorities used when determining aim-assist selection.
	Priorities CameraAimAssistCategoryPriorities
}

func (x *CameraAimAssistCategoryDefinition) Marshal(r protocol.IO) {
	r.String(&x.Name)
	protocol.Single(r, &x.Priorities)
}

// CameraAimAssistPresets Camera aim-assist registry presets/categories data sent from the server to clients.
type CameraAimAssistPresets struct {
	CameraAimAssistPresets []CameraAimAssistCategoryDefinition
	CameraAimAssistCategories []CameraAimAssistPresetDefinition
	Operation uint8
}

// ID ...
func (*CameraAimAssistPresets) ID() uint32 {
	return IDCameraAimAssistPresets
}

func (pk *CameraAimAssistPresets) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.CameraAimAssistPresets)
	protocol.Slice(io, &pk.CameraAimAssistCategories)
	io.Uint8(&pk.Operation)
}
