// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          316 (0x13C)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	CameraAimAssistPacketPayloadTargetModeAngle = iota
	CameraAimAssistPacketPayloadTargetModeDistance
)

const (
	CameraAimAssistPacketPayloadActionSet = iota
	CameraAimAssistPacketPayloadActionClear
)

// CameraAimAssist CameraAimAssist
type CameraAimAssist struct {
	PresetID string
	ViewAngle mgl32.Vec2
	Distance float32
	TargetMode uint8
	Action uint8
	ShowDebugRender bool
}

// ID ...
func (*CameraAimAssist) ID() uint32 {
	return IDCameraAimAssist
}

func (pk *CameraAimAssist) Marshal(io protocol.IO) {
	io.String(&pk.PresetID)
	io.Vec2(&pk.ViewAngle)
	io.Float32(&pk.Distance)
	io.Uint8(&pk.TargetMode)
	io.Uint8(&pk.Action)
	io.Bool(&pk.ShowDebugRender)
}
