// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          339 (0x153)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AimAssistActorPriorityData is a nested struct used in the packet.
type AimAssistActorPriorityData struct {
	PresetIndex int32
	CategoryIndex int32
	ActorIndex int32
	PriorityValue int32
}

func (x *AimAssistActorPriorityData) Marshal(r protocol.IO) {
	r.Int32(&x.PresetIndex)
	r.Int32(&x.CategoryIndex)
	r.Int32(&x.ActorIndex)
	r.Int32(&x.PriorityValue)
}

// CameraAimAssistActorPriority Camera aim-assist actor priority data sent from the server to clients.
type CameraAimAssistActorPriority struct {
	CameraAimAssistActorPriorityList []AimAssistActorPriorityData
}

// ID ...
func (*CameraAimAssistActorPriority) ID() uint32 {
	return IDCameraAimAssistActorPriority
}

func (pk *CameraAimAssistActorPriority) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.CameraAimAssistActorPriorityList)
}
