// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          198 (0xC6)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SharedTypesComprehensiveCameraAimAssistCommandDefinition is a nested struct used in the packet.
type SharedTypesComprehensiveCameraAimAssistCommandDefinition struct {
	PresetID string
	TargetMode uint8
	ViewAngle mgl32.Vec2
	Distance float32
}

func (x *SharedTypesComprehensiveCameraAimAssistCommandDefinition) Marshal(r protocol.IO) {
	r.String(&x.PresetID)
	r.Uint8(&x.TargetMode)
	r.Vec2(&x.ViewAngle)
	r.Float32(&x.Distance)
}

// CameraPresetsEntry is a nested struct used in the packet.
type CameraPresetsEntry struct {
	Name string
	InheritFrom string
	PosX float32
	PosY float32
	PosZ float32
	RotX float32
	RotY float32
	RotationSpeed float32
	SnapToTarget bool
	HorizontalRotationLimit mgl32.Vec2
	VerticalRotationLimit mgl32.Vec2
	ContinueTargeting bool
	BlockListeningRadius float32
	ViewOffset mgl32.Vec2
	// EntityOffset Changing the camera's pivot point from the center of the entity
	EntityOffset mgl32.Vec3
	Radius float32
	YawLimitMin float32
	YawLimitMax float32
	Listener uint8
	PlayerEffects bool
	AimAssist SharedTypesComprehensiveCameraAimAssistCommandDefinition
	ControlScheme uint8
}

func (x *CameraPresetsEntry) Marshal(r protocol.IO) {
	r.String(&x.Name)
	r.String(&x.InheritFrom)
	r.Float32(&x.PosX)
	r.Float32(&x.PosY)
	r.Float32(&x.PosZ)
	r.Float32(&x.RotX)
	r.Float32(&x.RotY)
	r.Float32(&x.RotationSpeed)
	r.Bool(&x.SnapToTarget)
	r.Vec2(&x.HorizontalRotationLimit)
	r.Vec2(&x.VerticalRotationLimit)
	r.Bool(&x.ContinueTargeting)
	r.Float32(&x.BlockListeningRadius)
	r.Vec2(&x.ViewOffset)
	r.Vec3(&x.EntityOffset)
	r.Float32(&x.Radius)
	r.Float32(&x.YawLimitMin)
	r.Float32(&x.YawLimitMax)
	r.Uint8(&x.Listener)
	r.Bool(&x.PlayerEffects)
	protocol.Single(r, &x.AimAssist)
	r.Uint8(&x.ControlScheme)
}

// CameraPresets Used to sync CameraPresets data from server to clients.
type CameraPresets struct {
	CameraPresets CameraPresetsEntry
}

// ID ...
func (*CameraPresets) ID() uint32 {
	return IDCameraPresets
}

func (pk *CameraPresets) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.CameraPresets)
}
