// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          300 (0x12C)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CameraInstructionFovInstruction is a nested struct used in the packet.
type CameraInstructionFovInstruction struct {
	FieldOfView float32
	FOVEaseTime float32
	FOVEaseType int32
	FieldOfViewClear bool
}

func (x *CameraInstructionFovInstruction) Marshal(r protocol.IO) {
	r.Float32(&x.FieldOfView)
	r.Float32(&x.FOVEaseTime)
	r.Int32(&x.FOVEaseType)
	r.Bool(&x.FieldOfViewClear)
}

// CameraInstructionSetInstructionEaseOption is a nested struct used in the packet.
type CameraInstructionSetInstructionEaseOption struct {
	Type uint8
	Time float32
}

func (x *CameraInstructionSetInstructionEaseOption) Marshal(r protocol.IO) {
	r.Uint8(&x.Type)
	r.Float32(&x.Time)
}

// CameraInstructionSetInstructionEntityOffsetOption is a nested struct used in the packet.
type CameraInstructionSetInstructionEntityOffsetOption struct {
	EntityOffsetX float32
	EntityOffsetY float32
	EntityOffsetZ float32
}

func (x *CameraInstructionSetInstructionEntityOffsetOption) Marshal(r protocol.IO) {
	r.Float32(&x.EntityOffsetX)
	r.Float32(&x.EntityOffsetY)
	r.Float32(&x.EntityOffsetZ)
}

// CameraInstructionSetInstructionViewOffsetOption is a nested struct used in the packet.
type CameraInstructionSetInstructionViewOffsetOption struct {
	X float32
	Y float32
}

func (x *CameraInstructionSetInstructionViewOffsetOption) Marshal(r protocol.IO) {
	r.Float32(&x.X)
	r.Float32(&x.Y)
}

// CameraInstructionSetInstructionRotOption is a nested struct used in the packet.
type CameraInstructionSetInstructionRotOption struct {
	X float32
	Y float32
}

func (x *CameraInstructionSetInstructionRotOption) Marshal(r protocol.IO) {
	r.Float32(&x.X)
	r.Float32(&x.Y)
}

// CameraInstructionSetInstruction is a nested struct used in the packet.
type CameraInstructionSetInstruction struct {
	Preset uint32
	Ease CameraInstructionSetInstructionEaseOption
	Pos mgl32.Vec3
	Rot CameraInstructionSetInstructionRotOption
	Facing mgl32.Vec3
	ViewOffset CameraInstructionSetInstructionViewOffsetOption
	EntityOffset CameraInstructionSetInstructionEntityOffsetOption
	Default bool
	RemoveIgnoreStartingValuesComponent bool
}

func (x *CameraInstructionSetInstruction) Marshal(r protocol.IO) {
	r.Uint32(&x.Preset)
	protocol.Single(r, &x.Ease)
	r.Vec3(&x.Pos)
	protocol.Single(r, &x.Rot)
	r.Vec3(&x.Facing)
	protocol.Single(r, &x.ViewOffset)
	protocol.Single(r, &x.EntityOffset)
	r.Bool(&x.Default)
	r.Bool(&x.RemoveIgnoreStartingValuesComponent)
}

// CameraInstructionSplineInstructionSplineRotationOption is a nested struct used in the packet.
type CameraInstructionSplineInstructionSplineRotationOption struct {
	KeyFrameValues mgl32.Vec3
	KeyFrameTimes float32
}

func (x *CameraInstructionSplineInstructionSplineRotationOption) Marshal(r protocol.IO) {
	r.Vec3(&x.KeyFrameValues)
	r.Float32(&x.KeyFrameTimes)
}

// CameraInstructionSplineInstruction is a nested struct used in the packet.
type CameraInstructionSplineInstruction struct {
	TotalTime float32
	Type uint8
	Curve []mgl32.Vec3
	ProgressKeyFrames []mgl32.Vec2
	RotationOption []CameraInstructionSplineInstructionSplineRotationOption
}

func (x *CameraInstructionSplineInstruction) Marshal(r protocol.IO) {
	r.Float32(&x.TotalTime)
	r.Uint8(&x.Type)
	protocol.FuncSlice(r, &x.Curve, r.Vec3)
	protocol.FuncSlice(r, &x.ProgressKeyFrames, r.Vec2)
	protocol.Slice(r, &x.RotationOption)
}

// CameraInstructionTargetInstruction is a nested struct used in the packet.
type CameraInstructionTargetInstruction struct {
	TargetCenterOffset mgl32.Vec3
	TargetActorID int64
}

func (x *CameraInstructionTargetInstruction) Marshal(r protocol.IO) {
	r.Vec3(&x.TargetCenterOffset)
	r.Int64(&x.TargetActorID)
}

// CameraInstructionFadeInstructionColorOption is a nested struct used in the packet.
type CameraInstructionFadeInstructionColorOption struct {
	Red float32
	Green float32
	Blue float32
}

func (x *CameraInstructionFadeInstructionColorOption) Marshal(r protocol.IO) {
	r.Float32(&x.Red)
	r.Float32(&x.Green)
	r.Float32(&x.Blue)
}

// CameraInstructionFadeInstructionTimeOption is a nested struct used in the packet.
type CameraInstructionFadeInstructionTimeOption struct {
	FadeInTime float32
	HoldTime float32
	FadeOutTime float32
}

func (x *CameraInstructionFadeInstructionTimeOption) Marshal(r protocol.IO) {
	r.Float32(&x.FadeInTime)
	r.Float32(&x.HoldTime)
	r.Float32(&x.FadeOutTime)
}

// CameraInstructionFadeInstruction is a nested struct used in the packet.
type CameraInstructionFadeInstruction struct {
	Time CameraInstructionFadeInstructionTimeOption
	Color CameraInstructionFadeInstructionColorOption
}

func (x *CameraInstructionFadeInstruction) Marshal(r protocol.IO) {
	protocol.Single(r, &x.Time)
	protocol.Single(r, &x.Color)
}

// CameraInstructionEntry is a nested struct used in the packet.
type CameraInstructionEntry struct {
	Set CameraInstructionSetInstruction
	Clear bool
	Fade CameraInstructionFadeInstruction
	Target CameraInstructionTargetInstruction
	RemoveTarget bool
	FieldOfView CameraInstructionFovInstruction
	Spline CameraInstructionSplineInstruction
	AttachToEntity int64
	DetachFromEntity bool
}

func (x *CameraInstructionEntry) Marshal(r protocol.IO) {
	protocol.Single(r, &x.Set)
	r.Bool(&x.Clear)
	protocol.Single(r, &x.Fade)
	protocol.Single(r, &x.Target)
	r.Bool(&x.RemoveTarget)
	protocol.Single(r, &x.FieldOfView)
	protocol.Single(r, &x.Spline)
	r.Int64(&x.AttachToEntity)
	r.Bool(&x.DetachFromEntity)
}

// CameraInstruction Used to send a CameraInstruction from the server to the specified clients.
type CameraInstruction struct {
	CameraInstruction CameraInstructionEntry
}

// ID ...
func (*CameraInstruction) ID() uint32 {
	return IDCameraInstruction
}

func (pk *CameraInstruction) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.CameraInstruction)
}
