// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          73 (0x49)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Camera Used only in EDU through the tripod camera item or the TakePictureCommand. Sends the camera actor id and the target player id from the server.
type Camera struct {
	CameraID int64
	TargetPlayerID int64
}

// ID ...
func (*Camera) ID() uint32 {
	return IDCamera
}

func (pk *Camera) Marshal(io protocol.IO) {
	io.Varint64(&pk.CameraID)
	io.Varint64(&pk.TargetPlayerID)
}
