// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          73 (0x49)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Camera Used only in EDU through the tripod camera item or the TakePictureCommand. Sends the camera actor id and the target player id from the server.
type Camera struct {
	CameraID int64
	TargetPlayerID int64
}

// ID ...
func (*Camera) ID() uint32 {
	return IDCamera
}

// Marshal ...
func (pk *Camera) Marshal(io protocol.IO) {
	io.Varint64(&pk.CameraID)
	io.Varint64(&pk.TargetPlayerID)
}
