// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          338 (0x152)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CameraSplineProgressKeyFrame is a nested struct used in the packet.
type CameraSplineProgressKeyFrame struct {
	// Progress Normalized progress of this frame along the spline, from 0.0 (start) to 1.0 (end).
	Progress float32
	// Time Time (in seconds) at which this progress should be applied.
	Time float32
	// Easing Optional easing function used to interpolate towards this progress key frame. Defaults to "linear" if omitted.
	Easing int32
}

func (x *CameraSplineProgressKeyFrame) Marshal(r protocol.IO) {
	r.Float32(&x.Progress)
	r.Float32(&x.Time)
	r.Int32(&x.Easing)
}

// CameraSplineRotationKeyFrame is a nested struct used in the packet.
type CameraSplineRotationKeyFrame struct {
	// Rotation Rotation [x, y, z] value.
	Rotation mgl32.Vec3
	// Time Time (in seconds) at which this rotation should be applied.
	Time float32
	// Easing Optional easing function used to interpolate towards this rotation key frame. Defaults to "linear" if omitted.
	Easing int32
}

func (x *CameraSplineRotationKeyFrame) Marshal(r protocol.IO) {
	r.Vec3(&x.Rotation)
	r.Float32(&x.Time)
	r.Int32(&x.Easing)
}

// CameraSplineDefinition is a nested struct used in the packet.
type CameraSplineDefinition struct {
	// Name The identifier for this spline, in "namespace:name" format.
	Name string
	// TotalTime The total time, in seconds, to play back the spline.
	TotalTime float32
	// SplineType The spline interpolation type: "catmullrom" or "linear". Defaults to "catmullrom".
	SplineType string
	// ControlPoints Array of control point positions, each as [x, y, z] in world space.
	ControlPoints []mgl32.Vec3
	// ProgressKeyFrames Key frames where each entry defines a progress alpha [0–1] and a time (in seconds) when the spline should reach that progress.
	ProgressKeyFrames []CameraSplineProgressKeyFrame
	// RotationKeyFrames Array of rotation key frames, each with a rotation value and the time (in seconds) when it should be applied.
	RotationKeyFrames []CameraSplineRotationKeyFrame
}

func (x *CameraSplineDefinition) Marshal(r protocol.IO) {
	r.String(&x.Name)
	r.Float32(&x.TotalTime)
	r.String(&x.SplineType)
	protocol.FuncSlice(r, &x.ControlPoints, r.Vec3)
	protocol.Slice(r, &x.ProgressKeyFrames)
	protocol.Slice(r, &x.RotationKeyFrames)
}

// CameraSpline Camera custom spline data sent from server to client.
type CameraSpline struct {
	CameraDataSplines []CameraSplineDefinition
}

// ID ...
func (*CameraSpline) ID() uint32 {
	return IDCameraSpline
}

func (pk *CameraSpline) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.CameraDataSplines)
}
