// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          61 (0x3D)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ChangeDimension The server sends this packet from the level to kick off dimension changing process.
type ChangeDimension struct {
	// DimensionID Currently supported: (0 -> Overworld, 1 -> Nether, 2 -> The End, 3 -> Undefined)
	DimensionID int32
	Position mgl32.Vec3
	Respawn bool
	// LoadingScreenID Leave empty if there is no loading screen expected on the client. This id needs to be unique and not conflict with any other active loading screens. This is implemented with an unsigned integer incrementing forever, and that is expected to not have collisions when it wraps around back to 0 if that could be a possibility.
	LoadingScreenID uint32
}

// ID ...
func (*ChangeDimension) ID() uint32 {
	return IDChangeDimension
}

func (pk *ChangeDimension) Marshal(io protocol.IO) {
	io.Varint32(&pk.DimensionID)
	io.Vec3(&pk.Position)
	io.Bool(&pk.Respawn)
	io.Uint32(&pk.LoadingScreenID)
}
