// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          182 (0xB6)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ChangeMobProperty packet containing data for changing mob property
type ChangeMobProperty struct {
	ActorID int64
	PropertyName string
	BoolComponentValue bool
	StringComponentValue string
	IntComponentValue int32
	FloatComponentValue float32
}

// ID ...
func (*ChangeMobProperty) ID() uint32 {
	return IDChangeMobProperty
}

func (pk *ChangeMobProperty) Marshal(io protocol.IO) {
	io.Varint64(&pk.ActorID)
	io.String(&pk.PropertyName)
	io.Bool(&pk.BoolComponentValue)
	io.String(&pk.StringComponentValue)
	io.Varint32(&pk.IntComponentValue)
	io.Float32(&pk.FloatComponentValue)
}
