// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          70 (0x46)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ChunkRadiusUpdated Sent when the world is loading. We don't know why it is sent four times. Defines the tick distance.
type ChunkRadiusUpdated struct {
	ChunkRadius int32
}

// ID ...
func (*ChunkRadiusUpdated) ID() uint32 {
	return IDChunkRadiusUpdated
}

func (pk *ChunkRadiusUpdated) Marshal(io protocol.IO) {
	io.Varint32(&pk.ChunkRadius)
}
