// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          335 (0x14F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientboundDataDrivenUIReload Allows the server to tell the client to reload the Data Driven UI.
type ClientboundDataDrivenUIReload struct {
}

// ID ...
func (*ClientboundDataDrivenUIReload) ID() uint32 {
	return IDClientboundDataDrivenUIReload
}

func (pk *ClientboundDataDrivenUIReload) Marshal(io protocol.IO) {
}
