// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          333 (0x14D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientboundDataDrivenUIShowScreen Allows the server to tell the client to show a Data Driven UI screen.
type ClientboundDataDrivenUIShowScreen struct {
	// ScreenID The ID of the screen to show
	ScreenID string
	// FormID The unique id of this instance of the form for tracking in scripting
	FormID uint32
	// DataInstanceID The optional id of the data associated with this screen
	DataInstanceID protocol.Optional[uint32]
}

// ID ...
func (*ClientboundDataDrivenUIShowScreen) ID() uint32 {
	return IDClientboundDataDrivenUIShowScreen
}

func (pk *ClientboundDataDrivenUIShowScreen) Marshal(io protocol.IO) {
	io.String(&pk.ScreenID)
	io.Uint32(&pk.FormID)
	protocol.OptionalFunc(io, &pk.DataInstanceID, io.Uint32)
}
