// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          4 (0x04)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientToServerHandshake Sets up encryption and authenticates in educational version once at level startup from client.
type ClientToServerHandshake struct {
}

// ID ...
func (*ClientToServerHandshake) ID() uint32 {
	return IDClientToServerHandshake
}

func (pk *ClientToServerHandshake) Marshal(io protocol.IO) {
}
