// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          345 (0x159)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AttributeLayerSettings is a nested struct used in the packet.
type AttributeLayerSettings struct {
	Priority int32
	Weight float32
	Enabled bool
	TransitionsPaused bool
}

func (x *AttributeLayerSettings) Marshal(r protocol.IO) {
	r.Int32(&x.Priority)
	r.Float32(&x.Weight)
	r.Bool(&x.Enabled)
	r.Bool(&x.TransitionsPaused)
}

// EnvironmentAttributeData is a nested struct used in the packet.
type EnvironmentAttributeData struct {
	AttributeName string
	FromAttribute any
	Attribute any
	ToAttribute any
	CurrentTransitionTicks uint32
	TotalTransitionTicks uint32
	Easing int32
	LocalTransitionTicks uint32
	NoiseTransition bool
}

func (x *EnvironmentAttributeData) Marshal(r protocol.IO) {
	r.String(&x.AttributeName)
	// TODO: FromAttribute - oneOf with complex variants
	// TODO: Attribute - oneOf with complex variants
	// TODO: ToAttribute - oneOf with complex variants
	r.Uint32(&x.CurrentTransitionTicks)
	r.Uint32(&x.TotalTransitionTicks)
	r.Int32(&x.Easing)
	r.Uint32(&x.LocalTransitionTicks)
	r.Bool(&x.NoiseTransition)
}

// AttributeLayerData is a nested struct used in the packet.
type AttributeLayerData struct {
	Name string
	NoiseName string
	Dimension int32
	Settings AttributeLayerSettings
	Attributes []EnvironmentAttributeData
}

func (x *AttributeLayerData) Marshal(r protocol.IO) {
	r.String(&x.Name)
	r.String(&x.NoiseName)
	r.Varint32(&x.Dimension)
	protocol.Single(r, &x.Settings)
	protocol.Slice(r, &x.Attributes)
}

// UpdateAttributeLayersData is a nested struct used in the packet.
type UpdateAttributeLayersData struct {
	AttributeLayers []AttributeLayerData
}

func (x *UpdateAttributeLayersData) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.AttributeLayers)
}

// UpdateAttributeLayerSettingsData is a nested struct used in the packet.
type UpdateAttributeLayerSettingsData struct {
	AttributeLayerName string
	AttributeLayerDimension int32
	AttributesLayerSettings AttributeLayerSettings
}

func (x *UpdateAttributeLayerSettingsData) Marshal(r protocol.IO) {
	r.String(&x.AttributeLayerName)
	r.Varint32(&x.AttributeLayerDimension)
	protocol.Single(r, &x.AttributesLayerSettings)
}

// UpdateEnvironmentAttributesData is a nested struct used in the packet.
type UpdateEnvironmentAttributesData struct {
	AttributeLayerName string
	AttributeLayerDimension int32
	Attributes []EnvironmentAttributeData
}

func (x *UpdateEnvironmentAttributesData) Marshal(r protocol.IO) {
	r.String(&x.AttributeLayerName)
	r.Varint32(&x.AttributeLayerDimension)
	protocol.Slice(r, &x.Attributes)
}

// RemoveEnvironmentAttributesData is a nested struct used in the packet.
type RemoveEnvironmentAttributesData struct {
	AttributeLayerName string
	AttributeLayerDimension int32
	Attributes []string
}

func (x *RemoveEnvironmentAttributesData) Marshal(r protocol.IO) {
	r.String(&x.AttributeLayerName)
	r.Varint32(&x.AttributeLayerDimension)
	protocol.FuncSlice(r, &x.Attributes, r.String)
}

// ClientboundAttributeLayerSync Syncs Attribute Layers to the Client (Currently disabled)
type ClientboundAttributeLayerSync struct {
	Data any
}

// ID ...
func (*ClientboundAttributeLayerSync) ID() uint32 {
	return IDClientboundAttributeLayerSync
}

func (pk *ClientboundAttributeLayerSync) Marshal(io protocol.IO) {
	// TODO: Data - oneOf variants generated but control field unknown
	// Variants: UpdateAttributeLayersData(0), UpdateAttributeLayerSettingsData(1), UpdateEnvironmentAttributesData(2), RemoveEnvironmentAttributesData(3)
}
