// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          135 (0x87)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientCacheBlobStatus Client Cache Blob Status Packet
type ClientCacheBlobStatus struct {
	MissingIds []uint64
	FoundIds []uint64
}

// ID ...
func (*ClientCacheBlobStatus) ID() uint32 {
	return IDClientCacheBlobStatus
}

func (pk *ClientCacheBlobStatus) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.MissingIds, io.Uint64)
	protocol.FuncSlice(io, &pk.FoundIds, io.Uint64)
}
