// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          321 (0x141)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ClientCameraAimAssistPacketActionSetFromCameraPreset = iota
	ClientCameraAimAssistPacketActionClear
)

// ClientCameraAimAssist Client-side activation of aim-assist
type ClientCameraAimAssist struct {
	CameraPresetID string
	Action uint8
	AllowAimAssist protocol.Optional[bool]
}

// ID ...
func (*ClientCameraAimAssist) ID() uint32 {
	return IDClientCameraAimAssist
}

// Marshal ...
func (pk *ClientCameraAimAssist) Marshal(io protocol.IO) {
	io.String(&pk.CameraPresetID)
	io.Uint8(&pk.Action)
	protocol.OptionalFunc(io, &pk.AllowAimAssist, io.Bool)
}
