// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          129 (0x81)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientCacheStatus It is sent by the Client once, at login, to communicate if it supports the cache or not.
type ClientCacheStatus struct {
	IsCacheSupported bool
}

// ID ...
func (*ClientCacheStatus) ID() uint32 {
	return IDClientCacheStatus
}

func (pk *ClientCacheStatus) Marshal(io protocol.IO) {
	io.Bool(&pk.IsCacheSupported)
}
