// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          334 (0x14E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientboundDataDrivenUICloseScreen Allows the server to tell the client to close Data Driven UI screens.
type ClientboundDataDrivenUICloseScreen struct {
	// FormID The unique id of th form to close. If not supplied, this will close all forms
	FormID protocol.Optional[uint32]
}

// ID ...
func (*ClientboundDataDrivenUICloseScreen) ID() uint32 {
	return IDClientboundDataDrivenUICloseScreen
}

// Marshal ...
func (pk *ClientboundDataDrivenUICloseScreen) Marshal(io protocol.IO) {
	protocol.OptionalFunc(io, &pk.FormID, io.Uint32)
}
