// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          330 (0x14A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientboundDataStore Sends a list of data store properties from the server to the client.
type ClientboundDataStore struct {
	// Updates List of changes, updates, or removals that have occurred to the data store
	Updates []any
}

// ID ...
func (*ClientboundDataStore) ID() uint32 {
	return IDClientboundDataStore
}

func (pk *ClientboundDataStore) Marshal(io protocol.IO) {
	// TODO: Updates - array with unknown item type
}
