// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          336 (0x150)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ClientboundTextureShiftPacketPayloadActionInvalid = iota
	ClientboundTextureShiftPacketPayloadActionInitialize
	ClientboundTextureShiftPacketPayloadActionStart
	ClientboundTextureShiftPacketPayloadActionSetEnabled
	ClientboundTextureShiftPacketPayloadActionSync
)

// ClientboundTextureShift Sends a set of update properties for the texture shift system from the server to the client.
type ClientboundTextureShift struct {
	ActionID uint8
	CollectionName string
	FromStep string
	ToStep string
	AllSteps []string
	CurrentLengthInTicks uint64
	TotalLengthInTicks uint64
	Enabled bool
}

// ID ...
func (*ClientboundTextureShift) ID() uint32 {
	return IDClientboundTextureShift
}

// Marshal ...
func (pk *ClientboundTextureShift) Marshal(io protocol.IO) {
	io.Uint8(&pk.ActionID)
	io.String(&pk.CollectionName)
	io.String(&pk.FromStep)
	io.String(&pk.ToStep)
	protocol.FuncSlice(io, &pk.AllSteps, io.String)
	io.Varuint64(&pk.CurrentLengthInTicks)
	io.Varuint64(&pk.TotalLengthInTicks)
	io.Bool(&pk.Enabled)
}
