// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          327 (0x147)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ControlSchemeLockedPlayerRelativeStrafe = iota
	ControlSchemeCameraRelative
	ControlSchemeCameraRelativeStrafe
	ControlSchemePlayerRelative
	ControlSchemePlayerRelativeStrafe
)

// ClientboundControlSchemeSet Set the control scheme that the player should use
type ClientboundControlSchemeSet struct {
	ControlScheme uint8
}

// ID ...
func (*ClientboundControlSchemeSet) ID() uint32 {
	return IDClientboundControlSchemeSet
}

func (pk *ClientboundControlSchemeSet) Marshal(io protocol.IO) {
	io.Uint8(&pk.ControlScheme)
}
