// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          136 (0x88)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MissingBlobData is a nested struct used in the packet.
type MissingBlobData struct {
	BlobID uint64
	// BlobData Subchunk data (see https://gist.github.com/Tomcc/a96af509e275b1af483b25c543cfbf37) plus biome data
	BlobData string
}

func (x *MissingBlobData) Marshal(r protocol.IO) {
	r.Uint64(&x.BlobID)
	r.String(&x.BlobData)
}

// ClientCacheMissResponse Only active in a real client-server scenario. This packet is just a list of <blobId, blob> pairs sent from server to client.
type ClientCacheMissResponse struct {
	// MissingBlobs List of <blobId, blob> pairs
	MissingBlobs []MissingBlobData
}

// ID ...
func (*ClientCacheMissResponse) ID() uint32 {
	return IDClientCacheMissResponse
}

// Marshal ...
func (pk *ClientCacheMissResponse) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.MissingBlobs)
}
