// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          310 (0x136)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientboundCloseForm Sent from the server to client to force close all server forms on the stack and return to the HUD screen.
type ClientboundCloseForm struct {
}

// ID ...
func (*ClientboundCloseForm) ID() uint32 {
	return IDClientboundCloseForm
}

// Marshal ...
func (pk *ClientboundCloseForm) Marshal(io protocol.IO) {
}
