// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          4 (0x04)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientToServerHandshake Sets up encryption and authenticates in educational version once at level startup from client.
type ClientToServerHandshake struct {
}

// ID ...
func (*ClientToServerHandshake) ID() uint32 {
	return IDClientToServerHandshake
}

// Marshal ...
func (pk *ClientToServerHandshake) Marshal(io protocol.IO) {
}
