// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          164 (0xA4)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PayloadTypeInvalid = iota
	PayloadTypeClearDebugMarkers
	PayloadTypeAddDebugMarkerCube
)

// DebugMarkerData is a nested struct used in the packet.
type DebugMarkerData struct {
	// Text String for what text to show at the location
	Text string
	// Position Position for where the debug cube should show up
	Position mgl32.Vec3
	// Color Color of the debug cube to show
	Color int32
	// Duration Duration (milliseconds) of the debug cube to show
	Duration uint64
}

func (x *DebugMarkerData) Marshal(r protocol.IO) {
	r.String(&x.Text)
	r.Vec3(&x.Position)
	r.Int32(&x.Color)
	r.Uint64(&x.Duration)
}

// ClientboundDebugRenderer Used to add/remove debug rendering objects.
type ClientboundDebugRenderer struct {
	// Type The type of action (Invalid=0, ClearDebugMarkers=1, AddDebugMarkerCube=2).
	Type uint8
	// DebugMarkerData If the action type is AddDebugMarkerCube, the marker data for the cube.
	DebugMarkerData protocol.Optional[DebugMarkerData]
}

// ID ...
func (*ClientboundDebugRenderer) ID() uint32 {
	return IDClientboundDebugRenderer
}

// Marshal ...
func (pk *ClientboundDebugRenderer) Marshal(io protocol.IO) {
	io.Uint8(&pk.Type)
	protocol.OptionalMarshaler(io, &pk.DebugMarkerData)
}
