// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          150 (0x96)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CodeBuilder Code Builder Packet
type CodeBuilder struct {
	URL string
	ShouldOpenCodeBuilder bool
}

// ID ...
func (*CodeBuilder) ID() uint32 {
	return IDCodeBuilder
}

// Marshal ...
func (pk *CodeBuilder) Marshal(io protocol.IO) {
	io.String(&pk.URL)
	io.Bool(&pk.ShouldOpenCodeBuilder)
}
