// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          150 (0x96)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CodeBuilder Code Builder Packet
type CodeBuilder struct {
	URL string
	ShouldOpenCodeBuilder bool
}

// ID ...
func (*CodeBuilder) ID() uint32 {
	return IDCodeBuilder
}

func (pk *CodeBuilder) Marshal(io protocol.IO) {
	io.String(&pk.URL)
	io.Bool(&pk.ShouldOpenCodeBuilder)
}
