// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          178 (0xB2)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	CodeBuilderStorageQueryOptionsCategoryNone = iota
	CodeBuilderStorageQueryOptionsCategoryCodeStatus
	CodeBuilderStorageQueryOptionsCategoryInstantiation
)

const (
	CodeBuilderExecutionStateCodeStatusNone = iota
	CodeBuilderExecutionStateCodeStatusNotStarted
	CodeBuilderExecutionStateCodeStatusInProgress
	CodeBuilderExecutionStateCodeStatusPaused
	CodeBuilderExecutionStateCodeStatusError
	CodeBuilderExecutionStateCodeStatusSucceeded
)

const (
	CodeBuilderStorageQueryOptionsOperationNone = iota
	CodeBuilderStorageQueryOptionsOperationGet
	CodeBuilderStorageQueryOptionsOperationSet
	CodeBuilderStorageQueryOptionsOperationReset
)

// CodeBuilderSource This is EDU exclusive, used in getInterface() of WebviewSystem
type CodeBuilderSource struct {
	Operation uint8
	Category uint8
	CodeStatus uint8
}

// ID ...
func (*CodeBuilderSource) ID() uint32 {
	return IDCodeBuilderSource
}

func (pk *CodeBuilderSource) Marshal(io protocol.IO) {
	io.Uint8(&pk.Operation)
	io.Uint8(&pk.Category)
	io.Uint8(&pk.CodeStatus)
}
