// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          77 (0x4D)

package packet

import (
	"github.com/google/uuid"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	CurrentCmdVersionInvalid = iota
	CurrentCmdVersionInitial
	CurrentCmdVersionTpRotationClamping
	CurrentCmdVersionNewBedrockCmdSystem
	CurrentCmdVersionExecuteUsesVec3
	CurrentCmdVersionCloneFixes
	CurrentCmdVersionUpdateAquatic
	CurrentCmdVersionEntitySelectorUsesVec3
	CurrentCmdVersionContainersDontDropItemsAnymore
	CurrentCmdVersionFiltersObeyDimensions
	CurrentCmdVersionExecuteAndBlockCommandAndSelfSelectorFixes
	CurrentCmdVersionInstantEffectsUseTicks
	CurrentCmdVersionDontRegisterBrokenFunctionCommands
	CurrentCmdVersionClearSpawnPointCommand
	CurrentCmdVersionCloneAndTeleportRotationFixes
	CurrentCmdVersionTeleportDimensionFixes
	CurrentCmdVersionCloneUpdateBlockAndTimeFixes
	CurrentCmdVersionCloneIntersectFix
	CurrentCmdVersionFunctionExecuteOrderAndChestSlotFix
	CurrentCmdVersionNonTickingAreasNoLongerConsideredLoaded
	CurrentCmdVersionSpreadplayersHazardAndResolvePlayerByNameFix
	CurrentCmdVersionNewExecuteCommandSyntaxExperimentAndChestLootTableFixAndTeleportFacingVerticalUnclampedAndLocateBiomeAndFeatureMerged
	CurrentCmdVersionWaterloggingAddedToStructureCommand
	CurrentCmdVersionSelectorDistanceFilteredAndRelativeRotationFix
	CurrentCmdVersionNewSummonCommandAddedRotationOptionsAndBubbleColumnCloneFixAndExecuteInDimensionTeleportFixAndNewExecuteRotationFix
	CurrentCmdVersionNewExecuteCommandReleaseEnchantCommandLevelFixAndHasItemDataFixAndCommandDeferral
	CurrentCmdVersionExecuteIfScoreFixes
	CurrentCmdVersionReplaceItemAndLootReplaceBlockCommandsDoNotPlaceItemsIntoCauldronsFix
	CurrentCmdVersionChangesToCommandOriginRotation
	CurrentCmdVersionRemoveAuxValueParameterFromBlockCommands
	CurrentCmdVersionVolumeSelectorFixes
	CurrentCmdVersionEnableSummonRotation
	CurrentCmdVersionSummonCommandDefaultRotation
	CurrentCmdVersionPositionalDimensionFiltering
	CurrentCmdVersionCommandSelectorHasItemFilterNoLongerCallsSameItemFunction
	CurrentCmdVersionAgentSweepingBlockTest
	CurrentCmdVersionBlockStateEquals
	CurrentCmdVersionCommandPositionFix
	CurrentCmdVersionCommandSelectorHasItemFilterUsesDataAsDamageForSelectingDamageableItems
	CurrentCmdVersionExecuteDetectConditionSubcommandNotAllowNonLoadedBlocks
	CurrentCmdVersionRemoveSuicideKeyword
	CurrentCmdVersionCloneContainerBlockEntityRemovalFix
	CurrentCmdVersionStopSoundMusicFix
	CurrentCmdVersionSpreadPlayersStuckInGroundFixAndMaxHeightParameter
	CurrentCmdVersionLocateStructureOutput
	CurrentCmdVersionPostBlockFlattening
	CurrentCmdVersionTestForBlockCommandDoesNotIgnoreBlockState
	CurrentCmdVersionCount
	CurrentCmdVersionLatest
)

// CommandOriginData is a nested struct used in the packet.
type CommandOriginData struct {
	// Type The command origin type.
	Type uint8
	// UUID The unique UUID that represents an instantiation of a command. Each time a command is run it should be given a UUID to represent that instance.
	UUID uuid.UUID
	// RequestID The request Id.
	RequestID string
	// PlayerID The player Id.
	PlayerID int64
}

func (x *CommandOriginData) Marshal(r protocol.IO) {
	r.Uint8(&x.Type)
	r.UUID(&x.UUID)
	r.String(&x.RequestID)
	r.Int64(&x.PlayerID)
}

// CommandRequest "slash" command execution, client to server.
type CommandRequest struct {
	// Command The command being executed.
	Command string
	// Origin The origin of the command.
	Origin CommandOriginData
	// IsInternal Whether the command is internal or not.
	IsInternal bool
	// Version The version of the command.
	Version int32
}

// ID ...
func (*CommandRequest) ID() uint32 {
	return IDCommandRequest
}

func (pk *CommandRequest) Marshal(io protocol.IO) {
	io.String(&pk.Command)
	protocol.Single(io, &pk.Origin)
	io.Bool(&pk.IsInternal)
	io.Int32(&pk.Version)
}
