// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          78 (0x4E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EntityCommandTarget is a nested struct used in the packet.
type EntityCommandTarget struct {
	TargetRuntimeID uint64
}

func (x *EntityCommandTarget) Marshal(r protocol.IO) {
	r.Varuint64(&x.TargetRuntimeID)
}

// BlockCommandData is a nested struct used in the packet.
type BlockCommandData struct {
	BlockPosition protocol.BlockPos
	CommandBlockMode uint32
	RedstoneMode bool
	IsConditional bool
}

func (x *BlockCommandData) Marshal(r protocol.IO) {
	r.BlockPos(&x.BlockPosition)
	r.Varuint32(&x.CommandBlockMode)
	r.Bool(&x.RedstoneMode)
	r.Bool(&x.IsConditional)
}

// CommandBlockUpdate Command Block Update
type CommandBlockUpdate struct {
	// Target The command block target. The variant index encodes the legacy 'Is Block?' bool: 0 = entity (e.g. minecart command block), 1 = block.
	Target any
	Command string
	LastOutput string
	Name string
	FilteredName string
	TrackOutput bool
	TickDelay int32
	// ExecuteOnFirstTick If a delay is set on a repeating command block, should the command execute on first tick, or on first delay?
	ExecuteOnFirstTick bool
}

// ID ...
func (*CommandBlockUpdate) ID() uint32 {
	return IDCommandBlockUpdate
}

// Marshal ...
func (pk *CommandBlockUpdate) Marshal(io protocol.IO) {
	// TODO: Target - oneOf variants generated but control field unknown
	// Variants: EntityCommandTarget(0), BlockCommandData(1)
	io.String(&pk.Command)
	io.String(&pk.LastOutput)
	io.String(&pk.Name)
	io.String(&pk.FilteredName)
	io.Bool(&pk.TrackOutput)
	io.Int32(&pk.TickDelay)
	io.Bool(&pk.ExecuteOnFirstTick)
}
