// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          79 (0x4F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CommandOutputMessage is a nested struct used in the packet.
type CommandOutputMessage struct {
	// MessageID The unique identifier for the message.
	MessageID string
	// Successful The command output type.
	Successful bool
	// Parameters The parameters for the message.
	Parameters []string
}

func (x *CommandOutputMessage) Marshal(r protocol.IO) {
	r.String(&x.MessageID)
	r.Bool(&x.Successful)
	protocol.FuncSlice(r, &x.Parameters, r.String)
}

// CommandOutputEntry is a nested struct used in the packet.
type CommandOutputEntry struct {
	// OutputType The command output type.
	OutputType int32
	// SuccessCount The success count.
	SuccessCount uint32
	// OutputMessages The messages.
	OutputMessages []CommandOutputMessage
	// DataSet The data set.
	DataSet string
}

func (x *CommandOutputEntry) Marshal(r protocol.IO) {
	r.Int32(&x.OutputType)
	r.Uint32(&x.SuccessCount)
	protocol.Slice(r, &x.OutputMessages)
	r.String(&x.DataSet)
}

// CommandOutput "slash" command execution output, server to client.
type CommandOutput struct {
	// OriginData The origin of the command.
	OriginData CommandOriginData
	// Output The output.
	Output CommandOutputEntry
}

// ID ...
func (*CommandOutput) ID() uint32 {
	return IDCommandOutput
}

func (pk *CommandOutput) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.OriginData)
	protocol.Single(io, &pk.Output)
}
