// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          142 (0x8E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CompletedUsingItem Send server to client to complete the using item process. An example is when you finish drinking or eating.
type CompletedUsingItem struct {
	ItemID int16
	ItemUseMethod int32
}

// ID ...
func (*CompletedUsingItem) ID() uint32 {
	return IDCompletedUsingItem
}

func (pk *CompletedUsingItem) Marshal(io protocol.IO) {
	io.Int16(&pk.ItemID)
	io.Int32(&pk.ItemUseMethod)
}
