// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          46 (0x2E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ContainerOpen Sent from the server so that the client knows to open the container screen and do the chest opening animation.
type ContainerOpen struct {
	ContainerID uint8
	ContainerType uint8
	Position protocol.BlockPos
	EntityUniqueID int64
}

// ID ...
func (*ContainerOpen) ID() uint32 {
	return IDContainerOpen
}

func (pk *ContainerOpen) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Uint8(&pk.ContainerType)
	io.UBlockPos(&pk.Position)
	io.Varint64(&pk.EntityUniqueID)
}
