// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          317 (0x13D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// FullContainerName is a nested struct used in the packet.
type FullContainerName struct {
	ContainerName uint8
	DynamicID uint32
}

func (x *FullContainerName) Marshal(r protocol.IO) {
	r.Uint8(&x.ContainerName)
	r.Uint32(&x.DynamicID)
}

// ContainerRegistryCleanup This is used to trigger a clientside cleanup of the dynamic container registry.
type ContainerRegistryCleanup struct {
	RemovedContainers []FullContainerName
}

// ID ...
func (*ContainerRegistryCleanup) ID() uint32 {
	return IDContainerRegistryCleanup
}

func (pk *ContainerRegistryCleanup) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.RemovedContainers)
}
