// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          317 (0x13D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ContainerRegistryCleanup This is used to trigger a clientside cleanup of the dynamic container registry.
type ContainerRegistryCleanup struct {
	RemovedContainers []FullContainerName
}

// ID ...
func (*ContainerRegistryCleanup) ID() uint32 {
	return IDContainerRegistryCleanup
}

// Marshal ...
func (pk *ContainerRegistryCleanup) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.RemovedContainers)
}
