// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          51 (0x33)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ContainerSetData This is sent from the server basically any time that the "cooking" state of the brewing stand or the furnace changes (i.e. the loading bar)
type ContainerSetData struct {
	ContainerID uint8
	TrackingID int32
	Value int32
}

// ID ...
func (*ContainerSetData) ID() uint32 {
	return IDContainerSetData
}

func (pk *ContainerSetData) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Varint32(&pk.TrackingID)
	io.Varint32(&pk.Value)
}
