// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          47 (0x2F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ContainerClose After the game deletes the container manager on the client, the client sends this packet. Then the server deletes its container manager, and sends a packet back to the client that closes the container screen.
type ContainerClose struct {
	ContainerID uint8
	ContainerType uint8
	// ServerInitiatedClose True if the server initiated the closing
	ServerInitiatedClose bool
}

// ID ...
func (*ContainerClose) ID() uint32 {
	return IDContainerClose
}

func (pk *ContainerClose) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Uint8(&pk.ContainerType)
	io.Bool(&pk.ServerInitiatedClose)
}
