// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          171 (0xAB)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CreatePhoto Players now have the possibility to export photos from their portfolios into photo items in their inventory. EDU.
type CreatePhoto struct {
	RawID uint64
	PhotoName string
	PhotoItemName string
}

// ID ...
func (*CreatePhoto) ID() uint32 {
	return IDCreatePhoto
}

func (pk *CreatePhoto) Marshal(io protocol.IO) {
	io.Uint64(&pk.RawID)
	io.String(&pk.PhotoName)
	io.String(&pk.PhotoItemName)
}
