// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          314 (0x13A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// CurrentStructureFeature Informs the client of which Structure Feature they are currently occupying.
type CurrentStructureFeature struct {
	// CurrentStructureFeature The identifier of the Structure Feature that the player is currently occupying. If the player is not occupying a structure then this value is an empty string.
	CurrentStructureFeature string
}

// ID ...
func (*CurrentStructureFeature) ID() uint32 {
	return IDCurrentStructureFeature
}

func (pk *CurrentStructureFeature) Marshal(io protocol.IO) {
	io.String(&pk.CurrentStructureFeature)
}
