// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          189 (0xBD)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// DeathCauseMessageType is a nested struct used in the packet.
type DeathCauseMessageType struct {
	DeathCauseAttackName string
	DeathCauseMessageList []string
}

func (x *DeathCauseMessageType) Marshal(r protocol.IO) {
	r.String(&x.DeathCauseAttackName)
	protocol.FuncSlice(r, &x.DeathCauseMessageList, r.String)
}

// DeathInfo Sent from the server to client when player dies (Level::onPlayerDeath).
type DeathInfo struct {
	DeathCauseMessage DeathCauseMessageType
}

// ID ...
func (*DeathInfo) ID() uint32 {
	return IDDeathInfo
}

func (pk *DeathInfo) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.DeathCauseMessage)
}
