// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          155 (0x9B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// DebugInfo The system sends debug information via a generic network packet. This enables rendering of any server information on the client in for instance ImGui.
type DebugInfo struct {
	ActorID int64
	Data string
}

// ID ...
func (*DebugInfo) ID() uint32 {
	return IDDebugInfo
}

func (pk *DebugInfo) Marshal(io protocol.IO) {
	io.Varint64(&pk.ActorID)
	io.String(&pk.Data)
}
