// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001

// Package packet implements all packets used by the Minecraft Bedrock protocol.
// This package was auto-generated from the official Mojang bedrock-protocol-docs.
// See: https://github.com/Mojang/bedrock-protocol-docs
package packet
