// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897

// Package packet implements all packets used by the Minecraft Bedrock protocol.
// This package was auto-generated from the official Mojang bedrock-protocol-docs.
// See: https://github.com/Mojang/bedrock-protocol-docs
package packet
