// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          190 (0xBE)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EditorNetwork General use Editor specific packet - carries a payload of whatever serialized data that the individual IEditorNetworkPayload generates.
type EditorNetwork struct {
	RouteToManager bool
	RawVariantName string
	RawVariantData string
}

// ID ...
func (*EditorNetwork) ID() uint32 {
	return IDEditorNetwork
}

// Marshal ...
func (pk *EditorNetwork) Marshal(io protocol.IO) {
	io.Bool(&pk.RouteToManager)
	io.String(&pk.RawVariantName)
	io.String(&pk.RawVariantData)
}
