// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          190 (0xBE)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EditorNetwork General use Editor specific packet - carries a payload of whatever serialized data that the individual IEditorNetworkPayload generates.
type EditorNetwork struct {
	RouteToManager bool
	BinaryPayload map[string]any
}

// ID ...
func (*EditorNetwork) ID() uint32 {
	return IDEditorNetwork
}

func (pk *EditorNetwork) Marshal(io protocol.IO) {
	io.Bool(&pk.RouteToManager)
	io.NBT(&pk.BinaryPayload, nbt.NetworkLittleEndian)
}
