// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          170 (0xAA)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EduSharedURIResource is a nested struct used in the packet.
type EduSharedURIResource struct {
	ButtonName string
	LinkURI string
}

func (x *EduSharedURIResource) Marshal(r protocol.IO) {
	r.String(&x.ButtonName)
	r.String(&x.LinkURI)
}

// EduURIResource Transmits Edu Shared Uri Resource settings to all clients.
type EduURIResource struct {
	EduSharedURIResource EduSharedURIResource
}

// ID ...
func (*EduURIResource) ID() uint32 {
	return IDEduURIResource
}

func (pk *EduURIResource) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.EduSharedURIResource)
}
