// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          137 (0x89)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ExternalLinkSettings is a nested struct used in the packet.
type ExternalLinkSettings struct {
	URL string
	DisplayName string
}

func (x *ExternalLinkSettings) Marshal(r protocol.IO) {
	r.String(&x.URL)
	r.String(&x.DisplayName)
}

// EducationLevelSettings is a nested struct used in the packet.
type EducationLevelSettings struct {
	CodeBuilderDefaultURI string
	CodeBuilderTitle string
	CanResizeCodeBuilder bool
	DisableLegacyTitleBar bool
	PostProcessFilter string
	ScreenshotBorderResourcePath string
	AgentCapabilities bool
	LocalSettings string
	AlwaysFalse bool
	ExternalLinkSettings ExternalLinkSettings
}

func (x *EducationLevelSettings) Marshal(r protocol.IO) {
	r.String(&x.CodeBuilderDefaultURI)
	r.String(&x.CodeBuilderTitle)
	r.Bool(&x.CanResizeCodeBuilder)
	r.Bool(&x.DisableLegacyTitleBar)
	r.String(&x.PostProcessFilter)
	r.String(&x.ScreenshotBorderResourcePath)
	r.Bool(&x.AgentCapabilities)
	r.String(&x.LocalSettings)
	r.Bool(&x.AlwaysFalse)
	protocol.Single(r, &x.ExternalLinkSettings)
}

// EducationSettings Transmits EducationLevelSettings to all clients.
type EducationSettings struct {
	EducationLevelSettings EducationLevelSettings
}

// ID ...
func (*EducationSettings) ID() uint32 {
	return IDEducationSettings
}

func (pk *EducationSettings) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.EducationLevelSettings)
}
