// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          152 (0x98)

package packet

import (
	"github.com/google/uuid"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EmoteList Allows clients to download emotes that other clients have equipped.
type EmoteList struct {
	RuntimeID uint64
	EmotePieceIds []uuid.UUID
}

// ID ...
func (*EmoteList) ID() uint32 {
	return IDEmoteList
}

func (pk *EmoteList) Marshal(io protocol.IO) {
	io.Varuint64(&pk.RuntimeID)
	protocol.FuncSlice(io, &pk.EmotePieceIds, io.UUID)
}
