// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          138 (0x8A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Emote A client sends this to the server to notify other clients about the emote.
type Emote struct {
	ActorRuntimeID uint64
	EmoteID string
	EmoteLengthTicks uint32
	XUID string
	PlatformID string
	Flags uint8
}

// ID ...
func (*Emote) ID() uint32 {
	return IDEmote
}

// Marshal ...
func (pk *Emote) Marshal(io protocol.IO) {
	io.Varuint64(&pk.ActorRuntimeID)
	io.String(&pk.EmoteID)
	io.Varuint32(&pk.EmoteLengthTicks)
	io.String(&pk.XUID)
	io.String(&pk.PlatformID)
	io.Uint8(&pk.Flags)
}
