// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          191 (0xBF)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// FeatureRegistryFeatureBinaryJsonFormat is a nested struct used in the packet.
type FeatureRegistryFeatureBinaryJsonFormat struct {
	FeatureName string
	BinaryJsonOutput string
}

func (x *FeatureRegistryFeatureBinaryJsonFormat) Marshal(r protocol.IO) {
	r.String(&x.FeatureName)
	r.String(&x.BinaryJsonOutput)
}

// FeatureRegistry This is the packet that tracks the active feature registry data from the server so that client can place the features themselves.
type FeatureRegistry struct {
	FeaturesDataList []FeatureRegistryFeatureBinaryJsonFormat
}

// ID ...
func (*FeatureRegistry) ID() uint32 {
	return IDFeatureRegistry
}

func (pk *FeatureRegistry) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.FeaturesDataList)
}
