// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          72 (0x48)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// GameRule is a nested struct used in the packet.
type GameRule struct {
	RuleName string
	RuleCanBeModified bool
	RuleValue any
}

func (x *GameRule) Marshal(r protocol.IO) {
	r.String(&x.RuleName)
	r.Bool(&x.RuleCanBeModified)
	switch val := x.RuleValue.(type) {
	case nil:
		var typeID uint32 = 0
		r.Uint32(&typeID)
		_ = val // nil value, nothing more to write
	case bool:
		var typeID uint32 = 1
		r.Uint32(&typeID)
		r.Bool(&val)
	case int32:
		var typeID uint32 = 2
		r.Uint32(&typeID)
		r.Varint32(&val)
	case float32:
		var typeID uint32 = 3
		r.Uint32(&typeID)
		r.Float32(&val)
	}
}

// GameRulesChangedPacketData is a nested struct used in the packet.
type GameRulesChangedPacketData struct {
	RulesList []GameRule
}

func (x *GameRulesChangedPacketData) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.RulesList)
}

// GameRulesChanged Updates game rules.
type GameRulesChanged struct {
	RuleData GameRulesChangedPacketData
}

// ID ...
func (*GameRulesChanged) ID() uint32 {
	return IDGameRulesChanged
}

func (pk *GameRulesChanged) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.RuleData)
}
