// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          194 (0xC2)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	RotationNone = iota
	RotationRotate90
	RotationRotate180
	RotationRotate270
	RotationClockwise90
	RotationClockwise180
	RotationCounterClockwise90
)

// GameTestRequest Internal Text Packet
type GameTestRequest struct {
	MaxTestsPerBatch int32
	RepeatCount int32
	Rotation uint8
	StopOnFailure bool
	TestPos protocol.BlockPos
	TestsPerRow int32
	TestName string
}

// ID ...
func (*GameTestRequest) ID() uint32 {
	return IDGameTestRequest
}

func (pk *GameTestRequest) Marshal(io protocol.IO) {
	io.Varint32(&pk.MaxTestsPerBatch)
	io.Varint32(&pk.RepeatCount)
	io.Uint8(&pk.Rotation)
	io.Bool(&pk.StopOnFailure)
	io.BlockPos(&pk.TestPos)
	io.Varint32(&pk.TestsPerRow)
	io.String(&pk.TestName)
}
