// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          331 (0x14B)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	GraphicsOverrideParameterTypeSkyZenithColor = iota
	GraphicsOverrideParameterTypeSkyHorizonColor
	GraphicsOverrideParameterTypeHorizonBlendMin
	GraphicsOverrideParameterTypeHorizonBlendMax
	GraphicsOverrideParameterTypeHorizonBlendStart
	GraphicsOverrideParameterTypeHorizonBlendMieStart
	GraphicsOverrideParameterTypeRayleighStrength
	GraphicsOverrideParameterTypeSunMieStrength
	GraphicsOverrideParameterTypeMoonMieStrength
	GraphicsOverrideParameterTypeSunGlareShape
	GraphicsOverrideParameterTypeChlorophyll
	GraphicsOverrideParameterTypeCDOM
	GraphicsOverrideParameterTypeSuspendedSediment
	GraphicsOverrideParameterTypeWavesDepth
	GraphicsOverrideParameterTypeWavesFrequency
	GraphicsOverrideParameterTypeWavesFrequencyScaling
	GraphicsOverrideParameterTypeWavesSpeed
	GraphicsOverrideParameterTypeWavesSpeedScaling
	GraphicsOverrideParameterTypeWavesShape
	GraphicsOverrideParameterTypeWavesOctaves
	GraphicsOverrideParameterTypeWavesMix
	GraphicsOverrideParameterTypeWavesPull
	GraphicsOverrideParameterTypeWavesDirectionIncrement
	GraphicsOverrideParameterTypeMidtonesContrast
	GraphicsOverrideParameterTypeHighlightsContrast
	GraphicsOverrideParameterTypeShadowsContrast
	GraphicsOverrideParameterTypeHighlightsGain
	GraphicsOverrideParameterTypeHighlightsGamma
	GraphicsOverrideParameterTypeHighlightsOffset
	GraphicsOverrideParameterTypeHighlightsSaturation
	GraphicsOverrideParameterTypeMidtonesGain
	GraphicsOverrideParameterTypeMidtonesGamma
	GraphicsOverrideParameterTypeMidtonesOffset
	GraphicsOverrideParameterTypeMidtonesSaturation
	GraphicsOverrideParameterTypeShadowsGain
	GraphicsOverrideParameterTypeShadowsGamma
	GraphicsOverrideParameterTypeShadowsOffset
	GraphicsOverrideParameterTypeShadowsSaturation
	GraphicsOverrideParameterTypeHighlightsMin
	GraphicsOverrideParameterTypeShadowsMax
	GraphicsOverrideParameterTypeTemperature
	GraphicsOverrideParameterTypeSunColor
	GraphicsOverrideParameterTypeSunIlluminance
	GraphicsOverrideParameterTypeMoonColor
	GraphicsOverrideParameterTypeMoonIlluminance
	GraphicsOverrideParameterTypeFlashColor
	GraphicsOverrideParameterTypeFlashIlluminance
	GraphicsOverrideParameterTypeAmbientColor
	GraphicsOverrideParameterTypeAmbientIlluminance
	GraphicsOverrideParameterTypeEmissiveDesaturation
	GraphicsOverrideParameterTypeSkyIntensity
	GraphicsOverrideParameterTypeOrbitalOffsetDegrees
)

// GraphicsOverrideParameter Sent from the server to the client when a server script changes the rendering settings
type GraphicsOverrideParameter struct {
	// ParameterKeyframeValues Time of Day key to Graphics Parameter value, Depending on the parameters, either all three components are used as a color or just the x component is used as a float, int, or bool
	ParameterKeyframeValues any
	// FloatValue If set, contains a single float graphics parameter to be overriden
	FloatValue float32
	// Vec3Value If set, contains a single Vec3 graphics parameter to be overriden
	Vec3Value mgl32.Vec3
	// BiomeIdentifier Determines which biome the override parameter is applied to
	BiomeIdentifier string
	// PlayerIdentifier Determines which player the override parameter is applied to
	PlayerIdentifier protocol.Optional[string]
	// IdentifierForParameter Identifier for the parameter that is having its value changed
	IdentifierForParameter uint8
	// ResetParameter If true, the specified parameter will be reset. If false, the parameter will be set using the data fields.
	ResetParameter bool
}

// ID ...
func (*GraphicsOverrideParameter) ID() uint32 {
	return IDGraphicsOverrideParameter
}

// Marshal ...
func (pk *GraphicsOverrideParameter) Marshal(io protocol.IO) {
	// TODO: ParameterKeyframeValues - type mapping not found for any
	io.Float32(&pk.FloatValue)
	io.Vec3(&pk.Vec3Value)
	io.String(&pk.BiomeIdentifier)
	protocol.OptionalFunc(io, &pk.PlayerIdentifier, io.String)
	io.Uint8(&pk.IdentifierForParameter)
	io.Bool(&pk.ResetParameter)
}
