// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          331 (0x14B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	GraphicsOverrideParameterTypeSkyZenithColor = iota
	GraphicsOverrideParameterTypeSkyHorizonColor
	GraphicsOverrideParameterTypeHorizonBlendMin
	GraphicsOverrideParameterTypeHorizonBlendMax
	GraphicsOverrideParameterTypeHorizonBlendStart
	GraphicsOverrideParameterTypeHorizonBlendMieStart
	GraphicsOverrideParameterTypeRayleighStrength
	GraphicsOverrideParameterTypeSunMieStrength
	GraphicsOverrideParameterTypeMoonMieStrength
	GraphicsOverrideParameterTypeSunGlareShape
)

// GraphicsOverrideParameter Sent from the server to the client when a server script changes the rendering settings
type GraphicsOverrideParameter struct {
	// ParameterKeyframeValues Time of Day key to Graphics Parameter value, Depending on the parameters, either all three components are used as a color or just the x component is used as a float, int, or bool
	ParameterKeyframeValues any
	// BiomeIdentifier Determines which biome the override parameter is applied to
	BiomeIdentifier string
	// IdentifierForParameter Identifier for the parameter that is having its value changed
	IdentifierForParameter uint8
	// ResetParameter If true, the specified parameter will be reset. If false, the parameter will be set using the data fields.
	ResetParameter bool
}

// ID ...
func (*GraphicsOverrideParameter) ID() uint32 {
	return IDGraphicsOverrideParameter
}

func (pk *GraphicsOverrideParameter) Marshal(io protocol.IO) {
	// TODO: ParameterKeyframeValues - type mapping not found for any
	io.String(&pk.BiomeIdentifier)
	io.Uint8(&pk.IdentifierForParameter)
	io.Bool(&pk.ResetParameter)
}
