// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          54 (0x36)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// GuiDataPickItem The server telling the client what item slot to hover over in the hotbar.
type GuiDataPickItem struct {
	ItemName string
	ItemEffectName string
	Slot int32
}

// ID ...
func (*GuiDataPickItem) ID() uint32 {
	return IDGuiDataPickItem
}

func (pk *GuiDataPickItem) Marshal(io protocol.IO) {
	io.String(&pk.ItemName)
	io.String(&pk.ItemEffectName)
	io.Int32(&pk.Slot)
}
