// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          38 (0x26)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// HurtArmor Hurt Armor
type HurtArmor struct {
	Cause int32
	Damage int32
	// ArmorSlots Bitset
	ArmorSlots uint64
}

// ID ...
func (*HurtArmor) ID() uint32 {
	return IDHurtArmor
}

// Marshal ...
func (pk *HurtArmor) Marshal(io protocol.IO) {
	io.Varint32(&pk.Cause)
	io.Varint32(&pk.Damage)
	io.Varuint64(&pk.ArmorSlots)
}
