// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          33 (0x21)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	InteractPacketPayloadActionInvalid = iota
	InteractPacketPayloadActionStopRiding
	InteractPacketPayloadActionInteractUpdate
	InteractPacketPayloadActionNpcOpen
	InteractPacketPayloadActionOpenInventory
)

// Interact Interact
type Interact struct {
	Action uint8
	EntityRuntimeID uint64
	Position protocol.Optional[mgl32.Vec3]
}

// ID ...
func (*Interact) ID() uint32 {
	return IDInteract
}

func (pk *Interact) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varuint64(&pk.EntityRuntimeID)
	protocol.OptionalFunc(io, &pk.Position, io.Vec3)
}
