// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          30 (0x1E)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LegacySetSlot is a nested struct used in the packet.
type LegacySetSlot struct {
	// ContainerEnum The container enum name identifying which container slot set this belongs to.
	ContainerEnum uint8
	// Slots List of inventory slot indices within the given container.
	Slots []uint8
}

func (x *LegacySetSlot) Marshal(r protocol.IO) {
	r.Uint8(&x.ContainerEnum)
	protocol.FuncSlice(r, &x.Slots, r.Uint8)
}

// NormalTransactionData is a nested struct used in the packet.
type NormalTransactionData struct {
	// Actions Base inventory actions. Lists the slot changes making up this Normal (container UI) transaction.
	Actions any
}

func (x *NormalTransactionData) Marshal(r protocol.IO) {
	// TODO: Actions - unresolved struct reference
}

// InventoryMismatchData is a nested struct used in the packet.
type InventoryMismatchData struct {
	// Actions Base inventory actions. Lists the slot changes making up this server-to-client rejection transaction.
	Actions any
}

func (x *InventoryMismatchData) Marshal(r protocol.IO) {
	// TODO: Actions - unresolved struct reference
}

// ItemUseInventoryTransaction is a nested struct used in the packet.
type ItemUseInventoryTransaction struct {
	// Actions Base inventory actions. Lists the inventory slot changes associated with this transaction.
	Actions any
	// ActionType The type of item use action performed.
	ActionType int32
	// TriggerType PlayerInput if a direct result of the player's initial button input. SimulationTick if the player is holding down input from a previous tick.
	TriggerType uint8
	// Position The position of the target block.
	Position protocol.BlockPos
	// Face The face of the target block that was clicked.
	Face uint8
	// Slot The inventory slot of the item being used.
	Slot int32
	// Item The item stack descriptor of the item being used.
	Item any
	// FromPosition The player's position when this transaction was sent.
	FromPosition mgl32.Vec3
	// ClickPosition The position within the target block face that was clicked.
	ClickPosition mgl32.Vec3
	// TargetBlockID The runtime block state ID of the target block.
	TargetBlockID uint32
	// ClientInteractPrediction Whether the client predicted the interaction would succeed.
	ClientInteractPrediction uint8
	// ClientCooldownState Whether the item is currently on cooldown on the client.
	ClientCooldownState uint8
}

func (x *ItemUseInventoryTransaction) Marshal(r protocol.IO) {
	// TODO: Actions - unresolved struct reference
	r.Varint32(&x.ActionType)
	r.Uint8(&x.TriggerType)
	r.BlockPos(&x.Position)
	r.Uint8(&x.Face)
	r.Varint32(&x.Slot)
	// TODO: Item - unresolved struct reference
	r.Vec3(&x.FromPosition)
	r.Vec3(&x.ClickPosition)
	r.Varuint32(&x.TargetBlockID)
	r.Uint8(&x.ClientInteractPrediction)
	r.Uint8(&x.ClientCooldownState)
}

// ItemUseOnActorInventoryTransaction is a nested struct used in the packet.
type ItemUseOnActorInventoryTransaction struct {
	// Actions Base inventory actions. Lists the inventory slot changes associated with this transaction.
	Actions any
	// RuntimeID The runtime ID of the actor being interacted with or attacked.
	RuntimeID uint64
	// ActionType Interact: right-click on actor. Attack: left-click or trident spin attack.
	ActionType int32
	// Slot The inventory slot of the item being used on the actor.
	Slot int32
	// Item The item stack descriptor of the item being used on the actor.
	Item any
	// FromPosition The player's position when this transaction was sent.
	FromPosition mgl32.Vec3
	// HitPosition The position on the actor that was clicked.
	HitPosition mgl32.Vec3
}

func (x *ItemUseOnActorInventoryTransaction) Marshal(r protocol.IO) {
	// TODO: Actions - unresolved struct reference
	r.Varuint64(&x.RuntimeID)
	r.Varint32(&x.ActionType)
	r.Varint32(&x.Slot)
	// TODO: Item - unresolved struct reference
	r.Vec3(&x.FromPosition)
	r.Vec3(&x.HitPosition)
}

// ItemReleaseInventoryTransaction is a nested struct used in the packet.
type ItemReleaseInventoryTransaction struct {
	// Actions Base inventory actions. Lists the inventory slot changes associated with this transaction.
	Actions any
	// ActionType Release: firing a bow or releasing a held item. Use: finishing charging a crossbow.
	ActionType int32
	// Slot The inventory slot of the item being released.
	Slot int32
	// Item The item stack descriptor of the item being released.
	Item any
	// FromPosition The player's position when this transaction was sent.
	FromPosition mgl32.Vec3
}

func (x *ItemReleaseInventoryTransaction) Marshal(r protocol.IO) {
	// TODO: Actions - unresolved struct reference
	r.Varint32(&x.ActionType)
	r.Varint32(&x.Slot)
	// TODO: Item - unresolved struct reference
	r.Vec3(&x.FromPosition)
}

// InventoryTransaction Inventory Transaction. Sent for item interaction UI depending on if ItemStackNetManager is enabled as well as when the player uses items in gameplay. See ComplexInventoryTransaction::Type for more details.
type InventoryTransaction struct {
	// LegacyRequestID Used when ItemStackNetManager is enabled. Identifies a legacy client item request. Negative, even values are valid. Zero indicates no legacy request.
	LegacyRequestID int32
	// LegacySetItemSlots Only present when Legacy Request ID is valid. Lists the open containers and their slot indices the client is requesting changes for.
	LegacySetItemSlots protocol.Optional[[]LegacySetSlot]
	// Transaction The inventory transaction. The variant index encodes ComplexInventoryTransaction::Type (0=Normal, 1=Mismatch, 2=ItemUse, 3=ItemUseOnActor, 4=ItemRelease), matching the legacy wire format discriminator.
	Transaction any
}

// ID ...
func (*InventoryTransaction) ID() uint32 {
	return IDInventoryTransaction
}

func (pk *InventoryTransaction) Marshal(io protocol.IO) {
	io.Varint32(&pk.LegacyRequestID)
	// TODO: LegacySetItemSlots - optional slice of structs needs manual handling
	// TODO: Transaction - oneOf variants generated but control field unknown
	// Variants: NormalTransactionData(0), InventoryMismatchData(1), ItemUseInventoryTransaction(2), ItemUseOnActorInventoryTransaction(3), ItemReleaseInventoryTransaction(4)
}
