// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          49 (0x31)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// FullContainerName is a nested struct used in the packet.
type FullContainerName struct {
	ContainerName uint8
	DynamicID uint32
}

func (x *FullContainerName) Marshal(r protocol.IO) {
	r.Uint8(&x.ContainerName)
	r.Uint32(&x.DynamicID)
}

// InventoryContent This is used for updating an entire container. Example uses include: player respawned, replace items command, 3rd party content calls sendInventory(), block picking.
type InventoryContent struct {
	// ContainerID The container ID
	ContainerID uint32
	// Slots The item stacks for each inventory slot
	Slots []any
	// FullContainerName Used to reference a specific container within a given screen container context
	FullContainerName FullContainerName
	// StorageItem Optional storage item containing the contents to set. Only the item type is relevant, not any stack information.
	StorageItem any
}

// ID ...
func (*InventoryContent) ID() uint32 {
	return IDInventoryContent
}

// Marshal ...
func (pk *InventoryContent) Marshal(io protocol.IO) {
	io.Varuint32(&pk.ContainerID)
	// TODO: Slots - array of complex referenced type
	protocol.Single(io, &pk.FullContainerName)
	// TODO: StorageItem - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
}
