// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          50 (0x32)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// InventorySlot Updates one slot in an inventory rather than the whole thing. So like animal inventory (horses, donkeys, etc) and chests. Hotbar, offhand, and some player inventory changes.
type InventorySlot struct {
	// ContainerID The container ID
	ContainerID uint8
	// Slot The slot index in the container
	Slot uint32
	// FullContainerName Optional reference to a specific container within a given screen container context
	FullContainerName protocol.Optional[FullContainerName]
	// StorageItem Optional storage item to set the 'Item' into. (e.g. bundle)
	StorageItem any
	// Item The item stack for this inventory slot
	Item any
}

// ID ...
func (*InventorySlot) ID() uint32 {
	return IDInventorySlot
}

// Marshal ...
func (pk *InventorySlot) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Varuint32(&pk.Slot)
	protocol.OptionalMarshaler(io, &pk.FullContainerName)
	// TODO: StorageItem - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	// TODO: Item - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
}
