// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          162 (0xA2)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ItemData is a nested struct used in the packet.
type ItemData struct {
	ItemName string
	// ItemID Block id's < 256 (can be negative); Item id's >= 257
	ItemID int16
	IsComponentBased bool
	ItemVersion int32
	ItemComponentData any
}

func (x *ItemData) Marshal(r protocol.IO) {
	r.String(&x.ItemName)
	r.Int16(&x.ItemID)
	r.Bool(&x.IsComponentBased)
	r.Varint32(&x.ItemVersion)
	// TODO: ItemComponentData - unresolved struct reference
}

// ItemRegistry Item data from the server. Contains component information.
type ItemRegistry struct {
	ItemData []ItemData
}

// ID ...
func (*ItemRegistry) ID() uint32 {
	return IDItemRegistry
}

func (pk *ItemRegistry) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.ItemData)
}
