// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          313 (0x139)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// JigsawStructureData Jigsaw Structure data used by client jigsaw structure worldgen. This packet contains a copy of the behavior pack jigsaw structure rules.
type JigsawStructureData struct {
	JigsawStructureDataTag any
}

// ID ...
func (*JigsawStructureData) ID() uint32 {
	return IDJigsawStructureData
}

// Marshal ...
func (pk *JigsawStructureData) Marshal(io protocol.IO) {
	// TODO: JigsawStructureDataTag - unresolved reference: #/definitions/3172631924
}
