// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          109 (0x6D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	LabTableReactionTypeNone = iota
	LabTableReactionTypeIceBomb
	LabTableReactionTypeBleach
	LabTableReactionTypeElephantToothpaste
	LabTableReactionTypeFertilizer
	LabTableReactionTypeHeatBlock
	LabTableReactionTypeMagnesiumSalts
	LabTableReactionTypeMiscFire
	LabTableReactionTypeMiscExplosion
	LabTableReactionTypeMiscLava
	LabTableReactionTypeMiscMystical
	LabTableReactionTypeMiscSmoke
	LabTableReactionTypeMiscLargeSmoke
)

const (
	LabTablePacketPayloadTypeStartCombine = iota
	LabTablePacketPayloadTypeStartReaction
	LabTablePacketPayloadTypeReset
)

// LabTable For the EDU Chemistry Lab Table block actor.
type LabTable struct {
	Type uint8
	Position protocol.BlockPos
	Reaction uint8
}

// ID ...
func (*LabTable) ID() uint32 {
	return IDLabTable
}

func (pk *LabTable) Marshal(io protocol.IO) {
	io.Uint8(&pk.Type)
	io.BlockPos(&pk.Position)
	io.Uint8(&pk.Reaction)
}
