// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          125 (0x7D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LecternUpdate This is used for the Lectern Block Actor.
type LecternUpdate struct {
	NewPageToShow uint8
	TotalPages uint8
	PositionOfLecternToUpdate protocol.BlockPos
}

// ID ...
func (*LecternUpdate) ID() uint32 {
	return IDLecternUpdate
}

// Marshal ...
func (pk *LecternUpdate) Marshal(io protocol.IO) {
	io.Uint8(&pk.NewPageToShow)
	io.Uint8(&pk.TotalPages)
	io.BlockPos(&pk.PositionOfLecternToUpdate)
}
