// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          65 (0x41)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	LegacyTelemetryEventPacketPayloadTypeAchievement = iota
	LegacyTelemetryEventPacketPayloadTypeInteraction
	LegacyTelemetryEventPacketPayloadTypePortalCreated
	LegacyTelemetryEventPacketPayloadTypePortalUsed
	LegacyTelemetryEventPacketPayloadTypeMobKilled
	LegacyTelemetryEventPacketPayloadTypeCauldronUsed
	LegacyTelemetryEventPacketPayloadTypePlayerDied
	LegacyTelemetryEventPacketPayloadTypeBossKilled
	LegacyTelemetryEventPacketPayloadTypeAgentcommandObsolete
	LegacyTelemetryEventPacketPayloadTypeAgentCreated
	LegacyTelemetryEventPacketPayloadTypePatternremovedObsolete
	LegacyTelemetryEventPacketPayloadTypeSlashCommand
	LegacyTelemetryEventPacketPayloadTypeFishbucketedObsolete
	LegacyTelemetryEventPacketPayloadTypeMobBorn
	LegacyTelemetryEventPacketPayloadTypePetdiedObsolete
	LegacyTelemetryEventPacketPayloadTypePOICauldronUsed
	LegacyTelemetryEventPacketPayloadTypeComposterUsed
	LegacyTelemetryEventPacketPayloadTypeBellUsed
	LegacyTelemetryEventPacketPayloadTypeActorDefinition
	LegacyTelemetryEventPacketPayloadTypeRaidUpdate
	LegacyTelemetryEventPacketPayloadTypePlayermovementanomalyObsolete
	LegacyTelemetryEventPacketPayloadTypePlayermovementcorrectedObsolete
	LegacyTelemetryEventPacketPayloadTypeHoneyHarvested
	LegacyTelemetryEventPacketPayloadTypeTargetBlockHit
	LegacyTelemetryEventPacketPayloadTypePiglinBarter
	LegacyTelemetryEventPacketPayloadTypePlayerWaxedOrUnwaxedCopper
	LegacyTelemetryEventPacketPayloadTypeCodeBuilderRuntimeAction
	LegacyTelemetryEventPacketPayloadTypeCodeBuilderScoreboard
	LegacyTelemetryEventPacketPayloadTypeStriderRiddenInLavaInOverworld
	LegacyTelemetryEventPacketPayloadTypeSneakCloseToSculkSensor
	LegacyTelemetryEventPacketPayloadTypeCarefulRestoration
	LegacyTelemetryEventPacketPayloadTypeItemUsed
)

// Achievement is a nested struct used in the packet.
type Achievement struct {
	AchievementID uint8
}

func (x *Achievement) Marshal(r protocol.IO) {
	r.Uint8(&x.AchievementID)
}

// Interaction is a nested struct used in the packet.
type Interaction struct {
	InteractedEntityID int64
	InteractionType uint8
	InteractionActorType int32
	InteractionActorVariant int32
	InteractionActorColor uint8
}

func (x *Interaction) Marshal(r protocol.IO) {
	r.Varint64(&x.InteractedEntityID)
	r.Uint8(&x.InteractionType)
	r.Varint32(&x.InteractionActorType)
	r.Varint32(&x.InteractionActorVariant)
	r.Uint8(&x.InteractionActorColor)
}

// PortalCreated is a nested struct used in the packet.
type PortalCreated struct {
	// DimensionID Currently supported: (0 -> Overworld, 1 -> Nether, 2 -> The End, 3 -> Undefined)
	DimensionID int32
}

func (x *PortalCreated) Marshal(r protocol.IO) {
	r.Varint32(&x.DimensionID)
}

// PortalUsed is a nested struct used in the packet.
type PortalUsed struct {
	// SourceDimensionID Currently supported: (0 -> Overworld, 1 -> Nether, 2 -> The End, 3 -> Undefined)
	SourceDimensionID int32
	// TargetDimensionID Currently supported: (0 -> Overworld, 1 -> Nether, 2 -> The End, 3 -> Undefined)
	TargetDimensionID int32
}

func (x *PortalUsed) Marshal(r protocol.IO) {
	r.Varint32(&x.SourceDimensionID)
	r.Varint32(&x.TargetDimensionID)
}

// MobKilled is a nested struct used in the packet.
type MobKilled struct {
	InstigatorActorID int64
	TargetActorID int64
	InstigatorChildActorType int32
	DamageSource int32
	// TradeTier -1 if not a trading actor.
	TradeTier int32
	// TraderName Empty if not a trading actor.
	TraderName string
}

func (x *MobKilled) Marshal(r protocol.IO) {
	r.Varint64(&x.InstigatorActorID)
	r.Varint64(&x.TargetActorID)
	r.Varint32(&x.InstigatorChildActorType)
	r.Varint32(&x.DamageSource)
	r.Varint32(&x.TradeTier)
	r.String(&x.TraderName)
}

// CauldronUsed is a nested struct used in the packet.
type CauldronUsed struct {
	ContentsColor uint32
	ContentsType int16
	FillLevel int16
}

func (x *CauldronUsed) Marshal(r protocol.IO) {
	r.Varuint32(&x.ContentsColor)
	r.Int16(&x.ContentsType)
	r.Int16(&x.FillLevel)
}

// PlayerDied is a nested struct used in the packet.
type PlayerDied struct {
	InstigatorActorID int32
	InstigatorMobVariant int32
	DamageSource int32
	DiedInRaid bool
}

func (x *PlayerDied) Marshal(r protocol.IO) {
	r.Varint32(&x.InstigatorActorID)
	r.Varint32(&x.InstigatorMobVariant)
	r.Varint32(&x.DamageSource)
	r.Bool(&x.DiedInRaid)
}

// BossKilled is a nested struct used in the packet.
type BossKilled struct {
	BossActorID int64
	PartySize int32
	BossType int32
}

func (x *BossKilled) Marshal(r protocol.IO) {
	r.Varint64(&x.BossActorID)
	r.Varint32(&x.PartySize)
	r.Varint32(&x.BossType)
}

// SlashCommand is a nested struct used in the packet.
type SlashCommand struct {
	SuccessCount int32
	ErrorCount int32
	CommandName string
	ErrorList string
}

func (x *SlashCommand) Marshal(r protocol.IO) {
	r.Varint32(&x.SuccessCount)
	r.Varint32(&x.ErrorCount)
	r.String(&x.CommandName)
	r.String(&x.ErrorList)
}

// MobBorn is a nested struct used in the packet.
type MobBorn struct {
	BornBabyEntityType int32
	BornBabyEntityVariant int32
	BornBabyColor uint8
}

func (x *MobBorn) Marshal(r protocol.IO) {
	r.Varint32(&x.BornBabyEntityType)
	r.Varint32(&x.BornBabyEntityVariant)
	r.Uint8(&x.BornBabyColor)
}

// POICauldronUsed is a nested struct used in the packet.
type POICauldronUsed struct {
	BlockInteractionType uint8
	// ItemID Id of the relevant item used in the interaction.
	ItemID int16
}

func (x *POICauldronUsed) Marshal(r protocol.IO) {
	r.Uint8(&x.BlockInteractionType)
	r.Int16(&x.ItemID)
}

// ComposterUsed is a nested struct used in the packet.
type ComposterUsed struct {
	BlockInteractionType uint8
	// ItemID Id of the relevant item used in the interaction.
	ItemID int16
}

func (x *ComposterUsed) Marshal(r protocol.IO) {
	r.Uint8(&x.BlockInteractionType)
	r.Int16(&x.ItemID)
}

// BellUsed is a nested struct used in the packet.
type BellUsed struct {
	// ItemID Id of the relevant item used in the interaction.
	ItemID int16
}

func (x *BellUsed) Marshal(r protocol.IO) {
	r.Int16(&x.ItemID)
}

// ActorDefinition is a nested struct used in the packet.
type ActorDefinition struct {
	EventName string
}

func (x *ActorDefinition) Marshal(r protocol.IO) {
	r.String(&x.EventName)
}

// RaidUpdate is a nested struct used in the packet.
type RaidUpdate struct {
	CurrentWave int32
	TotalWaves int32
	Success bool
}

func (x *RaidUpdate) Marshal(r protocol.IO) {
	r.Varint32(&x.CurrentWave)
	r.Varint32(&x.TotalWaves)
	r.Bool(&x.Success)
}

// TargetBlockHit is a nested struct used in the packet.
type TargetBlockHit struct {
	RedstoneLevel int32
}

func (x *TargetBlockHit) Marshal(r protocol.IO) {
	r.Varint32(&x.RedstoneLevel)
}

// PiglinBarter is a nested struct used in the packet.
type PiglinBarter struct {
	ItemID int32
	WasTargetingBarteringPlayer bool
}

func (x *PiglinBarter) Marshal(r protocol.IO) {
	r.Varint32(&x.ItemID)
	r.Bool(&x.WasTargetingBarteringPlayer)
}

// PlayerWaxedOrUnwaxedCopper is a nested struct used in the packet.
type PlayerWaxedOrUnwaxedCopper struct {
	PlayerWaxedOrUnwaxedCopperBlockID int32
}

func (x *PlayerWaxedOrUnwaxedCopper) Marshal(r protocol.IO) {
	r.Varint32(&x.PlayerWaxedOrUnwaxedCopperBlockID)
}

// CodeBuilderRuntimeAction is a nested struct used in the packet.
type CodeBuilderRuntimeAction struct {
	CodeBuilderRuntimeAction string
}

func (x *CodeBuilderRuntimeAction) Marshal(r protocol.IO) {
	r.String(&x.CodeBuilderRuntimeAction)
}

// CodeBuilderScoreboard is a nested struct used in the packet.
type CodeBuilderScoreboard struct {
	ObjectiveName string
	Score int32
}

func (x *CodeBuilderScoreboard) Marshal(r protocol.IO) {
	r.String(&x.ObjectiveName)
	r.Varint32(&x.Score)
}

// ItemUsed is a nested struct used in the packet.
type ItemUsed struct {
	ItemID int16
	ItemAux int32
	UseMethod int32
	Count int32
}

func (x *ItemUsed) Marshal(r protocol.IO) {
	r.Int16(&x.ItemID)
	r.Int32(&x.ItemAux)
	r.Int32(&x.UseMethod)
	r.Int32(&x.Count)
}

// LegacyTelemetryEvent Sends telemetry events to the client so the client can then send that on to the eventing system
type LegacyTelemetryEvent struct {
	EntityUniqueID int64
	EventType int32
	UsePlayerID bool
	// EventData Actual event payload (variant) holding data specific to the type of event (achievement ID for an achievement event).
	EventData any
}

// ID ...
func (*LegacyTelemetryEvent) ID() uint32 {
	return IDLegacyTelemetryEvent
}

func (pk *LegacyTelemetryEvent) Marshal(io protocol.IO) {
	io.Varint64(&pk.EntityUniqueID)
	io.Varint32(&pk.EventType)
	io.Bool(&pk.UsePlayerID)
	switch pk.EventType {
	case 0: // Achievement
		x := pk.EventData.(Achievement)
		x.Marshal(io)
	case 1: // Interaction
		x := pk.EventData.(Interaction)
		x.Marshal(io)
	case 2: // PortalCreated
		x := pk.EventData.(PortalCreated)
		x.Marshal(io)
	case 3: // PortalUsed
		x := pk.EventData.(PortalUsed)
		x.Marshal(io)
	case 4: // MobKilled
		x := pk.EventData.(MobKilled)
		x.Marshal(io)
	case 5: // CauldronUsed
		x := pk.EventData.(CauldronUsed)
		x.Marshal(io)
	case 6: // PlayerDied
		x := pk.EventData.(PlayerDied)
		x.Marshal(io)
	case 7: // BossKilled
		x := pk.EventData.(BossKilled)
		x.Marshal(io)
	case 8: // SlashCommand
		x := pk.EventData.(SlashCommand)
		x.Marshal(io)
	case 9: // MobBorn
		x := pk.EventData.(MobBorn)
		x.Marshal(io)
	case 10: // POICauldronUsed
		x := pk.EventData.(POICauldronUsed)
		x.Marshal(io)
	case 11: // ComposterUsed
		x := pk.EventData.(ComposterUsed)
		x.Marshal(io)
	case 12: // BellUsed
		x := pk.EventData.(BellUsed)
		x.Marshal(io)
	case 13: // ActorDefinition
		x := pk.EventData.(ActorDefinition)
		x.Marshal(io)
	case 14: // RaidUpdate
		x := pk.EventData.(RaidUpdate)
		x.Marshal(io)
	case 15: // TargetBlockHit
		x := pk.EventData.(TargetBlockHit)
		x.Marshal(io)
	case 16: // PiglinBarter
		x := pk.EventData.(PiglinBarter)
		x.Marshal(io)
	case 17: // PlayerWaxedOrUnwaxedCopper
		x := pk.EventData.(PlayerWaxedOrUnwaxedCopper)
		x.Marshal(io)
	case 18: // CodeBuilderRuntimeAction
		x := pk.EventData.(CodeBuilderRuntimeAction)
		x.Marshal(io)
	case 19: // CodeBuilderScoreboard
		x := pk.EventData.(CodeBuilderScoreboard)
		x.Marshal(io)
	case 20: // ItemUsed
		x := pk.EventData.(ItemUsed)
		x.Marshal(io)
	}
}
