// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          123 (0x7B)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LevelSoundEvent Level Sound Event
type LevelSoundEvent struct {
	SoundEvent string
	Position mgl32.Vec3
	Data int32
	ActorIdentifier string
	IsBaby bool
	IsGlobal bool
	ActorUniqueID int64
	FireAtPosition mgl32.Vec3
}

// ID ...
func (*LevelSoundEvent) ID() uint32 {
	return IDLevelSoundEvent
}

func (pk *LevelSoundEvent) Marshal(io protocol.IO) {
	io.String(&pk.SoundEvent)
	io.Vec3(&pk.Position)
	io.Varint32(&pk.Data)
	io.String(&pk.ActorIdentifier)
	io.Bool(&pk.IsBaby)
	io.Bool(&pk.IsGlobal)
	io.Int64(&pk.ActorUniqueID)
	io.Vec3(&pk.FireAtPosition)
}
