// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          25 (0x19)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LevelEvent Splash Potions, weather events, global pause, simlock commands, oh my!
type LevelEvent struct {
	EventID int32
	// Position Note about Event ID: Legacy particles use the @enums.html#Particle Type@ enum |ed with ParticleLegacyEvent(0x4000)
	Position mgl32.Vec3
	Data int32
}

// ID ...
func (*LevelEvent) ID() uint32 {
	return IDLevelEvent
}

func (pk *LevelEvent) Marshal(io protocol.IO) {
	io.Varint32(&pk.EventID)
	io.Vec3(&pk.Position)
	io.Varint32(&pk.Data)
}
