// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          124 (0x7C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LevelEventGeneric LevelEventGenericPacket
type LevelEventGeneric struct {
	EventID int32
	Data map[string]any
}

// ID ...
func (*LevelEventGeneric) ID() uint32 {
	return IDLevelEventGeneric
}

func (pk *LevelEventGeneric) Marshal(io protocol.IO) {
	io.Varint32(&pk.EventID)
	io.NBT(&pk.Data, nbt.NetworkLittleEndian)
}
