// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          124 (0x7C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// LevelEventGeneric LevelEventGenericPacket
type LevelEventGeneric struct {
	EventID int32
	Data any
}

// ID ...
func (*LevelEventGeneric) ID() uint32 {
	return IDLevelEventGeneric
}

// Marshal ...
func (pk *LevelEventGeneric) Marshal(io protocol.IO) {
	io.Varint32(&pk.EventID)
	// TODO: Data - unresolved reference: #/definitions/3172631924
}
