// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          341 (0x155)

package packet

import (
	"github.com/google/uuid"
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// WorldPosition is a nested struct used in the packet.
type WorldPosition struct {
	// Position The Vec3 position in the dimension.
	Position mgl32.Vec3
	// DimensionType The runtime id of the dimension.
	DimensionType int32
}

func (x *WorldPosition) Marshal(r protocol.IO) {
	r.Vec3(&x.Position)
	r.Varint32(&x.DimensionType)
}

// ServerWaypointPayload is a nested struct used in the packet.
type ServerWaypointPayload struct {
	// UpdateFlag A bitflag uint used to map to which of the optional values in this payload should be updated.
	UpdateFlag uint32
	// IsVisible Boolean used to tell the client if the Waypoint is visible or not.
	IsVisible bool
	// WorldPosition The Vec3 position and DimensionID of the waypoint.
	WorldPosition WorldPosition
	// TexturePath The path used to select which texture the Waypoint displays.
	TexturePath string
	// IconSize The size of the icon that is displayed. Default: [1, 1]
	IconSize mgl32.Vec2
	// Color The color that the client with tint the waypoint texture.
	Color int32
	// ClientPositionAuthority Boolean that if true the client will update the Waypoints position per tick.
	ClientPositionAuthority bool
	// ActorUniqueID The entity id that Waypoint will be attached to.
	ActorUniqueID int64
}

func (x *ServerWaypointPayload) Marshal(r protocol.IO) {
	r.Uint32(&x.UpdateFlag)
	r.Bool(&x.IsVisible)
	protocol.Single(r, &x.WorldPosition)
	r.String(&x.TexturePath)
	r.Vec2(&x.IconSize)
	r.Int32(&x.Color)
	r.Bool(&x.ClientPositionAuthority)
	r.Varint64(&x.ActorUniqueID)
}

// LocatorBarWaypointPayload is a nested struct used in the packet.
type LocatorBarWaypointPayload struct {
	// GroupHandle WaypointGroup::WaypointHandle used to lookup Waypoint in WaypointGroups.
	GroupHandle uuid.UUID
	// ServerWaypointPayload Contains the optional data to add or update the client Waypoint.
	ServerWaypointPayload ServerWaypointPayload
	// ActionFlag Enum which defines if the Waypoint operation was an add, remove or update.
	ActionFlag uint8
}

func (x *LocatorBarWaypointPayload) Marshal(r protocol.IO) {
	r.UUID(&x.GroupHandle)
	protocol.Single(r, &x.ServerWaypointPayload)
	r.Uint8(&x.ActionFlag)
}

// LocatorBar Syncs LocatorBar changes on the server with the client.
type LocatorBar struct {
	// Waypoints Array of LocatorBarWaypointPayload's
	Waypoints []LocatorBarWaypointPayload
}

// ID ...
func (*LocatorBar) ID() uint32 {
	return IDLocatorBar
}

func (pk *LocatorBar) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.Waypoints)
}
