// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          1 (0x01)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Login Sent once from client to server at login. About 100k.
type Login struct {
	ClientNetworkVersion int32
	// ConnectionRequest see @connectionRequest.html#diagram@
	ConnectionRequest string
}

// ID ...
func (*Login) ID() uint32 {
	return IDLogin
}

// Marshal ...
func (pk *Login) Marshal(io protocol.IO) {
	io.Int32(&pk.ClientNetworkVersion)
	io.String(&pk.ConnectionRequest)
}
