// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          1 (0x01)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Login Sent once from client to server at login. About 100k.
type Login struct {
	ClientNetworkVersion int32
	// ConnectionRequest see @connectionRequest.html#diagram@
	ConnectionRequest string
}

// ID ...
func (*Login) ID() uint32 {
	return IDLogin
}

func (pk *Login) Marshal(io protocol.IO) {
	io.Int32(&pk.ClientNetworkVersion)
	io.String(&pk.ConnectionRequest)
}
