// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          131 (0x83)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MapCreateLockedCopy This is fired when the user locks a map item utilizing the Cartography Table in game.
type MapCreateLockedCopy struct {
	// OriginalMapID Id of the map being locked.
	OriginalMapID int64
	// NewMapID Id that the new map should have.
	NewMapID int64
}

// ID ...
func (*MapCreateLockedCopy) ID() uint32 {
	return IDMapCreateLockedCopy
}

func (pk *MapCreateLockedCopy) Marshal(io protocol.IO) {
	io.Varint64(&pk.OriginalMapID)
	io.Varint64(&pk.NewMapID)
}
