// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          68 (0x44)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AnonymousNamespaceMapInfoRequestPacketAnonClientPixelsProxy is a nested struct used in the packet.
type AnonymousNamespaceMapInfoRequestPacketAnonClientPixelsProxy struct {
	Pixel uint32
	Index uint16
}

func (x *AnonymousNamespaceMapInfoRequestPacketAnonClientPixelsProxy) Marshal(r protocol.IO) {
	r.Uint32(&x.Pixel)
	r.Uint16(&x.Index)
}

// MapInfoRequest In the case of the client being unable to find map data for a map item it sends a uuid for a map to the server.
type MapInfoRequest struct {
	MapUniqueID int64
	// ClientPixelsList These are sent from the client to tell the Server map about terrain pixels it doesn't know about
	ClientPixelsList []AnonymousNamespaceMapInfoRequestPacketAnonClientPixelsProxy
}

// ID ...
func (*MapInfoRequest) ID() uint32 {
	return IDMapInfoRequest
}

func (pk *MapInfoRequest) Marshal(io protocol.IO) {
	io.Varint64(&pk.MapUniqueID)
	protocol.Slice(io, &pk.ClientPixelsList)
}
