// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          28 (0x1C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	MobEffectPacketPayloadEventInvalid = iota
	MobEffectPacketPayloadEventAdd
	MobEffectPacketPayloadEventUpdate
	MobEffectPacketPayloadEventRemove
)

// MobEffect Mob Effect
type MobEffect struct {
	EntityRuntimeID uint64
	EventType uint8
	EffectID int32
	EffectAmplifier int32
	ShowParticles bool
	EffectDurationTicks int32
	// Tick If this packet is referring to the player or a client predicted vehicle they are in control of, this should be the most recently processed PlayerInputTick from their PlayerAuthInputPacket. Otherwise zero.
	Tick uint64
	// Ambient If the effect is considered ambient (like the ones applied by Beacons or Conduits)
	Ambient bool
}

// ID ...
func (*MobEffect) ID() uint32 {
	return IDMobEffect
}

func (pk *MobEffect) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	io.Uint8(&pk.EventType)
	io.Varint32(&pk.EffectID)
	io.Varint32(&pk.EffectAmplifier)
	io.Bool(&pk.ShowParticles)
	io.Varint32(&pk.EffectDurationTicks)
	io.Varuint64(&pk.Tick)
	io.Bool(&pk.Ambient)
}
