// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          31 (0x1F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MobEquipment Mob Equipment. Changes to any mob's held/offhand item are fired from server to client with this packet. Clients also send this to the server when their held slot or its contents change.
type MobEquipment struct {
	// EntityRuntimeID Runtime ID of the mob or player whose equipment is changing.
	EntityRuntimeID uint64
	// Item The item stack being equipped. Send an empty descriptor to indicate no item.
	Item any
	// Slot The inventory slot index the item occupies within the container.
	Slot uint8
	// SelectedSlot The hotbar slot that is currently selected by the player. Matches Slot for non-player mobs.
	SelectedSlot uint8
	// ContainerID Identifies which container the item belongs to, e.g. inventory or offhand.
	ContainerID uint8
}

// ID ...
func (*MobEquipment) ID() uint32 {
	return IDMobEquipment
}

// Marshal ...
func (pk *MobEquipment) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	// TODO: Item - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	io.Uint8(&pk.Slot)
	io.Uint8(&pk.SelectedSlot)
	io.Uint8(&pk.ContainerID)
}
