// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          32 (0x20)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MobArmorEquipment Mob Armor Equipment
type MobArmorEquipment struct {
	EntityRuntimeID uint64
	Head any
	Torso any
	Legs any
	Feet any
	Body any
}

// ID ...
func (*MobArmorEquipment) ID() uint32 {
	return IDMobArmorEquipment
}

// Marshal ...
func (pk *MobArmorEquipment) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	// TODO: Head - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	// TODO: Torso - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	// TODO: Legs - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	// TODO: Feet - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
	// TODO: Body - multi-property reference to cerealizer<NetworkItemStackDescriptor>::SerializedData
}
