// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          100 (0x64)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ModalFormRequest Modal Form Request
type ModalFormRequest struct {
	FormID uint32
	FormUIJSON string
}

// ID ...
func (*ModalFormRequest) ID() uint32 {
	return IDModalFormRequest
}

func (pk *ModalFormRequest) Marshal(io protocol.IO) {
	io.Varuint32(&pk.FormID)
	io.String(&pk.FormUIJSON)
}
