// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          101 (0x65)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ModalFormCancelReasonUserClosed = iota
	ModalFormCancelReasonUserBusy
)

// ModalFormResponse Fired in response to third party server request to show the custom UI screen.
type ModalFormResponse struct {
	FormID uint32
	JSONResponse []byte
	FormCancelReason uint8
}

// ID ...
func (*ModalFormResponse) ID() uint32 {
	return IDModalFormResponse
}

func (pk *ModalFormResponse) Marshal(io protocol.IO) {
	io.Varuint32(&pk.FormID)
	io.ByteSlice(&pk.JSONResponse)
	io.Uint8(&pk.FormCancelReason)
}
