// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          101 (0x65)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ModalFormCancelReasonUserClosed = iota
	ModalFormCancelReasonUserBusy
)

// ModalFormResponse Fired in response to third party server request to show the custom UI screen.
type ModalFormResponse struct {
	FormID uint32
	JSONResponse []byte
	FormCancelReason uint8
}

// ID ...
func (*ModalFormResponse) ID() uint32 {
	return IDModalFormResponse
}

// Marshal ...
func (pk *ModalFormResponse) Marshal(io protocol.IO) {
	io.Varuint32(&pk.FormID)
	io.ByteSlice(&pk.JSONResponse)
	io.Uint8(&pk.FormCancelReason)
}
