// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          318 (0x13E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	MovementEffectTypeGlideBoost = iota
	MovementEffectTypeDolphinBoost
	MovementEffectTypeGeyserBoost
)

// MovementEffect These packets are sent to the client to update specific MovementEffects
type MovementEffect struct {
	EntityRuntimeID uint64
	EffectID int32
	EffectDuration int32
	// Tick If this packet is referring to the player or a client predicted vehicle they are in control of, this should be the most recently processed PlayerInputTick from their PlayerAuthInputPacket. Otherwise zero.
	Tick uint64
}

// ID ...
func (*MovementEffect) ID() uint32 {
	return IDMovementEffect
}

// Marshal ...
func (pk *MovementEffect) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	io.Varint32(&pk.EffectID)
	io.Varint32(&pk.EffectDuration)
	io.Varuint64(&pk.Tick)
}
