// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          18 (0x12)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClassMoveActorAbsoluteData is a nested struct used in the packet.
type ClassMoveActorAbsoluteData struct {
	// ActorRuntimeID The runtime id of the actor being moved
	ActorRuntimeID uint64
	// Header Header bits describing the status of the actor, see additional documentation in the supplemental documentation folder
	Header uint8
	// Position X/Y/Z coordinates of the position of the actor, each being a 4 byte float
	Position mgl32.Vec3
	// RotationX The X rotation of the actor stored as an integer
	RotationX uint8
	// RotationY The Y rotation of the actor stored as an integer
	RotationY uint8
	// RotationYHead The head rotation of the actor if and only if it's a Mob type, stored as an integer
	RotationYHead uint8
}

func (x *ClassMoveActorAbsoluteData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ActorRuntimeID)
	r.Uint8(&x.Header)
	r.Vec3(&x.Position)
	r.Uint8(&x.RotationX)
	r.Uint8(&x.RotationY)
	r.Uint8(&x.RotationYHead)
}

// MoveActorAbsolute This is used primarily for motion updates of all actors from server to client.
type MoveActorAbsolute struct {
	// MoveData This is client bound for normal actor motion updates.
	MoveData ClassMoveActorAbsoluteData
}

// ID ...
func (*MoveActorAbsolute) ID() uint32 {
	return IDMoveActorAbsolute
}

func (pk *MoveActorAbsolute) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.MoveData)
}
