// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          139 (0x8B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	MultiplayerSettingsPacketTypeEnableMultiplayer = iota
	MultiplayerSettingsPacketTypeDisableMultiplayer
	MultiplayerSettingsPacketTypeRefreshJoincode
)

// MultiplayerSettings Syncs multiplayer settings
type MultiplayerSettings struct {
	PacketType int32
}

// ID ...
func (*MultiplayerSettings) ID() uint32 {
	return IDMultiplayerSettings
}

// Marshal ...
func (pk *MultiplayerSettings) Marshal(io protocol.IO) {
	io.Varint32(&pk.PacketType)
}
