// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          139 (0x8B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	MultiplayerSettingsPacketTypeEnableMultiplayer = iota
	MultiplayerSettingsPacketTypeDisableMultiplayer
	MultiplayerSettingsPacketTypeRefreshJoincode
)

// MultiplayerSettings Syncs multiplayer settings
type MultiplayerSettings struct {
	PacketType int32
}

// ID ...
func (*MultiplayerSettings) ID() uint32 {
	return IDMultiplayerSettings
}

func (pk *MultiplayerSettings) Marshal(io protocol.IO) {
	io.Varint32(&pk.PacketType)
}
