// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          115 (0x73)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// NetworkStackLatency Ping Packet
type NetworkStackLatency struct {
	CreationTime uint64
	IsFromServer bool
}

// ID ...
func (*NetworkStackLatency) ID() uint32 {
	return IDNetworkStackLatency
}

// Marshal ...
func (pk *NetworkStackLatency) Marshal(io protocol.IO) {
	io.Uint64(&pk.CreationTime)
	io.Bool(&pk.IsFromServer)
}
