// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          115 (0x73)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// NetworkStackLatency Ping Packet
type NetworkStackLatency struct {
	CreationTime uint64
	IsFromServer bool
}

// ID ...
func (*NetworkStackLatency) ID() uint32 {
	return IDNetworkStackLatency
}

func (pk *NetworkStackLatency) Marshal(io protocol.IO) {
	io.Uint64(&pk.CreationTime)
	io.Bool(&pk.IsFromServer)
}
