// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          143 (0x8F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PacketCompressionAlgorithmZLib = iota
	PacketCompressionAlgorithmSnappy
	PacketCompressionAlgorithmNone
)

// NetworkSettings Sends tunable options from host to client (compression threshold and algorithm)
type NetworkSettings struct {
	// CompressionThreshold Determines the smallest size of raw network payload to compress. NOTE: 0 is disable compression, 1 is compress everything 1 byte or larger (so everything)
	CompressionThreshold uint16
	CompressionAlgorithm uint16
	ClientThrottleEnabled bool
	ClientThrottleThreshold uint8
	ClientThrottleScalar float32
}

// ID ...
func (*NetworkSettings) ID() uint32 {
	return IDNetworkSettings
}

func (pk *NetworkSettings) Marshal(io protocol.IO) {
	io.Uint16(&pk.CompressionThreshold)
	io.Uint16(&pk.CompressionAlgorithm)
	io.Bool(&pk.ClientThrottleEnabled)
	io.Uint8(&pk.ClientThrottleThreshold)
	io.Float32(&pk.ClientThrottleScalar)
}
