// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          121 (0x79)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// NetworkChunkPublisherUpdate Tells clients to update the chunk view for the local player.
type NetworkChunkPublisherUpdate struct {
	NewPositionForView protocol.BlockPos
	NewRadiusForView uint32
	ServerBuiltChunksList []protocol.ChunkPos
}

// ID ...
func (*NetworkChunkPublisherUpdate) ID() uint32 {
	return IDNetworkChunkPublisherUpdate
}

func (pk *NetworkChunkPublisherUpdate) Marshal(io protocol.IO) {
	io.BlockPos(&pk.NewPositionForView)
	io.Varuint32(&pk.NewRadiusForView)
	protocol.FuncSlice(io, &pk.ServerBuiltChunksList, io.ChunkPos)
}
