// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          169 (0xA9)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	NPCDialogueActionTypeOpen = iota
	NPCDialogueActionTypeClose
)

// NPCDialogue Sent from the server to client when remote firing an NPC dialogue window for a client
type NPCDialogue struct {
	// NPCIDRawID The ActorUniqueID of the NPC being remote fired
	NPCIDRawID uint64
	NPCDialogueActionType int32
	// Dialogue The text to be displayed to the client
	Dialogue string
	// SceneName The scene the data has been pulled from for the client to reference
	SceneName string
	// NPCName The name of the NPC to be displayed to the client
	NPCName string
	// ActionJSON The JSON string of the buttons/actions the server can perform. The server is still authoritative on what actions can be performed
	ActionJSON string
}

// ID ...
func (*NPCDialogue) ID() uint32 {
	return IDNPCDialogue
}

func (pk *NPCDialogue) Marshal(io protocol.IO) {
	io.Uint64(&pk.NPCIDRawID)
	io.Varint32(&pk.NPCDialogueActionType)
	io.String(&pk.Dialogue)
	io.String(&pk.SceneName)
	io.String(&pk.NPCName)
	io.String(&pk.ActionJSON)
}
