// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          98 (0x62)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	NPCRequestPacketPayloadRequestTypeSetActions = iota
	NPCRequestPacketPayloadRequestTypeExecuteAction
	NPCRequestPacketPayloadRequestTypeExecuteClosingCommands
	NPCRequestPacketPayloadRequestTypeSetName
	NPCRequestPacketPayloadRequestTypeSetSkin
	NPCRequestPacketPayloadRequestTypeSetInteractText
	NPCRequestPacketPayloadRequestTypeExecuteOpeningCommands
)

// NPCRequest Used for a number of interactions with the NPC Component
type NPCRequest struct {
	NPCRuntimeID uint64
	RequestType uint8
	Actions string
	ActionIndex uint8
	SceneName string
}

// ID ...
func (*NPCRequest) ID() uint32 {
	return IDNPCRequest
}

func (pk *NPCRequest) Marshal(io protocol.IO) {
	io.Varuint64(&pk.NPCRuntimeID)
	io.Uint8(&pk.RequestType)
	io.String(&pk.Actions)
	io.Uint8(&pk.ActionIndex)
	io.String(&pk.SceneName)
}
