// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          130 (0x82)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// OnScreenTextureAnimation On-Screen Texture Animation
type OnScreenTextureAnimation struct {
	EffectID uint32
}

// ID ...
func (*OnScreenTextureAnimation) ID() uint32 {
	return IDOnScreenTextureAnimation
}

func (pk *OnScreenTextureAnimation) Marshal(io protocol.IO) {
	io.Uint32(&pk.EffectID)
}
