// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          303 (0x12F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// OpenSign Sent from the server so that the client knows to open the sign screen.
type OpenSign struct {
	Pos protocol.BlockPos
	IsFrontSide bool
}

// ID ...
func (*OpenSign) ID() uint32 {
	return IDOpenSign
}

// Marshal ...
func (pk *OpenSign) Marshal(io protocol.IO) {
	io.BlockPos(&pk.Pos)
	io.Bool(&pk.IsFrontSide)
}
