// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          303 (0x12F)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// OpenSign Sent from the server so that the client knows to open the sign screen.
type OpenSign struct {
	Pos protocol.BlockPos
	IsFrontSide bool
}

// ID ...
func (*OpenSign) ID() uint32 {
	return IDOpenSign
}

func (pk *OpenSign) Marshal(io protocol.IO) {
	io.UBlockPos(&pk.Pos)
	io.Bool(&pk.IsFrontSide)
}
