// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          156 (0x9C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PacketViolationSeverityUnknown = iota
	PacketViolationSeverityWarning
	PacketViolationSeverityFinalWarning
	PacketViolationSeverityTerminatingConnection
)

const (
	PacketViolationTypeUnknown = iota
	PacketViolationTypePacketMalformed
)

// PacketViolationWarning This is sent when the client detects a malformed packet
type PacketViolationWarning struct {
	ViolationType int32
	ViolationSeverity int32
	ViolationPacketID int32
	ViolationContext string
}

// ID ...
func (*PacketViolationWarning) ID() uint32 {
	return IDPacketViolationWarning
}

// Marshal ...
func (pk *PacketViolationWarning) Marshal(io protocol.IO) {
	io.Varint32(&pk.ViolationType)
	io.Varint32(&pk.ViolationSeverity)
	io.Varint32(&pk.ViolationPacketID)
	io.String(&pk.ViolationContext)
}
