// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          342 (0x156)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerPartyInfo is a nested struct used in the packet.
type PlayerPartyInfo struct {
	PartyID string
	IsPartyLeader bool
}

func (x *PlayerPartyInfo) Marshal(r protocol.IO) {
	r.String(&x.PartyID)
	r.Bool(&x.IsPartyLeader)
}

// PartyChanged Sent by the client to provide additional client metadata.
type PartyChanged struct {
	PartyInfo PlayerPartyInfo
}

// ID ...
func (*PartyChanged) ID() uint32 {
	return IDPartyChanged
}

func (pk *PartyChanged) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.PartyInfo)
}
