// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          350 (0x15E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PartyDestinationCookieResponse Sent by the client to the server with a party destination cookie response.
type PartyDestinationCookieResponse struct {
	Cookie string
	Accepted bool
}

// ID ...
func (*PartyDestinationCookieResponse) ID() uint32 {
	return IDPartyDestinationCookieResponse
}

func (pk *PartyDestinationCookieResponse) Marshal(io protocol.IO) {
	io.String(&pk.Cookie)
	io.Bool(&pk.Accepted)
}
