// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          99 (0x63)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PhotoTypePortfolio = iota
	PhotoTypePhotoItem
	PhotoTypeBook
)

// PhotoTransfer There is a camera item in EDU and they can use it to take screenshots and add them to a scrapbook.
type PhotoTransfer struct {
	PhotoName string
	PhotoData string
	BookID string
	Type uint8
	SourceType uint8
	OwnerID int64
	NewPhotoName string
}

// ID ...
func (*PhotoTransfer) ID() uint32 {
	return IDPhotoTransfer
}

func (pk *PhotoTransfer) Marshal(io protocol.IO) {
	io.String(&pk.PhotoName)
	io.String(&pk.PhotoData)
	io.String(&pk.BookID)
	io.Uint8(&pk.Type)
	io.Uint8(&pk.SourceType)
	io.Int64(&pk.OwnerID)
	io.String(&pk.NewPhotoName)
}
