// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          36 (0x24)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PlayerActionTypeUnknown = iota
	PlayerActionTypeStartDestroyBlock
	PlayerActionTypeAbortDestroyBlock
	PlayerActionTypeStopDestroyBlock
	PlayerActionTypeGetUpdatedBlock
	PlayerActionTypeDropItem
	PlayerActionTypeStartSleeping
	PlayerActionTypeStopSleeping
	PlayerActionTypeRespawn
	PlayerActionTypeStartJump
	PlayerActionTypeStartSprinting
	PlayerActionTypeStopSprinting
	PlayerActionTypeStartSneaking
	PlayerActionTypeStopSneaking
	PlayerActionTypeCreativeDestroyBlock
	PlayerActionTypeChangeDimensionAck
	PlayerActionTypeStartGliding
	PlayerActionTypeStopGliding
	PlayerActionTypeDenyDestroyBlock
	PlayerActionTypeCrackBlock
	PlayerActionTypeChangeSkin
	PlayerActionTypeUpdatedEnchantingSeed
	PlayerActionTypeStartSwimming
	PlayerActionTypeStopSwimming
	PlayerActionTypeStartSpinAttack
	PlayerActionTypeStopSpinAttack
	PlayerActionTypeInteractWithBlock
	PlayerActionTypePredictDestroyBlock
	PlayerActionTypeContinueDestroyBlock
	PlayerActionTypeStartItemUseOn
	PlayerActionTypeStopItemUseOn
	PlayerActionTypeHandledTeleport
	PlayerActionTypeMissedSwing
	PlayerActionTypeStartCrawling
	PlayerActionTypeStopCrawling
	PlayerActionTypeStartFlying
	PlayerActionTypeStopFlying
	PlayerActionTypeClientAckServerData
	PlayerActionTypeStartUsingItem
	PlayerActionTypeCount
)

// PlayerAction Sent from the client whenever the player performs an action (dashing, un-dashing, use an item, mine/hit, use a block, etc).
type PlayerAction struct {
	PlayerRuntimeID uint64
	Action int32
	BlockPosition protocol.BlockPos
	ResultPos protocol.BlockPos
	Face int32
}

// ID ...
func (*PlayerAction) ID() uint32 {
	return IDPlayerAction
}

func (pk *PlayerAction) Marshal(io protocol.IO) {
	io.Varuint64(&pk.PlayerRuntimeID)
	io.Varint32(&pk.Action)
	io.UBlockPos(&pk.BlockPosition)
	io.UBlockPos(&pk.ResultPos)
	io.Varint32(&pk.Face)
}
