// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          160 (0xA0)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerFog Player Fog Packet
type PlayerFog struct {
	// FogStack Stack of fog effects created by /fog command. Fog effects are strings from /fog command
	FogStack []string
}

// ID ...
func (*PlayerFog) ID() uint32 {
	return IDPlayerFog
}

func (pk *PlayerFog) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.FogStack, io.String)
}
