// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          324 (0x144)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// StartVideoCapture is a nested struct used in the packet.
type StartVideoCapture struct {
	FrameRate uint32
	FilePrefix string
}

func (x *StartVideoCapture) Marshal(r protocol.IO) {
	r.Uint32(&x.FrameRate)
	r.String(&x.FilePrefix)
}

// PlayerVideoCapture Used by a test command to start/stop video capture
type PlayerVideoCapture struct {
	StartVideoCapture protocol.Optional[any]
	StopVideoCapture protocol.Optional[any]
}

// ID ...
func (*PlayerVideoCapture) ID() uint32 {
	return IDPlayerVideoCapture
}

// Marshal ...
func (pk *PlayerVideoCapture) Marshal(io protocol.IO) {
	// TODO: StartVideoCapture - oneOf variants generated but control field unknown
	// Variants: StartVideoCapture(0)
	// TODO: StopVideoCapture - oneOf variants generated but control field unknown
	// Variants: StartVideoCapture(0)
}
