// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          2 (0x02)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PlayStatusLoginSuccess = iota
	PlayStatusLoginfailedClientold
	PlayStatusLoginfailedServerold
	PlayStatusPlayerSpawn
	PlayStatusLoginfailedInvalidtenant
	PlayStatusLoginfailedEditionmismatchedutovanilla
	PlayStatusLoginfailedEditionmismatchvanillatoedu
	PlayStatusLoginfailedServerfullsubclient
	PlayStatusLoginfailedEditormismatcheditortovanilla
	PlayStatusLoginfailedEditormismatchvanillatoeditor
)

// PlayStatus Describes the login status of the player
type PlayStatus struct {
	Status int32
}

// ID ...
func (*PlayStatus) ID() uint32 {
	return IDPlayStatus
}

func (pk *PlayStatus) Marshal(io protocol.IO) {
	io.Int32(&pk.Status)
}
