// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          86 (0x56)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlaySound This packet is only used via command or script event. This is for 3rd party content.
type PlaySound struct {
	Name string
	Position protocol.BlockPos
	Volume float32
	Pitch float32
	ServerSoundHandle protocol.Optional[uint64]
}

// ID ...
func (*PlaySound) ID() uint32 {
	return IDPlaySound
}

// Marshal ...
func (pk *PlaySound) Marshal(io protocol.IO) {
	io.String(&pk.Name)
	io.BlockPos(&pk.Position)
	io.Float32(&pk.Volume)
	io.Float32(&pk.Pitch)
	protocol.OptionalFunc(io, &pk.ServerSoundHandle, io.Uint64)
}
