// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          48 (0x30)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerHotbar Sent from the server when the player uses pick block on actors or blocks, in addition to the player uses the clear, give, or replace item command or if the serverplayer uses _sendAdditionalLevelData().
type PlayerHotbar struct {
	SelectedSlot uint32
	ContainerID uint8
	ShouldSelectSlot bool
}

// ID ...
func (*PlayerHotbar) ID() uint32 {
	return IDPlayerHotbar
}

// Marshal ...
func (pk *PlayerHotbar) Marshal(io protocol.IO) {
	io.Varuint32(&pk.SelectedSlot)
	io.Uint8(&pk.ContainerID)
	io.Bool(&pk.ShouldSelectSlot)
}
