// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          93 (0x5D)

package packet

import (
	"github.com/google/uuid"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SkinImage is a nested struct used in the packet.
type SkinImage struct {
	Width uint32
	Height uint32
	ImageBytes []uint8
}

func (x *SkinImage) Marshal(r protocol.IO) {
	r.Uint32(&x.Width)
	r.Uint32(&x.Height)
	protocol.FuncSlice(r, &x.ImageBytes, r.Uint8)
}

// AnimatedImageData is a nested struct used in the packet.
type AnimatedImageData struct {
	SkinImage SkinImage
	AnimatedTextureType uint32
	Frames float32
	AnimationExpression uint32
}

func (x *AnimatedImageData) Marshal(r protocol.IO) {
	protocol.Single(r, &x.SkinImage)
	r.Varuint32(&x.AnimatedTextureType)
	r.Float32(&x.Frames)
	r.Varuint32(&x.AnimationExpression)
}

// SerializedPersonaPieceHandle is a nested struct used in the packet.
type SerializedPersonaPieceHandle struct {
	PieceID string
	PieceType uint32
	PackID uuid.UUID
	IsDefaultPiece bool
	ProductID string
}

func (x *SerializedPersonaPieceHandle) Marshal(r protocol.IO) {
	r.String(&x.PieceID)
	r.Uint32(&x.PieceType)
	r.UUID(&x.PackID)
	r.Bool(&x.IsDefaultPiece)
	r.String(&x.ProductID)
}

// PieceTintColorsEntry is a nested struct used in the packet.
type PieceTintColorsEntry struct {
	Key uint32
	Value any
}

func (x *PieceTintColorsEntry) Marshal(r protocol.IO) {
	r.Uint32(&x.Key)
	// TODO: Value - type mapping not found
}

// SerializedSkin is a nested struct used in the packet.
type SerializedSkin struct {
	ID string
	PlayFabID string
	ResourcePatch string
	ImageData SkinImage
	AnimatedImageData []AnimatedImageData
	CapeImageData SkinImage
	GeometryData []byte
	GeometryDataMinEngineVersion string
	AnimationData string
	CapeID string
	FullID string
	ArmSize uint8
	SkinColor int32
	PersonaPieces []SerializedPersonaPieceHandle
	PieceTintColors []PieceTintColorsEntry
	IsPremium bool
	IsPersona bool
	IsPersonaCapeOnClassicSkin bool
	IsPrimaryUser bool
	OverridesPlayerAppearance bool
	TrustedSkinFlag any
}

func (x *SerializedSkin) Marshal(r protocol.IO) {
	r.String(&x.ID)
	r.String(&x.PlayFabID)
	r.String(&x.ResourcePatch)
	protocol.Single(r, &x.ImageData)
	protocol.Slice(r, &x.AnimatedImageData)
	protocol.Single(r, &x.CapeImageData)
	r.ByteSlice(&x.GeometryData)
	r.String(&x.GeometryDataMinEngineVersion)
	r.String(&x.AnimationData)
	r.String(&x.CapeID)
	r.String(&x.FullID)
	r.Uint8(&x.ArmSize)
	r.Int32(&x.SkinColor)
	protocol.Slice(r, &x.PersonaPieces)
	protocol.Slice(r, &x.PieceTintColors)
	r.Bool(&x.IsPremium)
	r.Bool(&x.IsPersona)
	r.Bool(&x.IsPersonaCapeOnClassicSkin)
	r.Bool(&x.IsPrimaryUser)
	r.Bool(&x.OverridesPlayerAppearance)
	// TODO: TrustedSkinFlag - type mapping not found
}

// PlayerSkin Used when the player changes their skin
type PlayerSkin struct {
	// UUID The player's UUID
	UUID uuid.UUID
	// SerializedSkin The player's serialized skin
	SerializedSkin SerializedSkin
	// LocalizedNewSkinName The player's localized new skin name
	LocalizedNewSkinName string
	// LocalizedOldSkinName The player's localized old skin name
	LocalizedOldSkinName string
}

// ID ...
func (*PlayerSkin) ID() uint32 {
	return IDPlayerSkin
}

func (pk *PlayerSkin) Marshal(io protocol.IO) {
	io.UUID(&pk.UUID)
	protocol.Single(io, &pk.SerializedSkin)
	io.String(&pk.LocalizedNewSkinName)
	io.String(&pk.LocalizedOldSkinName)
}
