// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          149 (0x95)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ArmorSlotAndDamagePair is a nested struct used in the packet.
type ArmorSlotAndDamagePair struct {
	ArmorSlot int32
	Damage int16
}

func (x *ArmorSlotAndDamagePair) Marshal(r protocol.IO) {
	r.Varint32(&x.ArmorSlot)
	r.Int16(&x.Damage)
}

// PlayerArmorDamage Sent from server whenever the player's armor takes damage.
type PlayerArmorDamage struct {
	ArmorSlotAndDamagePairs []ArmorSlotAndDamagePair
}

// ID ...
func (*PlayerArmorDamage) ID() uint32 {
	return IDPlayerArmorDamage
}

func (pk *PlayerArmorDamage) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.ArmorSlotAndDamagePairs)
}
