// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          146 (0x92)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ItemEnchants is a nested struct used in the packet.
type ItemEnchants struct {
	Slot int32
	ItemEnchants []any
}

func (x *ItemEnchants) Marshal(r protocol.IO) {
	r.Int32(&x.Slot)
	// TODO: ItemEnchants - type mapping not found
}

// ItemEnchantOption is a nested struct used in the packet.
type ItemEnchantOption struct {
	Cost uint8
	Enchants ItemEnchants
	EnchantName string
	EnchantNetID uint32
}

func (x *ItemEnchantOption) Marshal(r protocol.IO) {
	r.Uint8(&x.Cost)
	protocol.Single(r, &x.Enchants)
	r.String(&x.EnchantName)
	r.Varuint32(&x.EnchantNetID)
}

// PlayerEnchantOptions Sends the of new Enchanting options from the server when a player right clicks the enchantment table.
type PlayerEnchantOptions struct {
	// Options The array of enchantment options available to the player
	Options []ItemEnchantOption
}

// ID ...
func (*PlayerEnchantOptions) ID() uint32 {
	return IDPlayerEnchantOptions
}

func (pk *PlayerEnchantOptions) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.Options)
}
