// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          160 (0xA0)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerFog Player Fog Packet
type PlayerFog struct {
	// FogStack Stack of fog effects created by /fog command. Fog effects are strings from /fog command
	FogStack []string
}

// ID ...
func (*PlayerFog) ID() uint32 {
	return IDPlayerFog
}

// Marshal ...
func (pk *PlayerFog) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.FogStack, io.String)
}
