// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          86 (0x56)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlaySound This packet is only used via command or script event. This is for 3rd party content.
type PlaySound struct {
	Name string
	Position protocol.BlockPos
	Volume float32
	Pitch float32
}

// ID ...
func (*PlaySound) ID() uint32 {
	return IDPlaySound
}

func (pk *PlaySound) Marshal(io protocol.IO) {
	io.String(&pk.Name)
	io.UBlockPos(&pk.Position)
	io.Float32(&pk.Volume)
	io.Float32(&pk.Pitch)
}
