// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          306 (0x132)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerToggleCrafterSlotRequest PlayerToggleCrafterSlotRequestPacket
type PlayerToggleCrafterSlotRequest struct {
	PosX int32
	PosY int32
	PosZ int32
	SlotIndex uint8
	IsDisabled bool
}

// ID ...
func (*PlayerToggleCrafterSlotRequest) ID() uint32 {
	return IDPlayerToggleCrafterSlotRequest
}

// Marshal ...
func (pk *PlayerToggleCrafterSlotRequest) Marshal(io protocol.IO) {
	io.Int32(&pk.PosX)
	io.Int32(&pk.PosY)
	io.Int32(&pk.PosZ)
	io.Uint8(&pk.SlotIndex)
	io.Bool(&pk.IsDisabled)
}
