// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          176 (0xB0)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PlayerStartItemCooldown Player Start Item Cooldown
type PlayerStartItemCooldown struct {
	ItemCategory string
	DurationTicks int32
}

// ID ...
func (*PlayerStartItemCooldown) ID() uint32 {
	return IDPlayerStartItemCooldown
}

// Marshal ...
func (pk *PlayerStartItemCooldown) Marshal(io protocol.IO) {
	io.String(&pk.ItemCategory)
	io.Varint32(&pk.DurationTicks)
}
