// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          154 (0x9A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PositionTrackingDBClientRequestPacketPayloadActionQuery = iota
)

// PositionTrackingDBClientRequest Position Tracking DB Client Request
type PositionTrackingDBClientRequest struct {
	Action uint8
	TrackingID int32
}

// ID ...
func (*PositionTrackingDBClientRequest) ID() uint32 {
	return IDPositionTrackingDBClientRequest
}

func (pk *PositionTrackingDBClientRequest) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varint32(&pk.TrackingID)
}
