// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          153 (0x99)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PositionTrackingDBServerBroadcastPacketPayloadActionUpdate = iota
	PositionTrackingDBServerBroadcastPacketPayloadActionDestroy
	PositionTrackingDBServerBroadcastPacketPayloadActionNotFound
)

// PositionTrackingDBServerBroadcast Server to client packet for server authoratative runtime database (with persistent LevelStorage backup) designed primarily to track lodestone stuff. See Position Tracking DB Notes.md in bedrock-docs.
type PositionTrackingDBServerBroadcast struct {
	Action uint8
	TrackingID int32
	// PositionTrackingData CompoundTag for record key: version (byte) id (string) positions (list of (int, int, int)) dimension (int) status (byte, record status enum)
	PositionTrackingData map[string]any
}

// ID ...
func (*PositionTrackingDBServerBroadcast) ID() uint32 {
	return IDPositionTrackingDBServerBroadcast
}

func (pk *PositionTrackingDBServerBroadcast) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varint32(&pk.TrackingID)
	io.NBT(&pk.PositionTrackingData, nbt.NetworkLittleEndian)
}
