// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          154 (0x9A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PositionTrackingDBClientRequestPacketPayloadActionQuery = iota
)

// PositionTrackingDBClientRequest Position Tracking DB Client Request
type PositionTrackingDBClientRequest struct {
	Action uint8
	TrackingID int32
}

// ID ...
func (*PositionTrackingDBClientRequest) ID() uint32 {
	return IDPositionTrackingDBClientRequest
}

// Marshal ...
func (pk *PositionTrackingDBClientRequest) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varint32(&pk.TrackingID)
}
