// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          153 (0x99)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PositionTrackingDBServerBroadcastPacketPayloadActionUpdate = iota
	PositionTrackingDBServerBroadcastPacketPayloadActionDestroy
	PositionTrackingDBServerBroadcastPacketPayloadActionNotFound
)

// PositionTrackingDBServerBroadcast Server to client packet for server authoratative runtime database (with persistent LevelStorage backup) designed primarily to track lodestone stuff. See Position Tracking DB Notes.md in bedrock-docs.
type PositionTrackingDBServerBroadcast struct {
	Action uint8
	TrackingID int32
	// PositionTrackingData CompoundTag for record key: version (byte) id (string) positions (list of (int, int, int)) dimension (int) status (byte, record status enum)
	PositionTrackingData any
}

// ID ...
func (*PositionTrackingDBServerBroadcast) ID() uint32 {
	return IDPositionTrackingDBServerBroadcast
}

func (pk *PositionTrackingDBServerBroadcast) Marshal(io protocol.IO) {
	io.Uint8(&pk.Action)
	io.Varint32(&pk.TrackingID)
	// TODO: PositionTrackingData - unresolved reference: #/definitions/3172631924
}
