// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          92 (0x5C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PurchaseReceipt Sent from client to server
type PurchaseReceipt struct {
	// PurchaseReceipts Purchase Receipts
	PurchaseReceipts []string
}

// ID ...
func (*PurchaseReceipt) ID() uint32 {
	return IDPurchaseReceipt
}

func (pk *PurchaseReceipt) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.PurchaseReceipts, io.String)
}
