// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          92 (0x5C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PurchaseReceipt Sent from client to server
type PurchaseReceipt struct {
	// PurchaseReceipts Purchase Receipts
	PurchaseReceipts []string
}

// ID ...
func (*PurchaseReceipt) ID() uint32 {
	return IDPurchaseReceipt
}

func (pk *PurchaseReceipt) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.PurchaseReceipts, io.String)
}
