// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          305 (0x131)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RefreshEntitlements Refresh Entitlements
type RefreshEntitlements struct {
}

// ID ...
func (*RefreshEntitlements) ID() uint32 {
	return IDRefreshEntitlements
}

func (pk *RefreshEntitlements) Marshal(io protocol.IO) {
}
