// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          305 (0x131)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RefreshEntitlements Refresh Entitlements
type RefreshEntitlements struct {
}

// ID ...
func (*RefreshEntitlements) ID() uint32 {
	return IDRefreshEntitlements
}

func (pk *RefreshEntitlements) Marshal(io protocol.IO) {
}
