// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          167 (0xA7)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RemoveVolumeEntity Sends a volume entity to be removed from server to client.
type RemoveVolumeEntity struct {
	EntityNetworkID uint32
	DimensionType int32
}

// ID ...
func (*RemoveVolumeEntity) ID() uint32 {
	return IDRemoveVolumeEntity
}

func (pk *RemoveVolumeEntity) Marshal(io protocol.IO) {
	io.Varuint32(&pk.EntityNetworkID)
	io.Varint32(&pk.DimensionType)
}
