// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          14 (0x0E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RemoveActor Occasionally, during the server player tick some time is taken to remove nearby actors from the world.
type RemoveActor struct {
	EntityUniqueID int64
}

// ID ...
func (*RemoveActor) ID() uint32 {
	return IDRemoveActor
}

func (pk *RemoveActor) Marshal(io protocol.IO) {
	io.Varint64(&pk.EntityUniqueID)
}
