// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          14 (0x0E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RemoveActor Occasionally, during the server player tick some time is taken to remove nearby actors from the world.
type RemoveActor struct {
	EntityUniqueID int64
}

// ID ...
func (*RemoveActor) ID() uint32 {
	return IDRemoveActor
}

func (pk *RemoveActor) Marshal(io protocol.IO) {
	io.Varint64(&pk.EntityUniqueID)
}
