// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          106 (0x6A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RemoveObjective Using the scoreboard command, users can remove objectives that are tracked on the scoreboard.
type RemoveObjective struct {
	ObjectiveName string
}

// ID ...
func (*RemoveObjective) ID() uint32 {
	return IDRemoveObjective
}

func (pk *RemoveObjective) Marshal(io protocol.IO) {
	io.String(&pk.ObjectiveName)
}
