// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          193 (0xC1)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RequestNetworkSettings Requests tunable options from host to client (compression threshold and algorithm).
type RequestNetworkSettings struct {
	ClientNetworkVersion int32
}

// ID ...
func (*RequestNetworkSettings) ID() uint32 {
	return IDRequestNetworkSettings
}

func (pk *RequestNetworkSettings) Marshal(io protocol.IO) {
	io.Int32(&pk.ClientNetworkVersion)
}
