// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          185 (0xB9)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RequestPermissions Sent from client to server. Used to request a new Permissions Levels.
type RequestPermissions struct {
	// TargetPlayerIDRawID mTargetPlayerId is a ActorUniqueID
	TargetPlayerIDRawID int64
	PlayerPermissionLevel int32
	CustomPermissionFlags uint16
}

// ID ...
func (*RequestPermissions) ID() uint32 {
	return IDRequestPermissions
}

func (pk *RequestPermissions) Marshal(io protocol.IO) {
	io.Int64(&pk.TargetPlayerIDRawID)
	io.Varint32(&pk.PlayerPermissionLevel)
	io.Uint16(&pk.CustomPermissionFlags)
}
