// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          184 (0xB8)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	RequestAbilityPacketPayloadTypeUnset = iota
	RequestAbilityPacketPayloadTypeBool
	RequestAbilityPacketPayloadTypeFloat
)

// RequestAbility Sent from client to server. Used to request an ability change.
type RequestAbility struct {
	Ability int32
	ValueType uint8
	Bool bool
	Float float32
}

// ID ...
func (*RequestAbility) ID() uint32 {
	return IDRequestAbility
}

func (pk *RequestAbility) Marshal(io protocol.IO) {
	io.Varint32(&pk.Ability)
	io.Uint8(&pk.ValueType)
	io.Bool(&pk.Bool)
	io.Float32(&pk.Float)
}
