// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          69 (0x45)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// RequestChunkRadius The client can't just change the view radius without the server's approval, otherwise there could be holes on unrendered area.
type RequestChunkRadius struct {
	ChunkRadius int32
	MaxChunkRadius uint8
}

// ID ...
func (*RequestChunkRadius) ID() uint32 {
	return IDRequestChunkRadius
}

func (pk *RequestChunkRadius) Marshal(io protocol.IO) {
	io.Varint32(&pk.ChunkRadius)
	io.Uint8(&pk.MaxChunkRadius)
}
