// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          7 (0x07)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ExperimentToggle is a nested struct used in the packet.
type ExperimentToggle struct {
	Name string
	Enabled bool
}

func (x *ExperimentToggle) Marshal(r protocol.IO) {
	r.String(&x.Name)
	r.Bool(&x.Enabled)
}

// Experiments is a nested struct used in the packet.
type Experiments struct {
	// Toggles Active experiment toggles followed by always-on toggles
	Toggles []ExperimentToggle
	// ExperimentsEverToggled Whether any experiments have ever been toggled in this world
	ExperimentsEverToggled bool
}

func (x *Experiments) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.Toggles)
	r.Bool(&x.ExperimentsEverToggled)
}

// PackInstanceID is a nested struct used in the packet.
type PackInstanceID struct {
	// PackID UUID of the pack
	PackID string
	// Version SemVer version of the pack
	Version string
	SubPackName string
}

func (x *PackInstanceID) Marshal(r protocol.IO) {
	r.String(&x.PackID)
	r.String(&x.Version)
	r.String(&x.SubPackName)
}

// ResourcePackStack Resource Pack Stack
type ResourcePackStack struct {
	TexturePackRequired bool
	// TexturePackList List of texture pack IDs and versions for the resource pack stack
	TexturePackList []PackInstanceID
	// BaseGameVersion For clients to be able to set their stack to the right version
	BaseGameVersion string
	// Experiments Active and always-on experiment toggles
	Experiments Experiments
	// IncludeEditorPacks When connecting to an Editor world, include the vanilla editor packs in the stack
	IncludeEditorPacks bool
}

// ID ...
func (*ResourcePackStack) ID() uint32 {
	return IDResourcePackStack
}

func (pk *ResourcePackStack) Marshal(io protocol.IO) {
	io.Bool(&pk.TexturePackRequired)
	protocol.Slice(io, &pk.TexturePackList)
	io.String(&pk.BaseGameVersion)
	protocol.Single(io, &pk.Experiments)
	io.Bool(&pk.IncludeEditorPacks)
}
