// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          340 (0x154)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ResourcePacksReadyForValidation Used to inform the server that the client has finished loading all resource packs.
type ResourcePacksReadyForValidation struct {
}

// ID ...
func (*ResourcePacksReadyForValidation) ID() uint32 {
	return IDResourcePacksReadyForValidation
}

// Marshal ...
func (pk *ResourcePacksReadyForValidation) Marshal(io protocol.IO) {
}
