// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          82 (0x52)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ResourcePackDataInfo Resource Pack Data Info
type ResourcePackDataInfo struct {
	ResourceName string
	ChunkSize uint32
	NumberOfChunks uint32
	FileSize uint64
	FileHash string
	// IsPremiumPack Do you need an entitlement to use this pack?
	IsPremiumPack bool
	PackType uint8
}

// ID ...
func (*ResourcePackDataInfo) ID() uint32 {
	return IDResourcePackDataInfo
}

func (pk *ResourcePackDataInfo) Marshal(io protocol.IO) {
	io.String(&pk.ResourceName)
	io.Uint32(&pk.ChunkSize)
	io.Uint32(&pk.NumberOfChunks)
	io.Uint64(&pk.FileSize)
	io.String(&pk.FileHash)
	io.Bool(&pk.IsPremiumPack)
	io.Uint8(&pk.PackType)
}
