// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          83 (0x53)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ResourcePackChunkData Resource Pack Chunk Data
type ResourcePackChunkData struct {
	ResourceName string
	ChunkID uint32
	ByteOffset uint64
	ChunkData string
}

// ID ...
func (*ResourcePackChunkData) ID() uint32 {
	return IDResourcePackChunkData
}

// Marshal ...
func (pk *ResourcePackChunkData) Marshal(io protocol.IO) {
	io.String(&pk.ResourceName)
	io.Uint32(&pk.ChunkID)
	io.Uint64(&pk.ByteOffset)
	io.String(&pk.ChunkData)
}
