// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          45 (0x2D)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PlayerRespawnStateSearchingForSpawn = iota
	PlayerRespawnStateReadyToSpawn
	PlayerRespawnStateClientReadyToSpawn
)

// Respawn Sent as a handshake between the client and server to respawn the player.
type Respawn struct {
	Position mgl32.Vec3
	State uint8
	PlayerRuntimeID uint64
}

// ID ...
func (*Respawn) ID() uint32 {
	return IDRespawn
}

func (pk *Respawn) Marshal(io protocol.IO) {
	io.Vec3(&pk.Position)
	io.Uint8(&pk.State)
	io.Varuint64(&pk.PlayerRuntimeID)
}
