// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          177 (0xB1)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ScriptMessage Used to send custom messages between client and server.
type ScriptMessage struct {
	MessageID string
	MessageValue string
}

// ID ...
func (*ScriptMessage) ID() uint32 {
	return IDScriptMessage
}

// Marshal ...
func (pk *ScriptMessage) Marshal(io protocol.IO) {
	io.String(&pk.MessageID)
	io.String(&pk.MessageValue)
}
