// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          177 (0xB1)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ScriptMessage Used to send custom messages between client and server.
type ScriptMessage struct {
	MessageID string
	MessageValue string
}

// ID ...
func (*ScriptMessage) ID() uint32 {
	return IDScriptMessage
}

func (pk *ScriptMessage) Marshal(io protocol.IO) {
	io.String(&pk.MessageID)
	io.String(&pk.MessageValue)
}
