// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          349 (0x15D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	PartyDestinationCookieIntentNotify = iota
	PartyDestinationCookieIntentOptIn
	PartyDestinationCookieIntentOptOut
)

// SendPartyDestinationCookie Sent by the server to a client with a party destination cookie.
type SendPartyDestinationCookie struct {
	Cookie string
	Intent int8
	DestinationName string
}

// ID ...
func (*SendPartyDestinationCookie) ID() uint32 {
	return IDSendPartyDestinationCookie
}

// Marshal ...
func (pk *SendPartyDestinationCookie) Marshal(io protocol.IO) {
	io.String(&pk.Cookie)
	io.Int8(&pk.Intent)
	io.String(&pk.DestinationName)
}
