// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          312 (0x138)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ServerboundLoadingScreenPacketTypeStartLoadingScreen = iota
	ServerboundLoadingScreenPacketTypeEndLoadingScreen
)

// ServerboundLoadingScreen Sent from the client to the server to message to the server about the state of the loading screen.
type ServerboundLoadingScreen struct {
	LoadingScreenPacketType int32
	// LoadingScreenID This will be set if the server gives us a value. If the server doesn't expect this value, then the client will get disconnected.
	LoadingScreenID uint32
}

// ID ...
func (*ServerboundLoadingScreen) ID() uint32 {
	return IDServerboundLoadingScreen
}

// Marshal ...
func (pk *ServerboundLoadingScreen) Marshal(io protocol.IO) {
	io.Varint32(&pk.LoadingScreenPacketType)
	io.Uint32(&pk.LoadingScreenID)
}
