// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          346 (0x15A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ClientStoreEntryPointConfig is a nested struct used in the packet.
type ClientStoreEntryPointConfig struct {
	// StoreID The unique identifier for the store.
	StoreID string
	// StoreName The name of the store.
	StoreName string
}

func (x *ClientStoreEntryPointConfig) Marshal(r protocol.IO) {
	r.String(&x.StoreID)
	r.String(&x.StoreName)
}

// ServerStoreInfo Sent by the server to provide ClientStoreEntryPointConfiguration to the client.
type ServerStoreInfo struct {
	ClientStoreEntryPointConfiguration ClientStoreEntryPointConfig
}

// ID ...
func (*ServerStoreInfo) ID() uint32 {
	return IDServerStoreInfo
}

func (pk *ServerStoreInfo) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.ClientStoreEntryPointConfiguration)
}
