// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          343 (0x157)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	DataDrivenScreenClosedReasonProgrammaticClose = iota
	DataDrivenScreenClosedReasonProgrammaticCloseAll
	DataDrivenScreenClosedReasonClientCanceled
	DataDrivenScreenClosedReasonUserBusy
	DataDrivenScreenClosedReasonInvalidForm
)

// ServerboundDataDrivenScreenClosed Sent from the client to the server when a data driven screen is closed.
type ServerboundDataDrivenScreenClosed struct {
	// FormID The form ID of the screen that was closed.
	FormID protocol.Optional[uint32]
	// CloseReason The reason the screen was closed.
	CloseReason uint8
}

// ID ...
func (*ServerboundDataDrivenScreenClosed) ID() uint32 {
	return IDServerboundDataDrivenScreenClosed
}

func (pk *ServerboundDataDrivenScreenClosed) Marshal(io protocol.IO) {
	protocol.OptionalFunc(io, &pk.FormID, io.Uint32)
	io.Uint8(&pk.CloseReason)
}
