// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          103 (0x67)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerSettingsResponse Server Settings Response
type ServerSettingsResponse struct {
	FormID uint32
	FormUIJSON string
}

// ID ...
func (*ServerSettingsResponse) ID() uint32 {
	return IDServerSettingsResponse
}

func (pk *ServerSettingsResponse) Marshal(io protocol.IO) {
	io.Varuint32(&pk.FormID)
	io.String(&pk.FormUIJSON)
}
