// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          315 (0x13B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerboundDiagnostics Sent from the client to the server IF ProfilerLite is enabled AND the creator toggle for additional client telemetry is enabled AND new telemetry data is ready (every 500 ms).
type ServerboundDiagnostics struct {
	AvgFps float32
	AvgServerSimTickTimeMS float32
	AvgClientSimTickTimeMS float32
	AvgBeginFrameTimeMS float32
	AvgInputTimeMS float32
	AvgRenderTimeMS float32
	AvgEndFrameTimeMS float32
	AvgRemainderTimePercent float32
	AvgUnaccountedTimePercent float32
}

// ID ...
func (*ServerboundDiagnostics) ID() uint32 {
	return IDServerboundDiagnostics
}

func (pk *ServerboundDiagnostics) Marshal(io protocol.IO) {
	io.Float32(&pk.AvgFps)
	io.Float32(&pk.AvgServerSimTickTimeMS)
	io.Float32(&pk.AvgClientSimTickTimeMS)
	io.Float32(&pk.AvgBeginFrameTimeMS)
	io.Float32(&pk.AvgInputTimeMS)
	io.Float32(&pk.AvgRenderTimeMS)
	io.Float32(&pk.AvgEndFrameTimeMS)
	io.Float32(&pk.AvgRemainderTimePercent)
	io.Float32(&pk.AvgUnaccountedTimePercent)
}
