// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          3 (0x03)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerToClientHandshake Server->Client Handshake
type ServerToClientHandshake struct {
	// HandshakeWebToken Base64 encoded JSON Web Token that contains the other relevant client properties. Properties Include: 'salt' = (for use in encryption) The public key used to compute the shared secret for encryption is embedded in the header of the token. It's the signer public key (json value of 'x5u')
	HandshakeWebToken string
}

// ID ...
func (*ServerToClientHandshake) ID() uint32 {
	return IDServerToClientHandshake
}

func (pk *ServerToClientHandshake) Marshal(io protocol.IO) {
	io.String(&pk.HandshakeWebToken)
}
