// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          315 (0x13B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// EntityDiagnosticTimingInfo is a nested struct used in the packet.
type EntityDiagnosticTimingInfo struct {
	DisplayName string
	Entity string
	TimeInNS uint64
	PercentOfTotal uint8
}

func (x *EntityDiagnosticTimingInfo) Marshal(r protocol.IO) {
	r.String(&x.DisplayName)
	r.String(&x.Entity)
	r.Uint64(&x.TimeInNS)
	r.Uint8(&x.PercentOfTotal)
}

// MemoryCategoryCounter is a nested struct used in the packet.
type MemoryCategoryCounter struct {
	Category uint8
	CurrentBytes uint64
}

func (x *MemoryCategoryCounter) Marshal(r protocol.IO) {
	r.Uint8(&x.Category)
	r.Uint64(&x.CurrentBytes)
}

// SystemDiagnosticTimingInfo is a nested struct used in the packet.
type SystemDiagnosticTimingInfo struct {
	DisplayName string
	SystemIndex uint64
	TimeInNS uint64
	PercentOfTotal uint8
}

func (x *SystemDiagnosticTimingInfo) Marshal(r protocol.IO) {
	r.String(&x.DisplayName)
	r.Uint64(&x.SystemIndex)
	r.Uint64(&x.TimeInNS)
	r.Uint8(&x.PercentOfTotal)
}

// WhiskerScopeDataSummary is a nested struct used in the packet.
type WhiskerScopeDataSummary struct {
	Label string
	Indentation string
	TotalHighCostNS uint64
	TotalMidCostNS uint64
	TotalLowCostNS uint64
}

func (x *WhiskerScopeDataSummary) Marshal(r protocol.IO) {
	r.String(&x.Label)
	r.String(&x.Indentation)
	r.Uint64(&x.TotalHighCostNS)
	r.Uint64(&x.TotalMidCostNS)
	r.Uint64(&x.TotalLowCostNS)
}

// ServerboundDiagnostics Sent from the client to the server IF ProfilerLite is enabled AND the creator toggle for additional client telemetry is enabled AND new telemetry data is ready (every 500 ms).
type ServerboundDiagnostics struct {
	AvgFps float32
	AvgServerSimTickTimeMS float32
	AvgClientSimTickTimeMS float32
	AvgBeginFrameTimeMS float32
	AvgInputTimeMS float32
	AvgRenderTimeMS float32
	AvgEndFrameTimeMS float32
	AvgRemainderTimePercent float32
	AvgUnaccountedTimePercent float32
	MemoryCategoryValues []MemoryCategoryCounter
	EntityDiagnostics []EntityDiagnosticTimingInfo
	SystemDiagnostics []SystemDiagnosticTimingInfo
	WhiskerScopes []WhiskerScopeDataSummary
}

// ID ...
func (*ServerboundDiagnostics) ID() uint32 {
	return IDServerboundDiagnostics
}

func (pk *ServerboundDiagnostics) Marshal(io protocol.IO) {
	io.Float32(&pk.AvgFps)
	io.Float32(&pk.AvgServerSimTickTimeMS)
	io.Float32(&pk.AvgClientSimTickTimeMS)
	io.Float32(&pk.AvgBeginFrameTimeMS)
	io.Float32(&pk.AvgInputTimeMS)
	io.Float32(&pk.AvgRenderTimeMS)
	io.Float32(&pk.AvgEndFrameTimeMS)
	io.Float32(&pk.AvgRemainderTimePercent)
	io.Float32(&pk.AvgUnaccountedTimePercent)
	protocol.Slice(io, &pk.MemoryCategoryValues)
	protocol.Slice(io, &pk.EntityDiagnostics)
	protocol.Slice(io, &pk.SystemDiagnostics)
	protocol.Slice(io, &pk.WhiskerScopes)
}
