// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          102 (0x66)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerSettingsRequest Sent during the initialization of world settings on the client.
type ServerSettingsRequest struct {
}

// ID ...
func (*ServerSettingsRequest) ID() uint32 {
	return IDServerSettingsRequest
}

// Marshal ...
func (pk *ServerSettingsRequest) Marshal(io protocol.IO) {
}
