// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          332 (0x14C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// DataStoreUpdate is a nested struct used in the packet.
type DataStoreUpdate struct {
	DataStoreName string
	// Property The name of the property in the data store that has changed
	Property string
	// Path The path through the property that needs updating
	Path string
	// Data The value that is updating
	Data any
	// UpdateCount The number of times this property has updated
	UpdateCount uint32
}

func (x *DataStoreUpdate) Marshal(r protocol.IO) {
	r.String(&x.DataStoreName)
	r.String(&x.Property)
	r.String(&x.Path)
	switch val := x.Data.(type) {
	case float32:
		var typeID uint32 = 0
		r.Uint32(&typeID)
		r.Float32(&val)
	case bool:
		var typeID uint32 = 1
		r.Uint32(&typeID)
		r.Bool(&val)
	}
	r.Uint32(&x.UpdateCount)
}

// ServerboundDataStore Applies a single update to the server data store from the client.
type ServerboundDataStore struct {
	// Update The update data
	Update DataStoreUpdate
}

// ID ...
func (*ServerboundDataStore) ID() uint32 {
	return IDServerboundDataStore
}

func (pk *ServerboundDataStore) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.Update)
}
