// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          192 (0xC0)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerStats Used to send performance and other valuable stats back to the client
type ServerStats struct {
	ServerTime float32
	NetworkTime float32
}

// ID ...
func (*ServerStats) ID() uint32 {
	return IDServerStats
}

// Marshal ...
func (pk *ServerStats) Marshal(io protocol.IO) {
	io.Float32(&pk.ServerTime)
	io.Float32(&pk.NetworkTime)
}
