// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          102 (0x66)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerSettingsRequest Sent during the initialization of world settings on the client.
type ServerSettingsRequest struct {
}

// ID ...
func (*ServerSettingsRequest) ID() uint32 {
	return IDServerSettingsRequest
}

func (pk *ServerSettingsRequest) Marshal(io protocol.IO) {
}
