// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          329 (0x149)

package packet

import (
	"github.com/google/uuid"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ServerboundPackSettingChange Sent from the client to the server when players change Pack Settings (pack UI).
type ServerboundPackSettingChange struct {
	// PackID The UUID of the pack whose setting is being changed.
	PackID uuid.UUID
	// PackSettingName The name of the setting being changed.
	PackSettingName string
	// PackSettingValue The value of the setting being changed.
	PackSettingValue any
}

// ID ...
func (*ServerboundPackSettingChange) ID() uint32 {
	return IDServerboundPackSettingChange
}

func (pk *ServerboundPackSettingChange) Marshal(io protocol.IO) {
	io.UUID(&pk.PackID)
	io.String(&pk.PackSettingName)
	// TODO: PackSettingValue - oneOf variants generated but control field unknown
	// Variants: (0), (1), (2)
}
