// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          347 (0x15B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// PresenceConfig is a nested struct used in the packet.
type PresenceConfig struct {
	// ExperienceName Name of the experience.
	ExperienceName string
	// WorldName Name of the world.
	WorldName string
	// RichPresenceID Optional rich presence ID to override client-driven rich presence.
	RichPresenceID string
}

func (x *PresenceConfig) Marshal(r protocol.IO) {
	r.String(&x.ExperienceName)
	r.String(&x.WorldName)
	r.String(&x.RichPresenceID)
}

// ServerPresenceInfo Sent by the server to provide PresenceConfiguration to the client.
type ServerPresenceInfo struct {
	PresenceConfiguration PresenceConfig
}

// ID ...
func (*ServerPresenceInfo) ID() uint32 {
	return IDServerPresenceInfo
}

func (pk *ServerPresenceInfo) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.PresenceConfiguration)
}
