// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          59 (0x3B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetCommandsEnabled This is used by the world settings screen, cheats, EDU builds for teachers, and various other places to enable cheats/commands
type SetCommandsEnabled struct {
	CommandsEnabled bool
}

// ID ...
func (*SetCommandsEnabled) ID() uint32 {
	return IDSetCommandsEnabled
}

func (pk *SetCommandsEnabled) Marshal(io protocol.IO) {
	io.Bool(&pk.CommandsEnabled)
}
