// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          113 (0x71)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetLocalPlayerAsInitialized Set Local Player As Initialized
type SetLocalPlayerAsInitialized struct {
	PlayerID uint64
}

// ID ...
func (*SetLocalPlayerAsInitialized) ID() uint32 {
	return IDSetLocalPlayerAsInitialized
}

// Marshal ...
func (pk *SetLocalPlayerAsInitialized) Marshal(io protocol.IO) {
	io.Varuint64(&pk.PlayerID)
}
