// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          59 (0x3B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetCommandsEnabled This is used by the world settings screen, cheats, EDU builds for teachers, and various other places to enable cheats/commands
type SetCommandsEnabled struct {
	CommandsEnabled bool
}

// ID ...
func (*SetCommandsEnabled) ID() uint32 {
	return IDSetCommandsEnabled
}

// Marshal ...
func (pk *SetCommandsEnabled) Marshal(io protocol.IO) {
	io.Bool(&pk.CommandsEnabled)
}
