// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          307 (0x133)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// InventoryOptions is a nested struct used in the packet.
type InventoryOptions struct {
	LeftInventoryTab int32
	RightInventoryTab int32
	Filtering bool
	LayoutInv int32
	LayoutCraft int32
}

func (x *InventoryOptions) Marshal(r protocol.IO) {
	r.Varint32(&x.LeftInventoryTab)
	r.Varint32(&x.RightInventoryTab)
	r.Bool(&x.Filtering)
	r.Varint32(&x.LayoutInv)
	r.Varint32(&x.LayoutCraft)
}

// SetPlayerInventoryOptions SetPlayerInventoryOptionsPacket
type SetPlayerInventoryOptions struct {
	InventoryOptions InventoryOptions
}

// ID ...
func (*SetPlayerInventoryOptions) ID() uint32 {
	return IDSetPlayerInventoryOptions
}

// Marshal ...
func (pk *SetPlayerInventoryOptions) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.InventoryOptions)
}
