// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          43 (0x2B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SpawnPositionTypePlayerRespawn = iota
	SpawnPositionTypeWorldSpawn
)

// SetSpawnPosition When a player logs in or the SetWorldSpawnCommand is used this is sent from the server to the client. Does not change when using a bed, that is a separate packet (RespawnPacket)
type SetSpawnPosition struct {
	SpawnPositionType int32
	BlockPosition protocol.BlockPos
	DimensionType int32
	SpawnBlockPos protocol.BlockPos
}

// ID ...
func (*SetSpawnPosition) ID() uint32 {
	return IDSetSpawnPosition
}

func (pk *SetSpawnPosition) Marshal(io protocol.IO) {
	io.Varint32(&pk.SpawnPositionType)
	io.BlockPos(&pk.BlockPosition)
	io.Varint32(&pk.DimensionType)
	io.BlockPos(&pk.SpawnBlockPos)
}
