// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          88 (0x58)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SetTitlePacketTitleTypeClear = iota
	SetTitlePacketTitleTypeReset
	SetTitlePacketTitleTypeTitle
	SetTitlePacketTitleTypeSubtitle
	SetTitlePacketTitleTypeActionbar
	SetTitlePacketTitleTypeTimes
	SetTitlePacketTitleTypeTitleTextObject
	SetTitlePacketTitleTypeSubtitleTextObject
	SetTitlePacketTitleTypeActionbarTextObject
)

// SetTitle Used by 3rd party content for the purpose of showing ui banners
type SetTitle struct {
	TitleType int32
	TitleText string
	FadeInTime int32
	StayTime int32
	FadeOutTime int32
	XUID string
	PlatformOnlineID string
	FilteredTitleMessage string
}

// ID ...
func (*SetTitle) ID() uint32 {
	return IDSetTitle
}

func (pk *SetTitle) Marshal(io protocol.IO) {
	io.Varint32(&pk.TitleType)
	io.String(&pk.TitleText)
	io.Varint32(&pk.FadeInTime)
	io.Varint32(&pk.StayTime)
	io.Varint32(&pk.FadeOutTime)
	io.String(&pk.XUID)
	io.String(&pk.PlatformOnlineID)
	io.String(&pk.FilteredTitleMessage)
}
