// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          96 (0x60)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ActorTypeUndefined = iota
	ActorTypeMob
	ActorTypePathfinderMob
	ActorTypeMonster
	ActorTypeAnimal
	ActorTypeTamableAnimal
	ActorTypeAmbient
	ActorTypeUndeadMob
	ActorTypeZombieMonster
	ActorTypeArthropod
	ActorTypeMinecart
	ActorTypeSkeletonMonster
	ActorTypeEquineAnimal
	ActorTypeProjectile
	ActorTypeAbstractArrow
	ActorTypeWaterAnimal
	ActorTypeVillagerBase
	ActorTypeChicken
	ActorTypeCow
	ActorTypePig
	ActorTypeSheep
	ActorTypeWolf
	ActorTypeVillager
	ActorTypeMushroomCow
	ActorTypeSquid
	ActorTypeRabbit
	ActorTypeBat
	ActorTypeIronGolem
	ActorTypeSnowGolem
	ActorTypeOcelot
	ActorTypeHorse
	ActorTypePolarBear
	ActorTypeLlama
	ActorTypeParrot
	ActorTypeDolphin
	ActorTypeDonkey
	ActorTypeMule
	ActorTypeSkeletonHorse
	ActorTypeZombieHorse
	ActorTypeZombie
	ActorTypeCreeper
	ActorTypeSkeleton
	ActorTypeSpider
	ActorTypePigZombie
	ActorTypeSlime
	ActorTypeEnderMan
	ActorTypeSilverfish
	ActorTypeCaveSpider
	ActorTypeGhast
	ActorTypeLavaSlime
	ActorTypeBlaze
	ActorTypeZombieVillager
	ActorTypeWitch
	ActorTypeStray
	ActorTypeHusk
	ActorTypeWitherSkeleton
	ActorTypeGuardian
	ActorTypeElderGuardian
	ActorTypeNpc
	ActorTypeWitherBoss
	ActorTypeDragon
	ActorTypeShulker
	ActorTypeEndermite
	ActorTypeAgent
	ActorTypeVindicator
	ActorTypePhantom
	ActorTypeIllagerBeast
	ActorTypeArmorStand
	ActorTypeTripodCamera
	ActorTypePlayer
	ActorTypeItemEntity
	ActorTypePrimedTnt
	ActorTypeFallingBlock
	ActorTypeMovingBlock
	ActorTypeExperiencePotion
	ActorTypeExperience
	ActorTypeEyeOfEnder
	ActorTypeEnderCrystal
	ActorTypeFireworksRocket
	ActorTypeTrident
	ActorTypeTurtle
	ActorTypeCat
	ActorTypeShulkerBullet
	ActorTypeFishingHook
	ActorTypeChalkboard
	ActorTypeDragonFireball
	ActorTypeArrow
	ActorTypeSnowball
	ActorTypeThrownEgg
	ActorTypePainting
	ActorTypeLargeFireball
	ActorTypeThrownPotion
	ActorTypeEnderpearl
	ActorTypeLeashKnot
	ActorTypeWitherSkull
	ActorTypeBoatRideable
	ActorTypeWitherSkullDangerous
	ActorTypeLightningBolt
	ActorTypeSmallFireball
	ActorTypeAreaEffectCloud
	ActorTypeLingeringPotion
	ActorTypeLlamaSpit
	ActorTypeEvocationFang
	ActorTypeEvocationIllager
	ActorTypeVex
	ActorTypeMinecartRideable
	ActorTypeMinecartHopper
	ActorTypeMinecartTNT
	ActorTypeMinecartChest
	ActorTypeMinecartFurnace
	ActorTypeMinecartCommandBlock
	ActorTypeIceBomb
	ActorTypeBalloon
	ActorTypePufferfish
	ActorTypeSalmon
	ActorTypeDrowned
	ActorTypeTropicalfish
	ActorTypeFish
	ActorTypePanda
	ActorTypePillager
	ActorTypeVillagerV2
	ActorTypeZombieVillagerV2
	ActorTypeShield
	ActorTypeWanderingTrader
	ActorTypeLectern
	ActorTypeElderGuardianGhost
	ActorTypeFox
	ActorTypeBee
	ActorTypePiglin
	ActorTypeHoglin
	ActorTypeStrider
	ActorTypeZoglin
	ActorTypePiglinBrute
	ActorTypeGoat
	ActorTypeGlowSquid
	ActorTypeAxolotl
	ActorTypeWarden
	ActorTypeFrog
	ActorTypeTadpole
	ActorTypeAllay
	ActorTypeChestBoatRideable
	ActorTypeTraderLlama
	ActorTypeCamel
	ActorTypeSniffer
	ActorTypeBreeze
	ActorTypeBreezeWindChargeProjectile
	ActorTypeArmadillo
	ActorTypeWindChargeProjectile
	ActorTypeBogged
	ActorTypeOminousItemSpawner
	ActorTypeCreaking
	ActorTypeHappyGhast
	ActorTypeCopperGolem
	ActorTypeNautilus
	ActorTypeZombieNautilus
	ActorTypeParched
	ActorTypeCamelHusk
)

// SetLastHurtBy Any time a player is hit, the id of the last mob that attacked them is sent to the client
type SetLastHurtBy struct {
	LastHurtBy int32
}

// ID ...
func (*SetLastHurtBy) ID() uint32 {
	return IDSetLastHurtBy
}

func (pk *SetLastHurtBy) Marshal(io protocol.IO) {
	io.Varint32(&pk.LastHurtBy)
}
