// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          62 (0x3E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	GameTypeUndefined = iota
	GameTypeSurvival
	GameTypeCreative
	GameTypeAdventure
	GameTypeDefault
	GameTypeSpectator
	GameTypeWorldDefault
)

// SetPlayerGameType Set Player Game Type
type SetPlayerGameType struct {
	PlayerGameType int32
}

// ID ...
func (*SetPlayerGameType) ID() uint32 {
	return IDSetPlayerGameType
}

func (pk *SetPlayerGameType) Marshal(io protocol.IO) {
	io.Varint32(&pk.PlayerGameType)
}
