// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          40 (0x28)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetActorMotion This is used for the server to set the velocity of a client actor.
type SetActorMotion struct {
	EntityRuntimeID uint64
	Motion mgl32.Vec3
	// Tick If this packet is referring to the player or a client predicted vehicle they are in control of, this should be the most recently processed PlayerInputTick from their PlayerAuthInputPacket. Otherwise zero.
	Tick uint64
}

// ID ...
func (*SetActorMotion) ID() uint32 {
	return IDSetActorMotion
}

func (pk *SetActorMotion) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	io.Vec3(&pk.Motion)
	io.Varuint64(&pk.Tick)
}
