// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          105 (0x69)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetDefaultGameType Same as SetPlayerGameTypePacket & UpdatePlayerGameTypePacket, the only difference is that this changes the default for all clients.
type SetDefaultGameType struct {
	DefaultGameType int32
}

// ID ...
func (*SetDefaultGameType) ID() uint32 {
	return IDSetDefaultGameType
}

func (pk *SetDefaultGameType) Marshal(io protocol.IO) {
	io.Varint32(&pk.DefaultGameType)
}
