// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          42 (0x2A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetHealth This packet is sent to the client when the player is spawned in and when they respawn.
type SetHealth struct {
	Health int32
}

// ID ...
func (*SetHealth) ID() uint32 {
	return IDSetHealth
}

func (pk *SetHealth) Marshal(io protocol.IO) {
	io.Varint32(&pk.Health)
}
