// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          308 (0x134)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	HudVisibilityHide = iota
	HudVisibilityReset
)

// SetHud This packet is only used via the set hud command. This is for 3rd party content.
type SetHud struct {
	HudElement []int32
	HudVisible int32
}

// ID ...
func (*SetHud) ID() uint32 {
	return IDSetHud
}

func (pk *SetHud) Marshal(io protocol.IO) {
	protocol.FuncSlice(io, &pk.HudElement, io.Int32)
	io.Varint32(&pk.HudVisible)
}
