// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          113 (0x71)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetLocalPlayerAsInitialized Set Local Player As Initialized
type SetLocalPlayerAsInitialized struct {
	PlayerID uint64
}

// ID ...
func (*SetLocalPlayerAsInitialized) ID() uint32 {
	return IDSetLocalPlayerAsInitialized
}

func (pk *SetLocalPlayerAsInitialized) Marshal(io protocol.IO) {
	io.Varuint64(&pk.PlayerID)
}
