// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          10 (0x0A)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetTime Set Time
type SetTime struct {
	Time int32
}

// ID ...
func (*SetTime) ID() uint32 {
	return IDSetTime
}

// Marshal ...
func (pk *SetTime) Marshal(io protocol.IO) {
	io.Varint32(&pk.Time)
}
