// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          41 (0x29)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ActorLink is a nested struct used in the packet.
type ActorLink struct {
	TargetA int64
	TargetB int64
	Type uint8
	Immediate bool
	// PassengerInitiated Whether the link was changed by the passenger
	PassengerInitiated bool
	VehicleAngularVelocity float32
}

func (x *ActorLink) Marshal(r protocol.IO) {
	r.Varint64(&x.TargetA)
	r.Varint64(&x.TargetB)
	r.Uint8(&x.Type)
	r.Bool(&x.Immediate)
	r.Bool(&x.PassengerInitiated)
	r.Float32(&x.VehicleAngularVelocity)
}

// SetActorLink Sent by both client and server, only received by LegacyClientHandler.
type SetActorLink struct {
	Link ActorLink
}

// ID ...
func (*SetActorLink) ID() uint32 {
	return IDSetActorLink
}

func (pk *SetActorLink) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.Link)
}
