// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          107 (0x6B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SetDisplayObjective Sent from the server for 3rd party content to display current objectives and status
type SetDisplayObjective struct {
	DisplaySlotName string
	ObjectiveName string
	ObjectiveDisplayName string
	CriteriaName string
	SortOrder int32
}

// ID ...
func (*SetDisplayObjective) ID() uint32 {
	return IDSetDisplayObjective
}

func (pk *SetDisplayObjective) Marshal(io protocol.IO) {
	io.String(&pk.DisplaySlotName)
	io.String(&pk.ObjectiveName)
	io.String(&pk.ObjectiveDisplayName)
	io.String(&pk.CriteriaName)
	io.Varint32(&pk.SortOrder)
}
