// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          140 (0x8C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SettingsCommand Requests a setting to be changed through commands.
type SettingsCommand struct {
	// Command Command to update setting.
	Command string
	SuppressOutput bool
}

// ID ...
func (*SettingsCommand) ID() uint32 {
	return IDSettingsCommand
}

func (pk *SettingsCommand) Marshal(io protocol.IO) {
	io.String(&pk.Command)
	io.Bool(&pk.SuppressOutput)
}
