// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          140 (0x8C)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SettingsCommand Requests a setting to be changed through commands.
type SettingsCommand struct {
	// Command Command to update setting.
	Command string
	SuppressOutput bool
}

// ID ...
func (*SettingsCommand) ID() uint32 {
	return IDSettingsCommand
}

func (pk *SettingsCommand) Marshal(io protocol.IO) {
	io.String(&pk.Command)
	io.Bool(&pk.SuppressOutput)
}
