// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          104 (0x68)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ShowProfile Show Profile
type ShowProfile struct {
	PlayerXUID string
}

// ID ...
func (*ShowProfile) ID() uint32 {
	return IDShowProfile
}

// Marshal ...
func (pk *ShowProfile) Marshal(io protocol.IO) {
	io.String(&pk.PlayerXUID)
}
