// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          75 (0x4B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ShowCredits Starts on server when the credits screen should pop up.
type ShowCredits struct {
	PlayerRuntimeID uint64
	CreditsState int32
}

// ID ...
func (*ShowCredits) ID() uint32 {
	return IDShowCredits
}

func (pk *ShowCredits) Marshal(io protocol.IO) {
	io.Varuint64(&pk.PlayerRuntimeID)
	io.Varint32(&pk.CreditsState)
}
