// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          75 (0x4B)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ShowCredits Starts on server when the credits screen should pop up.
type ShowCredits struct {
	PlayerRuntimeID uint64
	CreditsState int32
}

// ID ...
func (*ShowCredits) ID() uint32 {
	return IDShowCredits
}

// Marshal ...
func (pk *ShowCredits) Marshal(io protocol.IO) {
	io.Varuint64(&pk.PlayerRuntimeID)
	io.Varint32(&pk.CreditsState)
}
