// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          91 (0x5B)

package packet

import (
	"github.com/google/uuid"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	ShowStoreOfferRedirectTypeMarketplaceOffer = iota
	ShowStoreOfferRedirectTypeDressingRoomOffer
	ShowStoreOfferRedirectTypeThirdPartyServerPage
)

// ShowStoreOffer Used for redirecting a user to the right offer.
type ShowStoreOffer struct {
	// OfferID The offer Id tells which offer to look up when navigating to a marketplace or dressing room.
	OfferID uuid.UUID
	// RedirectType The redirect type determines which page to navigate to.
	RedirectType uint8
}

// ID ...
func (*ShowStoreOffer) ID() uint32 {
	return IDShowStoreOffer
}

func (pk *ShowStoreOffer) Marshal(io protocol.IO) {
	io.UUID(&pk.OfferID)
	io.Uint8(&pk.RedirectType)
}
