// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          104 (0x68)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ShowProfile Show Profile
type ShowProfile struct {
	PlayerXUID string
}

// ID ...
func (*ShowProfile) ID() uint32 {
	return IDShowProfile
}

func (pk *ShowProfile) Marshal(io protocol.IO) {
	io.String(&pk.PlayerXUID)
}
