// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          64 (0x40)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SubtypeUninitializedSubtype = iota
	SubtypeEnableCommands
	SubtypeDisableCommands
	SubtypeUnlockWorldTemplateSettings
)

// SimpleEvent This packet is used for enabling/disabling commands and for unlocking world template settings (both unlocking UI buttons on client and the actual setting on the server).
type SimpleEvent struct {
	Type uint16
}

// ID ...
func (*SimpleEvent) ID() uint32 {
	return IDSimpleEvent
}

func (pk *SimpleEvent) Marshal(io protocol.IO) {
	io.Uint16(&pk.Type)
}
