// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          168 (0xA8)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SimulationTypeGame = iota
	SimulationTypeEditor
	SimulationTypeTest
	SimulationTypeINVALID
)

// SimulationType Sent from the server to the client when setting the simulation type for toolbox mode. (Not yet suported)
type SimulationType struct {
	SimType uint8
}

// ID ...
func (*SimulationType) ID() uint32 {
	return IDSimulationType
}

func (pk *SimulationType) Marshal(io protocol.IO) {
	io.Uint8(&pk.SimType)
}
