// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          66 (0x42)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SpawnExperienceOrb Spawn Experience Orb
type SpawnExperienceOrb struct {
	Position mgl32.Vec3
	XPValue int32
}

// ID ...
func (*SpawnExperienceOrb) ID() uint32 {
	return IDSpawnExperienceOrb
}

func (pk *SpawnExperienceOrb) Marshal(io protocol.IO) {
	io.Vec3(&pk.Position)
	io.Varint32(&pk.XPValue)
}
