// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          118 (0x76)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SpawnParticleEffect Tell client to spawn a particle effect.
type SpawnParticleEffect struct {
	DimensionID uint8
	ActorID int64
	Position mgl32.Vec3
	// EffectName Should be an effect that exists on the client. No-op if the effect doesn't exist.
	EffectName string
	MolangVariables []byte
}

// ID ...
func (*SpawnParticleEffect) ID() uint32 {
	return IDSpawnParticleEffect
}

func (pk *SpawnParticleEffect) Marshal(io protocol.IO) {
	io.Uint8(&pk.DimensionID)
	io.Varint64(&pk.ActorID)
	io.Vec3(&pk.Position)
	io.String(&pk.EffectName)
	io.ByteSlice(&pk.MolangVariables)
}
