// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          87 (0x57)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// StopSound Allows you to stop a sound or all sounds on all clients, only used in a /command
type StopSound struct {
	SoundName string
	StopAllSounds bool
	StopMusic bool
}

// ID ...
func (*StopSound) ID() uint32 {
	return IDStopSound
}

func (pk *StopSound) Marshal(io protocol.IO) {
	io.String(&pk.SoundName)
	io.Bool(&pk.StopAllSounds)
	io.Bool(&pk.StopMusic)
}
