// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          133 (0x85)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	StructureTemplateResponseTypeNone = iota
	StructureTemplateResponseTypeExport
	StructureTemplateResponseTypeQuery
)

// StructureTemplateDataResponse This is used in exporting from load, exporting from save, and querying saved structures from structure blocks.
type StructureTemplateDataResponse struct {
	StructureName string
	StructureNBT map[string]any
	ResponseType uint8
}

// ID ...
func (*StructureTemplateDataResponse) ID() uint32 {
	return IDStructureTemplateDataResponse
}

func (pk *StructureTemplateDataResponse) Marshal(io protocol.IO) {
	io.String(&pk.StructureName)
	io.NBT(&pk.StructureNBT, nbt.NetworkLittleEndian)
	io.Uint8(&pk.ResponseType)
}
