// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          132 (0x84)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	StructureTemplateRequestOperationNone = iota
	StructureTemplateRequestOperationExportFromSaveMode
	StructureTemplateRequestOperationExportFromLoadMode
	StructureTemplateRequestOperationQuerySavedStructure
)

// ClassStructureSettings is a nested struct used in the packet.
type ClassStructureSettings struct {
	StructurePaletteName string
	ShouldIgnoreEntities bool
	ShouldIgnoreBlocks bool
	ShouldAllowNonTickingPlayerAndTickingAreaChunks bool
	StructureSize protocol.BlockPos
	StructureOffset protocol.BlockPos
	// LastEditPlayer Player who last edited the structure block.
	LastEditPlayer int64
	Rotation uint8
	Mirror uint8
	AnimationMode uint8
	AnimationSeconds float32
	IntegrityValue float32
	IntegritySeed uint32
	// RotationPivot Pivot used to rotate a structure around.
	RotationPivot mgl32.Vec3
}

func (x *ClassStructureSettings) Marshal(r protocol.IO) {
	r.String(&x.StructurePaletteName)
	r.Bool(&x.ShouldIgnoreEntities)
	r.Bool(&x.ShouldIgnoreBlocks)
	r.Bool(&x.ShouldAllowNonTickingPlayerAndTickingAreaChunks)
	r.UBlockPos(&x.StructureSize)
	r.UBlockPos(&x.StructureOffset)
	r.Varint64(&x.LastEditPlayer)
	r.Uint8(&x.Rotation)
	r.Uint8(&x.Mirror)
	r.Uint8(&x.AnimationMode)
	r.Float32(&x.AnimationSeconds)
	r.Float32(&x.IntegrityValue)
	r.Uint32(&x.IntegritySeed)
	r.Vec3(&x.RotationPivot)
}

// StructureTemplateDataRequest Used to request structure information from a server.
type StructureTemplateDataRequest struct {
	StructureName string
	StructurePosition protocol.BlockPos
	StructureSettings ClassStructureSettings
	RequestedOperation uint8
}

// ID ...
func (*StructureTemplateDataRequest) ID() uint32 {
	return IDStructureTemplateDataRequest
}

func (pk *StructureTemplateDataRequest) Marshal(io protocol.IO) {
	io.String(&pk.StructureName)
	io.UBlockPos(&pk.StructurePosition)
	protocol.Single(io, &pk.StructureSettings)
	io.Uint8(&pk.RequestedOperation)
}
