// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          133 (0x85)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	StructureTemplateResponseTypeNone = iota
	StructureTemplateResponseTypeExport
	StructureTemplateResponseTypeQuery
)

// StructureTemplateDataResponse This is used in exporting from load, exporting from save, and querying saved structures from structure blocks.
type StructureTemplateDataResponse struct {
	StructureName string
	StructureNBT any
	ResponseType uint8
}

// ID ...
func (*StructureTemplateDataResponse) ID() uint32 {
	return IDStructureTemplateDataResponse
}

func (pk *StructureTemplateDataResponse) Marshal(io protocol.IO) {
	io.String(&pk.StructureName)
	// TODO: StructureNBT - unresolved reference: #/definitions/3172631924
	io.Uint8(&pk.ResponseType)
}
