// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          175 (0xAF)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SubChunkPosOffset is a nested struct used in the packet.
type SubChunkPosOffset struct {
	SubchunkOffsetX int8
	SubchunkOffsetY int8
	SubchunkOffsetZ int8
}

func (x *SubChunkPosOffset) Marshal(r protocol.IO) {
	r.Int8(&x.SubchunkOffsetX)
	r.Int8(&x.SubchunkOffsetY)
	r.Int8(&x.SubchunkOffsetZ)
}

// SubChunkRequest Sent from the client to the server representing a batch of subchunks that the client requests from the server
type SubChunkRequest struct {
	DimensionType int32
	SubChunkPositionOffsetList []SubChunkPosOffset
	CenterPos protocol.SubChunkPos
}

// ID ...
func (*SubChunkRequest) ID() uint32 {
	return IDSubChunkRequest
}

// Marshal ...
func (pk *SubChunkRequest) Marshal(io protocol.IO) {
	io.Varint32(&pk.DimensionType)
	protocol.Slice(io, &pk.SubChunkPositionOffsetList)
	io.SubChunkPos(&pk.CenterPos)
}
