// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          344 (0x158)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SyncWorldClockStateData is a nested struct used in the packet.
type SyncWorldClockStateData struct {
	ClockID uint64
	Time int32
	IsPaused bool
}

func (x *SyncWorldClockStateData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ClockID)
	r.Varint32(&x.Time)
	r.Bool(&x.IsPaused)
}

// SyncStateData is a nested struct used in the packet.
type SyncStateData struct {
	ClockData []SyncWorldClockStateData
}

func (x *SyncStateData) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.ClockData)
}

// TimeMarkerData is a nested struct used in the packet.
type TimeMarkerData struct {
	ID uint64
	Name string
	Time int32
	Period int32
}

func (x *TimeMarkerData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ID)
	r.String(&x.Name)
	r.Varint32(&x.Time)
	r.Int32(&x.Period)
}

// WorldClockData is a nested struct used in the packet.
type WorldClockData struct {
	ID uint64
	Name string
	Time int32
	IsPaused bool
	TimeMarkers []TimeMarkerData
}

func (x *WorldClockData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ID)
	r.String(&x.Name)
	r.Varint32(&x.Time)
	r.Bool(&x.IsPaused)
	protocol.Slice(r, &x.TimeMarkers)
}

// InitializeRegistryData is a nested struct used in the packet.
type InitializeRegistryData struct {
	ClockData []WorldClockData
}

func (x *InitializeRegistryData) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.ClockData)
}

// AddTimeMarkerData is a nested struct used in the packet.
type AddTimeMarkerData struct {
	ClockID uint64
	TimeMarkers []TimeMarkerData
}

func (x *AddTimeMarkerData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ClockID)
	protocol.Slice(r, &x.TimeMarkers)
}

// RemoveTimeMarkerData is a nested struct used in the packet.
type RemoveTimeMarkerData struct {
	ClockID uint64
	TimeMarkerIds []uint64
}

func (x *RemoveTimeMarkerData) Marshal(r protocol.IO) {
	r.Varuint64(&x.ClockID)
	protocol.FuncSlice(r, &x.TimeMarkerIds, r.Uint64)
}

// SyncWorldClocks Initializes and syncs world clocks from the server to clients. (Currently disabled)
type SyncWorldClocks struct {
	// Data Variant data specific to what needs to be synced.
	Data any
}

// ID ...
func (*SyncWorldClocks) ID() uint32 {
	return IDSyncWorldClocks
}

// Marshal ...
func (pk *SyncWorldClocks) Marshal(io protocol.IO) {
	// TODO: Data - oneOf variants generated but control field unknown
	// Variants: SyncStateData(0), InitializeRegistryData(1), AddTimeMarkerData(2), RemoveTimeMarkerData(3)
}
