// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          165 (0xA5)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SyncActorProperty Allows us to synchronize Actor properties across the network.
type SyncActorProperty struct {
	// PropertyData type: actor identifier hash; properties: properties of actor that have been flagged for client sync as a sub-compound tag
	PropertyData any
}

// ID ...
func (*SyncActorProperty) ID() uint32 {
	return IDSyncActorProperty
}

// Marshal ...
func (pk *SyncActorProperty) Marshal(io protocol.IO) {
	// TODO: PropertyData - unresolved reference: #/definitions/3172631924
}
