// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          17 (0x11)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// TakeItemActor A packet sent to the server when deal with picking up an item off the ground in the world.
type TakeItemActor struct {
	ItemRuntimeID uint64
	EntityRuntimeID uint64
}

// ID ...
func (*TakeItemActor) ID() uint32 {
	return IDTakeItemActor
}

func (pk *TakeItemActor) Marshal(io protocol.IO) {
	io.Varuint64(&pk.ItemRuntimeID)
	io.Varuint64(&pk.EntityRuntimeID)
}
