// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          9 (0x09)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MessageOnly is a nested struct used in the packet.
type MessageOnly struct {
	MessageType uint8
	Message string
}

func (x *MessageOnly) Marshal(r protocol.IO) {
	r.Uint8(&x.MessageType)
	r.String(&x.Message)
}

// AuthorAndMessage is a nested struct used in the packet.
type AuthorAndMessage struct {
	MessageType uint8
	PlayerName string
	Message string
}

func (x *AuthorAndMessage) Marshal(r protocol.IO) {
	r.Uint8(&x.MessageType)
	r.String(&x.PlayerName)
	r.String(&x.Message)
}

// MessageAndParams is a nested struct used in the packet.
type MessageAndParams struct {
	MessageType uint8
	Message string
	ParameterList []string
}

func (x *MessageAndParams) Marshal(r protocol.IO) {
	r.Uint8(&x.MessageType)
	r.String(&x.Message)
	protocol.FuncSlice(r, &x.ParameterList, r.String)
}

// Text Represents a text message that needs to be displayed in-game
type Text struct {
	Localize bool
	// Body Message content (variant based on message type)
	Body any
	// XUID Xbox User ID of the message sender
	XUID protocol.Optional[string]
	// PlatformChatID Platform-specific user identifier
	PlatformChatID protocol.Optional[string]
	// FilteredMessage Profanity-filtered version of the message (if applicable)
	FilteredMessage protocol.Optional[string]
}

// ID ...
func (*Text) ID() uint32 {
	return IDText
}

func (pk *Text) Marshal(io protocol.IO) {
	io.Bool(&pk.Localize)
	// TODO: Body - oneOf variants generated but control field unknown
	// Variants: MessageOnly(0), AuthorAndMessage(1), MessageAndParams(2)
	protocol.OptionalFunc(io, &pk.XUID, io.String)
	protocol.OptionalFunc(io, &pk.PlatformChatID, io.String)
	protocol.OptionalFunc(io, &pk.FilteredMessage, io.String)
}
