// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          9 (0x09)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// MessageOnly is a nested struct used in the packet.
type MessageOnly struct {
	Raw uint8
	Tip uint8
	SystemMessage uint8
	TextObjectWhisper uint8
	TextObjectAnnouncement uint8
	TextObject uint8
	MessageType uint8
	Message string
}

func (x *MessageOnly) Marshal(r protocol.IO) {
	r.Uint8(&x.Raw)
	r.Uint8(&x.Tip)
	r.Uint8(&x.SystemMessage)
	r.Uint8(&x.TextObjectWhisper)
	r.Uint8(&x.TextObjectAnnouncement)
	r.Uint8(&x.TextObject)
	r.Uint8(&x.MessageType)
	r.String(&x.Message)
}

// AuthorAndMessage is a nested struct used in the packet.
type AuthorAndMessage struct {
	Chat uint8
	Whisper uint8
	Announcement uint8
	MessageType uint8
	PlayerName string
	Message string
}

func (x *AuthorAndMessage) Marshal(r protocol.IO) {
	r.Uint8(&x.Chat)
	r.Uint8(&x.Whisper)
	r.Uint8(&x.Announcement)
	r.Uint8(&x.MessageType)
	r.String(&x.PlayerName)
	r.String(&x.Message)
}

// MessageAndParams is a nested struct used in the packet.
type MessageAndParams struct {
	Translate uint8
	Popup uint8
	JukeboxPopup uint8
	MessageType uint8
	Message string
	ParameterList []string
}

func (x *MessageAndParams) Marshal(r protocol.IO) {
	r.Uint8(&x.Translate)
	r.Uint8(&x.Popup)
	r.Uint8(&x.JukeboxPopup)
	r.Uint8(&x.MessageType)
	r.String(&x.Message)
	protocol.FuncSlice(r, &x.ParameterList, r.String)
}

// Text Represents a text message that needs to be displayed in-game
type Text struct {
	Localize protocol.Optional[bool]
	// Body Message content (variant based on message type)
	Body any
	// XUID Xbox User ID of the message sender
	XUID string
	// PlatformChatID Platform-specific user identifier
	PlatformChatID string
	// FilteredMessage Profanity-filtered version of the message (if applicable)
	FilteredMessage protocol.Optional[string]
}

// ID ...
func (*Text) ID() uint32 {
	return IDText
}

func (pk *Text) Marshal(io protocol.IO) {
	protocol.OptionalFunc(io, &pk.Localize, io.Bool)
	// TODO: Body - oneOf variants generated but control field unknown
	// Variants: MessageOnly(0), AuthorAndMessage(1), MessageAndParams(2)
	io.String(&pk.XUID)
	io.String(&pk.PlatformChatID)
	protocol.OptionalFunc(io, &pk.FilteredMessage, io.String)
}
