// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          179 (0xB3)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// TickingAreasLoadStatus Used to inform the client that the server is waiting for ticking areas to finish preloading.
type TickingAreasLoadStatus struct {
	WaitingForPreload bool
}

// ID ...
func (*TickingAreasLoadStatus) ID() uint32 {
	return IDTickingAreasLoadStatus
}

func (pk *TickingAreasLoadStatus) Marshal(io protocol.IO) {
	io.Bool(&pk.WaitingForPreload)
}
