// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          186 (0xBA)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ToastRequest Pushes a UI toast message to be displayed by the client
type ToastRequest struct {
	// Title The title to display in the UI toast
	Title string
	// Content The content of the message to display in the UI toast
	Content string
}

// ID ...
func (*ToastRequest) ID() uint32 {
	return IDToastRequest
}

// Marshal ...
func (pk *ToastRequest) Marshal(io protocol.IO) {
	io.String(&pk.Title)
	io.String(&pk.Content)
}
