// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          186 (0xBA)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// ToastRequest Pushes a UI toast message to be displayed by the client
type ToastRequest struct {
	// Title The title to display in the UI toast
	Title string
	// Content The content of the message to display in the UI toast
	Content string
}

// ID ...
func (*ToastRequest) ID() uint32 {
	return IDToastRequest
}

func (pk *ToastRequest) Marshal(io protocol.IO) {
	io.String(&pk.Title)
	io.String(&pk.Content)
}
