// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          85 (0x55)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Transfer Used to kick off transferring the client between online games, or it can be used to cause players to quit the world and rejoin.
type Transfer struct {
	Address string
	Port uint16
	ReloadWorld bool
}

// ID ...
func (*Transfer) ID() uint32 {
	return IDTransfer
}

// Marshal ...
func (pk *Transfer) Marshal(io protocol.IO) {
	io.String(&pk.Address)
	io.Uint16(&pk.Port)
	io.Bool(&pk.ReloadWorld)
}
