// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          85 (0x55)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// Transfer Used to kick off transferring the client between online games, or it can be used to cause players to quit the world and rejoin.
type Transfer struct {
	Address string
	Port uint16
	ReloadWorld bool
}

// ID ...
func (*Transfer) ID() uint32 {
	return IDTransfer
}

func (pk *Transfer) Marshal(io protocol.IO) {
	io.String(&pk.Address)
	io.Uint16(&pk.Port)
	io.Bool(&pk.ReloadWorld)
}
