// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          199 (0xC7)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	UnlockedRecipesPacketPayloadPacketTypeEmpty = iota
	UnlockedRecipesPacketPayloadPacketTypeInitiallyUnlockedRecipes
	UnlockedRecipesPacketPayloadPacketTypeNewlyUnlockedRecipes
	UnlockedRecipesPacketPayloadPacketTypeRemoveUnlockedRecipes
	UnlockedRecipesPacketPayloadPacketTypeRemoveAllUnlockedRecipes
)

// UnlockedRecipes Sent from server to client, for all previously unlocked recipes on load and for any newly unlocked recipes during gameplay.
type UnlockedRecipes struct {
	PacketType uint32
	UnlockedRecipesList []string
}

// ID ...
func (*UnlockedRecipes) ID() uint32 {
	return IDUnlockedRecipes
}

func (pk *UnlockedRecipes) Marshal(io protocol.IO) {
	io.Uint32(&pk.PacketType)
	protocol.FuncSlice(io, &pk.UnlockedRecipesList, io.String)
}
