// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          323 (0x143)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	GraphicsModeSimple = iota
	GraphicsModeFancy
	GraphicsModeAdvanced
	GraphicsModeRayTraced
)

// UpdateClientOptions Sync the player's options (mostly settings) to the server.
type UpdateClientOptions struct {
	// GraphicsModeChange New graphics mode value
	GraphicsModeChange uint8
	// FilterProfanityChange New filter profanity value
	FilterProfanityChange bool
}

// ID ...
func (*UpdateClientOptions) ID() uint32 {
	return IDUpdateClientOptions
}

// Marshal ...
func (pk *UpdateClientOptions) Marshal(io protocol.IO) {
	io.Uint8(&pk.GraphicsModeChange)
	io.Bool(&pk.FilterProfanityChange)
}
