// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          110 (0x6E)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateBlockSynced Used to sync moving blocks with clients so they render correctly
type UpdateBlockSynced struct {
	BlockPosition protocol.BlockPos
	BlockRuntimeID uint32
	Flags uint32
	Layer uint32
	// UniqueActorID Id for the Moving Block Actor
	UniqueActorID uint64
	ActorSyncMessage uint64
}

// ID ...
func (*UpdateBlockSynced) ID() uint32 {
	return IDUpdateBlockSynced
}

func (pk *UpdateBlockSynced) Marshal(io protocol.IO) {
	io.UBlockPos(&pk.BlockPosition)
	io.Varuint32(&pk.BlockRuntimeID)
	io.Varuint32(&pk.Flags)
	io.Varuint32(&pk.Layer)
	io.Varuint64(&pk.UniqueActorID)
	io.Varuint64(&pk.ActorSyncMessage)
}
