// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          81 (0x51)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateEquip Seemingly only used for the Horse Inventory... More specifically when the player opens the horse inventory.
type UpdateEquip struct {
	ContainerID uint8
	Type uint8
	Size int32
	EntityUniqueID int64
	Data any
}

// ID ...
func (*UpdateEquip) ID() uint32 {
	return IDUpdateEquip
}

func (pk *UpdateEquip) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Uint8(&pk.Type)
	io.Varint32(&pk.Size)
	io.Varint64(&pk.EntityUniqueID)
	// TODO: Data - unresolved reference: #/definitions/3172631924
}
