// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          114 (0x72)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SoftEnumUpdateTypeAdd = iota
	SoftEnumUpdateTypeRemove
	SoftEnumUpdateTypeReplace
)

// UpdateSoftEnum This is used for the scoreboard and tag systems (overwhelmingly used by 3rd party content)
type UpdateSoftEnum struct {
	EnumName string
	Values []string
	UpdateType uint8
}

// ID ...
func (*UpdateSoftEnum) ID() uint32 {
	return IDUpdateSoftEnum
}

func (pk *UpdateSoftEnum) Marshal(io protocol.IO) {
	io.String(&pk.EnumName)
	protocol.FuncSlice(io, &pk.Values, io.String)
	io.Uint8(&pk.UpdateType)
}
