// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          323 (0x143)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	GraphicsModeSimple = iota
	GraphicsModeFancy
	GraphicsModeAdvanced
	GraphicsModeRayTraced
)

// UpdateClientOptions Sync the player's options (mostly settings) to the server.
type UpdateClientOptions struct {
	// GraphicsModeChange New graphics mode value
	GraphicsModeChange uint8
}

// ID ...
func (*UpdateClientOptions) ID() uint32 {
	return IDUpdateClientOptions
}

func (pk *UpdateClientOptions) Marshal(io protocol.IO) {
	io.Uint8(&pk.GraphicsModeChange)
}
