// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          21 (0x15)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateBlock Occasional packets sent from server when blocks update or are ticked. (For example, when digging.)
type UpdateBlock struct {
	BlockPosition protocol.BlockPos
	BlockRuntimeID uint32
	Flags uint32
	Layer uint32
}

// ID ...
func (*UpdateBlock) ID() uint32 {
	return IDUpdateBlock
}

func (pk *UpdateBlock) Marshal(io protocol.IO) {
	io.UBlockPos(&pk.BlockPosition)
	io.Varuint32(&pk.BlockRuntimeID)
	io.Varuint32(&pk.Flags)
	io.Varuint32(&pk.Layer)
}
