// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          172 (0xAC)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateSubChunkNetworkBlockInfo is a nested struct used in the packet.
type UpdateSubChunkNetworkBlockInfo struct {
	Pos protocol.BlockPos
	RuntimeID uint32
	UpdateFlags uint32
	SyncMessageEntityUniqueID uint64
	SyncMessageMessage uint32
}

func (x *UpdateSubChunkNetworkBlockInfo) Marshal(r protocol.IO) {
	r.BlockPos(&x.Pos)
	r.Varuint32(&x.RuntimeID)
	r.Varuint32(&x.UpdateFlags)
	r.Varuint64(&x.SyncMessageEntityUniqueID)
	r.Varuint32(&x.SyncMessageMessage)
}

// UpdateSubChunkBlocksChangedInfo is a nested struct used in the packet.
type UpdateSubChunkBlocksChangedInfo struct {
	BlocksChangedStandards []UpdateSubChunkNetworkBlockInfo
	BlocksChangedExtras []UpdateSubChunkNetworkBlockInfo
}

func (x *UpdateSubChunkBlocksChangedInfo) Marshal(r protocol.IO) {
	protocol.Slice(r, &x.BlocksChangedStandards)
	protocol.Slice(r, &x.BlocksChangedExtras)
}

// UpdateSubChunkBlocks Packet sent for every set of blocks changed in a sub chunk every tick.
type UpdateSubChunkBlocks struct {
	SubChunkBlockPosition protocol.BlockPos
	BlocksChanged UpdateSubChunkBlocksChangedInfo
}

// ID ...
func (*UpdateSubChunkBlocks) ID() uint32 {
	return IDUpdateSubChunkBlocks
}

// Marshal ...
func (pk *UpdateSubChunkBlocks) Marshal(io protocol.IO) {
	io.BlockPos(&pk.SubChunkBlockPosition)
	protocol.Single(io, &pk.BlocksChanged)
}
