// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          151 (0x97)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdatePlayerGameType The server will send this back to all clients on receipt of the SetPlayerGameTypePacket so that cached game type and permissions flags in mLevel on all clients is kept up to date.
type UpdatePlayerGameType struct {
	PlayerGameType int32
	TargetPlayer int64
	// Tick Most relevant to supply for transitioning into and out of spectator while in motion
	Tick uint64
}

// ID ...
func (*UpdatePlayerGameType) ID() uint32 {
	return IDUpdatePlayerGameType
}

// Marshal ...
func (pk *UpdatePlayerGameType) Marshal(io protocol.IO) {
	io.Varint32(&pk.PlayerGameType)
	io.Varint64(&pk.TargetPlayer)
	io.Varuint64(&pk.Tick)
}
