// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          196 (0xC4)

package packet

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateClientInputLocks UpdateClientInputLocksPacket
type UpdateClientInputLocks struct {
	InputLockComponentData uint32
	ServerPos mgl32.Vec3
}

// ID ...
func (*UpdateClientInputLocks) ID() uint32 {
	return IDUpdateClientInputLocks
}

func (pk *UpdateClientInputLocks) Marshal(io protocol.IO) {
	io.Varuint32(&pk.InputLockComponentData)
	io.Vec3(&pk.ServerPos)
}
