// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          80 (0x50)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateTrade This is used when the player trades with an npc. This sends all of the updated trade info in one big ol' packet.
type UpdateTrade struct {
	ContainerID uint8
	Type uint8
	Size int32
	TraderTier int32
	EntityUniqueID int64
	LastTradingPlayer int64
	DisplayName string
	UseNewTradeScreen bool
	// UsingEconomyTrade When set to false, it means the packet comes from the old Trade Component.
	UsingEconomyTrade bool
	// Data NBT Data.
	Data any
}

// ID ...
func (*UpdateTrade) ID() uint32 {
	return IDUpdateTrade
}

// Marshal ...
func (pk *UpdateTrade) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Uint8(&pk.Type)
	io.Varint32(&pk.Size)
	io.Varint32(&pk.TraderTier)
	io.Varint64(&pk.EntityUniqueID)
	io.Varint64(&pk.LastTradingPlayer)
	io.String(&pk.DisplayName)
	io.Bool(&pk.UseNewTradeScreen)
	io.Bool(&pk.UsingEconomyTrade)
	// TODO: Data - unresolved reference: #/definitions/3172631924
}
