// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          29 (0x1D)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AttributeModifier is a nested struct used in the packet.
type AttributeModifier struct {
	ID string
	Name string
	Amount float32
	Operation int32
	Operand int32
	IsSerializable bool
}

func (x *AttributeModifier) Marshal(r protocol.IO) {
	r.String(&x.ID)
	r.String(&x.Name)
	r.Float32(&x.Amount)
	r.Int32(&x.Operation)
	r.Int32(&x.Operand)
	r.Bool(&x.IsSerializable)
}

// AttributeData is a nested struct used in the packet.
type AttributeData struct {
	MinValue float32
	MaxValue float32
	CurrentValue float32
	DefaultMinValue float32
	DefaultMaxValue float32
	DefaultValue float32
	Name string
	Modifiers []AttributeModifier
}

func (x *AttributeData) Marshal(r protocol.IO) {
	r.Float32(&x.MinValue)
	r.Float32(&x.MaxValue)
	r.Float32(&x.CurrentValue)
	r.Float32(&x.DefaultMinValue)
	r.Float32(&x.DefaultMaxValue)
	r.Float32(&x.DefaultValue)
	r.String(&x.Name)
	protocol.Slice(r, &x.Modifiers)
}

// UpdateAttributes Update Attributes
type UpdateAttributes struct {
	EntityRuntimeID uint64
	AttributeList []AttributeData
	Tick uint64
}

// ID ...
func (*UpdateAttributes) ID() uint32 {
	return IDUpdateAttributes
}

// Marshal ...
func (pk *UpdateAttributes) Marshal(io protocol.IO) {
	io.Varuint64(&pk.EntityRuntimeID)
	protocol.Slice(io, &pk.AttributeList)
	io.Varuint64(&pk.Tick)
}
