// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          81 (0x51)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/nbt"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateEquip Seemingly only used for the Horse Inventory... More specifically when the player opens the horse inventory.
type UpdateEquip struct {
	ContainerID uint8
	Type uint8
	Size int32
	EntityUniqueID int64
	Data map[string]any
}

// ID ...
func (*UpdateEquip) ID() uint32 {
	return IDUpdateEquip
}

func (pk *UpdateEquip) Marshal(io protocol.IO) {
	io.Uint8(&pk.ContainerID)
	io.Uint8(&pk.Type)
	io.Varint32(&pk.Size)
	io.Varint64(&pk.EntityUniqueID)
	io.NBT(&pk.Data, nbt.NetworkLittleEndian)
}
