// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:46:18Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          196 (0xC4)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// UpdateClientInputLocks UpdateClientInputLocksPacket
type UpdateClientInputLocks struct {
	InputLockComponentData uint32
}

// ID ...
func (*UpdateClientInputLocks) ID() uint32 {
	return IDUpdateClientInputLocks
}

// Marshal ...
func (pk *UpdateClientInputLocks) Marshal(io protocol.IO) {
	io.Varuint32(&pk.InputLockComponentData)
}
