// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          187 (0xBB)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// SerializedAbilitiesDataSerializedLayer is a nested struct used in the packet.
type SerializedAbilitiesDataSerializedLayer struct {
	SerializedLayer uint16
	AbilitiesSet uint32
	AbilityValues uint32
	FlySpeed float32
	VerticalFlySpeed float32
	WalkSpeed float32
}

func (x *SerializedAbilitiesDataSerializedLayer) Marshal(r protocol.IO) {
	r.Uint16(&x.SerializedLayer)
	r.Uint32(&x.AbilitiesSet)
	r.Uint32(&x.AbilityValues)
	r.Float32(&x.FlySpeed)
	r.Float32(&x.VerticalFlySpeed)
	r.Float32(&x.WalkSpeed)
}

// SerializedAbilitiesData is a nested struct used in the packet.
type SerializedAbilitiesData struct {
	TargetPlayerRawID int64
	PlayerPermissions int8
	CommandPermissions uint8
	Layers []SerializedAbilitiesDataSerializedLayer
}

func (x *SerializedAbilitiesData) Marshal(r protocol.IO) {
	r.Int64(&x.TargetPlayerRawID)
	r.Int8(&x.PlayerPermissions)
	r.Uint8(&x.CommandPermissions)
	protocol.Slice(r, &x.Layers)
}

// UpdateAbilities Sent by the server to update the state of a player's Abilities.
type UpdateAbilities struct {
	Data SerializedAbilitiesData
}

// ID ...
func (*UpdateAbilities) ID() uint32 {
	return IDUpdateAbilities
}

func (pk *UpdateAbilities) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.Data)
}
