// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2025-12-12T23:58:34Z
// Minecraft version:  1.21.130
// Protocol version:   897
// Packet ID:          188 (0xBC)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// AdventureSettings is a nested struct used in the packet.
type AdventureSettings struct {
	NoPvM bool
	NoMvP bool
	ImmutableWorld bool
	ShowNameTags bool
	AutoJump bool
}

func (x *AdventureSettings) Marshal(r protocol.IO) {
	r.Bool(&x.NoPvM)
	r.Bool(&x.NoMvP)
	r.Bool(&x.ImmutableWorld)
	r.Bool(&x.ShowNameTags)
	r.Bool(&x.AutoJump)
}

// UpdateAdventureSettings UpdateAdventureSettingsPacket
type UpdateAdventureSettings struct {
	AdventureSettings AdventureSettings
}

// ID ...
func (*UpdateAdventureSettings) ID() uint32 {
	return IDUpdateAdventureSettings
}

func (pk *UpdateAdventureSettings) Marshal(io protocol.IO) {
	protocol.Single(io, &pk.AdventureSettings)
}
