// Code generated by protocol/packet generator; DO NOT EDIT.
// Generated at:       2026-07-02T16:35:30Z
// Minecraft version:  1.26.30
// Protocol version:   1001
// Packet ID:          337 (0x151)

package packet

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

// VoxelShapesSerializableCells is a nested struct used in the packet.
type VoxelShapesSerializableCells struct {
	// XSize Number of cells along the X axis
	XSize uint8
	// YSize Number of cells along the Y axis
	YSize uint8
	// ZSize Number of cells along the Z axis
	ZSize uint8
	// Storage Solid/empty state per cell
	Storage []uint8
}

func (x *VoxelShapesSerializableCells) Marshal(r protocol.IO) {
	r.Uint8(&x.XSize)
	r.Uint8(&x.YSize)
	r.Uint8(&x.ZSize)
	protocol.FuncSlice(r, &x.Storage, r.Uint8)
}

// VoxelShapesSerializableVoxelShape is a nested struct used in the packet.
type VoxelShapesSerializableVoxelShape struct {
	// Cells Grid of cells representing solid and empty regions
	Cells VoxelShapesSerializableCells
	// XCoordinates Cell boundaries along the X axis
	XCoordinates []float32
	// YCoordinates Cell boundaries along the Y axis
	YCoordinates []float32
	// ZCoordinates Cell boundaries along the Z axis
	ZCoordinates []float32
}

func (x *VoxelShapesSerializableVoxelShape) Marshal(r protocol.IO) {
	protocol.Single(r, &x.Cells)
	protocol.FuncSlice(r, &x.XCoordinates, r.Float32)
	protocol.FuncSlice(r, &x.YCoordinates, r.Float32)
	protocol.FuncSlice(r, &x.ZCoordinates, r.Float32)
}

// VoxelShapes Syncs client with server voxel shape data on world join. This packet contains a copy of all behavior pack voxel shapes data and is used by StartGamePacket.
type VoxelShapes struct {
	// Shapes Voxel shape structural data
	Shapes []VoxelShapesSerializableVoxelShape
	// NameMap Voxel shape name-to-handle mappings
	NameMap any
	// CustomShapeCount The number of custom voxel shapes
	CustomShapeCount uint16
}

// ID ...
func (*VoxelShapes) ID() uint32 {
	return IDVoxelShapes
}

func (pk *VoxelShapes) Marshal(io protocol.IO) {
	protocol.Slice(io, &pk.Shapes)
	// TODO: NameMap - type mapping not found for any
	io.Uint16(&pk.CustomShapeCount)
}
