name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck@v0.3
          GOBIN=$PWD/bin go install honnef.co/go/tools/cmd/staticcheck@v0.3
          ./bin/staticcheck ./...

      - name: Build
        run: go build -o gophertunnel_exe -v .